decentraland/unity-renderer

- .circleci/config.yml
- .github/workflows/ci.yml
- BuildImage/Dockerfile
- browser-interface/package-lock.json
- browser-interface/package.json
- ci-build.sh
- ci-editmode-test.sh
- ci-playmode-test.sh
- ci-setup.sh
- docker-env.sh
> test build using github actions

- .circleci/config.yml
- .gitignore
- browser-interface/package-lock.json
- browser-interface/package.json
- browser-interface/scripts/build.ts
- browser-interface/scripts/publish-artifacts.sh
- browser-interface/scripts/publish.ts
- browser-interface/scripts/tsconfig.json
- browser-interface/scripts/utils.ts
- browser-interface/src/index.ts
- browser-interface/tsconfig.json
Publishes the built artifacts ready to be consumed by the explorer in the URL `https://renderer-artifacts.decentraland.org/branch/${BRANCH}/${PATH}`. Examples: https://renderer-artifacts.decentraland.org/branch/feat/publish-renderer/package.json
> feat: publish WebGL artifacts

- README.md
- docs/code-review-standards.md
- docs/how-to-profile-a-local-unity-build-remotely.md
- docs/how-to-use-unity-visual-tests.md
- docs/style-guidelines.md
Added modified readme and documents with only the Unity relevant information.
> chore: update docs

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Main PR: decentraland/explorer#2345
Quick shortcut from the main PR to test:
https://play.decentraland.zone/branch/feat/gpu-metrics/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:feat/gpu-metrics&DEBUG_ANALYTICS
> feat: system info (gpu) metrics

- unity-renderer/Assets/ABConverter/AssetBundleMenuItems.cs
- unity-renderer/Assets/ABConverter/Core.cs
Cleaned up some code and added 1 helpful menu item for dumping scene ids
> chore: clean AB Converter core code

- README.md
> docs: fix license url

- unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/QuestsUIAnalytics/QuestsUIAnalytics.cs
Standarize the `ui_context` across the quests events.
> chore: quests analytics param standarization

- unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/DebugBridge/DebugBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/Debugging/Performance/PerformanceMeterController/PerformanceMeterController.cs
* Fixed Performance Meter Tool final score calculation (a float cast was missing)
* Added a bit more info to the final results
> fix: performance meter tool final score

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldInputWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWInputHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWSaveController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/EntityInformation/AttributeXYZ.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/UI/Prefabs/CatalogItemAdapter.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/BuildModeHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/Common/EntityInformationView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/Common/FeedbackToolTipView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/GodMode/Inspector/EntityListAdapter.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/GodMode/TopActionsButtons/ExtraActionsView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/GodMode/TopActionsButtons/TopActionsButtonsView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/Common/TooltipController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/Common/TooltipView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/Inspector/EntityListAdapter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/TopActionsButtons/ExtraActionsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/TopActionsButtons/ExtraActionsView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/BuildModeHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/BuildModeHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/ExtraActionsControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/ExtraActionsViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/TooltipControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Prefabs/LandElementView.prefab
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-UI-polishment-Part-2&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=80,154
> fix: [BiW Editor] UI polishment (Part 2)

- .github/PULL_REQUEST_TEMPLATE.md
Use a sounder English grammar for pull requests templates.
> chore: fix PR template grammar

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/BuildModeHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/Common/SceneCatalogView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/Common/ShortcutsView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/Common/BIWSearchBarView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/Inspector/EntityListAdapter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/Inspector/SceneLimitsController.cs
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-polishing-tasks&ENV=zone&position=80,154
2. Press 'k' to open the Builder In World editor.
> fix: [BiW Editor] Polishing tasks

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Resources/BuilderProjectsPanel.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/ControlsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/ControlsHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/Resources/ControlsHUD.prefab
1- Copy related to BiW updated on Controls screen. 
- Note: you will notice some extra changes in this prefabs because I resized all the keys images and the close button.
2-  `BuilderProjectsPanel` message style polished in this prefab as well.
Before
After
> style: BiW shortcut

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
The tooltip "Builder in World" was reduced just to "Builder" on the taskbar for the Builder button.
> style: BiW taskbar button hover updated

- .circleci/config.yml
- ci-playmode-test.sh
- nunit-to-junit.xsl
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/IdleChecker/Tests/IdleCheckerShould.cs
Fix #132
CircleCI only understands the JUnit report format, and we use NUnit, so I transform from NUnit to JUnit and store the results. 
1. Go to failed test report at: https://app.circleci.com/pipelines/github/decentraland/unity-renderer/1354/workflows/40641dd4-f348-491d-9f09-bdcc469bac25/jobs/6369 (or see on this PR pipeline at "[temp] Make CI fail on purpose" commit)
2. See if everything is right
> chore: store test results in junit format

- .circleci/config.yml
- .github/workflows/main.yml
> fix: code coverage outside NPM

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Resources/LoadingHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Textures/Assets/ManaImg.png
In order to improve text legibility, I increase all the fonts size. 
I also updated the Mana image that was not center inside the png canvas.
> style: increase font size in loading screen

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/HotSceneCellViewLoaded.anim
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Prefabs/HotSceneCellView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Resources/ExploreHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/SettingsPanelHUD.prefab
- unity-renderer/Assets/Textures/UI/PlayersIcon.png
- unity-renderer/Assets/Textures/UI/PlayersIcon.png.meta
- unity-renderer/Assets/Textures/UI/SceneInfoContainer.png
- unity-renderer/Assets/Textures/UI/SceneInfoContainer.png.meta
- unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
I made some polishment in the Explore HUD that was quiet abandoned.
Bonus track: I also updated the settings panel title style and the close button size in order to make all the panels consistent.
> style: Explore HUD polish

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Resources/BuilderProjectsPanel.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Resources/ExploreHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/QuestsPanelHUD/Resources/QuestEntry.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/QuestsPanelHUD/Resources/QuestSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/QuestsPanelHUD/Resources/QuestsPanelHUD.prefab
**Titles and sections labels changed from semi-bold style to bold. Sizes were adjusted as well.**
Example
Before
After
------
_Disclaimer_
The setting panel is not included in this branch because I'm working with Mordi in a different one.
> style: panels fonts

- unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
This PR fixes the creation of the floor with the new ID of the floor
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-hardcoded-values
2. Create a new scene
3. Exit from the scene and enter again
> fix: change hardcoded biw value

- browser-interface/scripts/publish.ts
> chore: add validations to CDN pipeline

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldBridge/BuilderInWorldBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
This PR renames the method name so the correct method is invoked in the build and not only in the editor
2. ...
> fix: biw AddAssets message works in build

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/Views/LandElementView.cs
Fixes the button on lands 
2. ...
> fix: editor land button fix

- unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/DrawDistanceControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/ScenesLoadRadiusControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/QualitySettingsData.cs
Closes #880 
Also increased scene load max radius from 4 to 6
> feat: increased draw distance and updated quality presets, #880

- browser-interface/src/index.ts
> fix: logic problem in mobile verification

- unity-renderer/Assets/Scenes/InitialScene.unity
Fix #963 
Use non-deprecated domain
Closes #963 
2. ...
> chore: use play.decentraland.zone

- .github/workflows/set-rollout-manual.yml
> chore: fix typo in github action

- unity-renderer/Assets/Plugins/DCL_CachedXHR/DCL_CachedXHR.jspre
Removes dependencies from kernel
2. ...
> chore: remove always-false codepath of indexed db

- .github/workflows/main.yml
- unity-renderer/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
> chore: updates for new scheme

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Materials/NFTImage.mat
> fix: NFTImage material had wrong material

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldInputWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmos.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmosAxis.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmosController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWGizmosRotate.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Gizmos/BIWScaleGizmos.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/BIWMode.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/FreeCameraController/FreeCameraMovement.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWFreeCameraShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWFreeCameraShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWGizmosShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWGodCameraShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWInputWrapperShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWScaleGizmosShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWScaleGizmosShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Modes/BIWModeShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/Modes/BIWModeShould.cs.meta
This adds unit test for the project, they are stated in this card
https://app.zenhub.com/workspaces/unity-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/939
> feat: biw add more unit test 

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/Tests/AudioTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/Tests/PromiseKeeperShouldBehaveCorrectlyWhen.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/APKWithPoolableAssetShouldWorkWhen_Base.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/APKWithRefCountedAssetShouldWorkWhen_Base.cs
- unity-renderer/Assets/Scripts/Tests/CursorControllerTests/CursorControllerTests.cs
Fixes #977 
This PR deactivate the flaky test
Check that the flaky test are not activated
> feat: deactivate flaky test

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldBridge.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/Tests.meta
> chore: commit meta files

- .github/PULL_REQUEST_TEMPLATE.md
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/LoadingFeedbackController.cs
This PR updates the PR template to match the current link
> feat: changed PR template to match the current link

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWCreatorController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/MissingAsset.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/MissingAsset.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Prefabs/ErrorPrefab.prefab
Fixes #742
It is almost impossible to test this PR without forcing the error from Unity Editor
> feat: implemented biw missing asset prefab collider

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
This PR deactivate the flaky test
> fix: marked flaky test as explicit

- .github/workflows/unprioritize-issues.yml
Changes the unprioritized label for a "new" label in the github action
1. Create a new issue in the unity-renderer repository
2. Check the issue has the "new" label
> Change unprioritized for new label

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/IWebVideoPlayerPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/IWebVideoPlayerPlugin.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/VideoState.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/VideoState.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebGLPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebGLPlugin.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayerNative.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayerNative.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/WebVideoPlayerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/WebVideoPlayerTests.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Fixes #941 
This PR containers a refactor to the WebVideoPlayer class that now receives a plugin interface so it could be mocked and fully tested.
2. ...
> feat: video component send events to kernel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Font/DCLFont.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/Tests/UIContainerStackTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/UIContainerStack.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/UIInputText.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIReferencesContainer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/UIScreenSpace.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIScrollRect/Tests/UIScrollRectTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIScrollRect/UIScrollRect.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/UIText.cs
- unity-renderer/Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs
> fix: UIShape related hiccups

- docs/code-review-standards.md
> docs: code review standards tweaks

- .github/workflows/set-rollout.yml
We're going to deploy to ORG manually. This is temporal.
> chore: rollout deploy percent zero to ORG

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/VideoState.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.jslib
Fix #1151 
WebVideoPlayer.jslib had its indentation fixed, the only change was line 170
See #1151 repro steps
> fix: video texture not reporting pause status after being paused

- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Disable the hologram transition while we fix it
> chore: disable hologram transition

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseSettings_Rendering.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MaterialTransitionController/MaterialTransitionController.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
https://play.decentraland.zone/?renderer-branch=chore/update-default-hologram-transition&position=-118,125
> chore: temporarily disable default hologram transition for meshes

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MaterialTransitionController/MaterialTransitionController.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
https://play.decentraland.zone/?renderer-branch=fix/hologramMaterialOnPooledAssets&position=-118,125
> fix: hologram material on pooled GLTFs, re-enable hologram material

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Font/DCLFont.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/Resources/UIText.prefab
> fix: change fonts used by the sdk

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Make sure that plugin system is initialized as soon as possible to receive kernel config and load bridges as soon as kernel send it
> fix: modify plugin system and start decentraland init order

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTInfoFectcherShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTShapeLoaderControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTShapeLoaderControllerShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTShapeTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/WrappedTextureAsset.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUDView.cs
Test suite to check that the promises are actually fogotten properly in NFT Shape Loader.
Tests should pass.
Pay attention to a scene with NFTs (like -72,-33) and check that everything behaves as normal.
> chore: nft shape loader test suite

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWContext.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorld.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldAudioHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWMainControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuilderInWorldLoadingController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuilderInWorldLoadingView.cs
Defensive fix for biw flaky test
2. ...
> fix: biw flaky test defensive fix

- unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
Fixes #1169  
This PR removes the FPS cap on high quality
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/remove-30-fps-preset
2. Change preset and see that the change apply
> feat: removed fps cap on high quality

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/BaseResolutionControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/QualityPresetControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/SSAOControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/ShadowResolutionControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/DropDownSettingsControlTemplate.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/DropDownSettingsControlTemplate.prefab.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/DropdownControlView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/DropdownControlView.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/DropdownItemColorSwap.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/DropdownItemColorSwap.cs.meta
Created a Dropdown option picker for the Settings menu, it was required for #411 and requested by many.
Go to settings, play around with dropdowns, have fun
> feat: added dropdown options for settings menu

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/DebugController/DebugController.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Interface/INotificationHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Interface/INotificationHUDController.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/NotificationHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/NotificationHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/WelcomeNotification.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/WelcomeNotification/WelcomeNotification.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/WelcomeNotification/WelcomeNotification.asmdef.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/WelcomeNotification/WelcomeNotification.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/WelcomeNotification/WelcomeNotification.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/NotificationsController/NotificationsController.cs
* moved `WelcomeNotification` to it own assembly
* added `INotificationHUDController` interface
Now `NotificationsController` is only managing interfaces
> refactor: reduce NotificationsController assembly dependencies

- unity-renderer/TestResources/VisualTests/BaselineImages/WearableVisualTests_AlphaTestWearable_0.png
A visual test is failing in master with 1% of margin. This PR fixes it.
Check the CI.
> fix: alpha test visual test fail

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/Controls/DropDownSettingsControlTemplate.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/DropdownControlView.cs
Adds scrollbar support to dropdown menus
Check resolution size option here: https://github.com/decentraland/explorer-desktop/pull/12
> feat: added scrollbar to dropdown menus

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldAudioHandler.cs
This PR solves the problem with the audio handler in builder in world
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/biw-flaky-test-audio
2. Test the the audio is still playing in biw
> fix: flaky test

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/CombineLayerUtils.cs
> chore: revert double sided heuristic

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
https://play.decentraland.zone/?renderer-branch=chore/AddChatSpamAutoMute&ream=loki
> chore: add chat spam auto mute

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarButton.cs
Add a NEW label in the taskbar icon.
**IMPORTANT:** This NEW label is something temporal. It will be removed in next releases. In the future, we will implement a system for the new Taskbar to manage these kind of labels for new features.
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/ExploreV2NewLabel
2. Notice the Explore icon in the taskbar has a NEW label indicator.
3. Open the Explore.
4. Notice the NEW label indicator dissapears.
> feat: [Explore V2] Add a NEW label in the taskbar icon

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEventColliders.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/Tests/UUIDComponentShould.cs
Added missing onpointerdown colliders mesh update.
This solves the issue https://github.com/decentraland/unity-renderer/issues/1348
> fix: parametrizable shape onpointerdown collider

- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/GPUSkinning.hlsl
- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/How to generate this shader.md
- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
Fixes CBuffer for some platforms
Fix #1465 
...
Shadows and avatars should work correctly on macOS for Desktop client
> fix: CBuffer not working correctly on some platforms

- unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController_Legacy.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
renamed action buttons:
ACTION_1 > ACTION_3
ACTION_2 > ACTION_4
ACTION_3 > ACTION_5
ACTION_4 > ACTION_6
> refactor: rename action buttons

- unity-renderer/Assets/UIComponents/Scripts/Components/Modal/ModalComponentView.cs
- unity-renderer/Assets/UIComponents/Tests/ModalComponentShould.cs
This PR adds unit test for the UI modal component 
Fix #1532
> feat: modal ui component unit test

- .circleci/config.yml
This PR deactivate the editor test
> fix: editor test

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/DebugController/DebugController.cs
Added missing event subscription
> fix: debug_mode toggling client debug logging

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/BuildModeHUD/Scripts.meta
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/OutlineInWorld.mat
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/OutlineInWorld.mat.meta
This PR adds the outline material to the repository 
> feat: biw add material 

- docs/setup-circleci.md
> docs: add to setup-circle-ci cors policy step for the S3

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Bridge/LoadingBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/LoadingHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/LoadingHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Resources/LoadingHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Tests/LoadingHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Tests/LoadingHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
Removes the obsolete wallet prompt from loading hud
1. Go to: https://play.decentraland.zone/?renderer-branch=refactor/wallet-prompt-removal
2. While loading you should not see a message like: _Please check your wallet (i.e Metamask) and look for the Signature Request_
> refactor: removed obsolete wallet prompt from loading hud

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/Tests/TextShapeTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/UIContainerRect.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/UIInputText.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIScrollRect/UIScrollRect.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/Tests/UITextVisualTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/UIText.cs
lots of sdk components had properties that were not used at all.
> chore: remove unused components properties

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestController.cs
Is part of https://github.com/decentraland/explorer-desktop/pull/34
> chore: change accessibility of variables for desktop

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAudioHandlerLocal.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAudioHandlerRemote.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/StickersController/StickerAnimationListener.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/StickersController/StickersController.cs
This PR adds a small patch to prevent stickers to be instantiated when tests are running.
Run the tests locally and validate that warnings due to footsteps being instantiated aren't being shown.
> chore: footsteps instancing on tests

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
Enables desktop project to inherit those classes
Is part of https://github.com/decentraland/unity-renderer/issues/1587
> chore: ProfileHUDController and view extensibility

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/AvatarAttach/AvatarAttachHandler.cs
> fix: avatar attach component scene boundaries check interval

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/PortableExperienceItem.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
Fixes #1659
it moves a bit the portable experiences in the taskbar and 
> fix: portable experience background

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Legendary.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/NFTItemToggle.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Uncommon.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Unique.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/NFTItemToggle.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/CellNFTUniqueframe.png
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/CellNFTUniqueframe.png.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/CellUniqueHighlight.png
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/CellUniqueHighlight.png.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible_Common.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible_Epic.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible_Legendary.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible_Mythic.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible_Rare.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible_Uncommon.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible_Unique.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
- unity-renderer/Assets/Textures/UI/NFTFrame.png.meta
- unity-renderer/Assets/Textures/UI/NFTStarContainer.png
- unity-renderer/Assets/Textures/UI/NFTStarUniqueContainer.png
- unity-renderer/Assets/Textures/UI/SmartItemIcon.png
- unity-renderer/Assets/Textures/UI/SmartItemIcon.png.meta
- unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
`Closes #1646 `
Adds a badge to smart wearables. The way to check if its a smart item is finding `game.js` content from wearable representations.
1. Go to: https://play.decentraland.org/?DEBUG_MODE=true&NETWORK=ropsten&WITH_COLLECTIONS=43e8f43a-f260-4360-a83a-d447116cf96d&island=I11&position=-14%2C0&realm=artemis&renderer-branch=feat/smart-item-badge
2. Press tab or click the avatar
3. Open collection section
4. Check that some of the wearables have a small _thunder_ icon on the bottom right of the container
5. Wear them like any other wearable, they should be usable as expected
> feat: smart item badges

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/ItemToggle.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Loaded.anim
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/NFTItemToggle.prefab
Architectural and visual improvements in the sections side.
- Sections and subsetions buttons moved upward.
- Categories section width is now smaller.
- Items and spaces between cells are smaller.
- Warning message in ItemsToggle prefab is updated.
- Loading items animation is fixed.
Test link: https://play.decentraland.zone/?renderer-branch=style/BackpackRefinement
Press [I] to open the backpack menu and navigate all the sections to check everything is consistent and that loading items animations are working.
> style: backpack refinement

- unity-renderer/Assets/ABConverter/AssetBundleMenuItems.cs
fixed empty parcels fetch and conversion mechanism
> fix: empty parcels manual AB conversion

- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/ProceduralSkybox.asmdef
- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxConfiguration.cs
- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxShaderUtils.cs
- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxShaderUtils.cs.meta
> refactor: procedural skybox shader variable optimization.

- unity-renderer/Assets/Prefabs/FPSPanel.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/DebugController/Resources/DebugView.prefab
- unity-renderer/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSColoring.cs
- unity-renderer/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSDisplay.asmdef
- unity-renderer/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSDisplay.cs
- unity-renderer/Assets/Scripts/MainScripts/Debugging/Performance/PerformanceMetricsController.cs
The FPS panel was not working while on Fullscreen since you have no focus on the browser/kernel/launcher, so a condition was added to avoid this.
Changed the fps label component from Text to TextMeshPro and assigned a better font with outline
Refactored label string creation for more flexibility
Fixes #1680 
Preview of the panel:
> feat: fps panel improvements

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/InteractionHoverCanvas/InteractionHoverCanvasController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/InteractionHoverCanvas/Resources/InteractionHoverCanvas.prefab
interaction feedback was enable at start
> fix: interaction feedback showing on start

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
https://github.com/decentraland/sdk/issues/161
> fix: remove url support for PE icon

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/InitialSceneReferences/MainSceneFactory.cs
Environment creation at the scene initialization is now extendible so the instantiated prefab can be changed in desktop project.
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/extendible-scene-environment
2. Start DCL as usual, nothing should have changed
> refactor: extendible environment prefab creation

- unity-renderer/Assets/ABConverter/WearablesCollectionClient.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Wearables/WearablesAPIData.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Wearables/WearablesFetchingHelper.cs
Updated API after testing with bots, ABConversion, in-world
> chore: update AB converter and bots wearables fetching API

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/CameraModeArea/CameraModeArea.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/CameraModeArea/CameraModeAreasController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/CameraModeArea/Tests/CameraModeAreasControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Model/NotificationModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/NotificationFactory.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Resources/CameraModeLockedNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Resources/CameraModeLockedNotification.prefab.meta
- unity-renderer/Assets/Textures/UI/CameraIconSmall.png
- unity-renderer/Assets/Textures/UI/CameraIconSmall.png.meta
- unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
add a toast to notify the user that the camera mode is locked by the scene
> feat: add toast when entering in a `CameraModeArea`

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLAvatarTexture.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLAvatarTexture.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/Protocol/Protocol.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Catalyst.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Interfaces/ICatalyst.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/RuntimeComponentFactory/RuntimeComponentFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/MainScripts.asmdef
Add the component AvatarTexture.
SDK PR:
- https://github.com/decentraland/js-sdk-toolchain/pull/87
https://github.com/decentraland/sdk/issues/64
1. Create a test scene with next code (`dcl init` in a empty folder and then replace the `src/game.ts` with):
```const material = new BasicMaterial()
material.texture = new AvatarTexture('0x03eb0BeF2bdbc89BfF468f5bD6e6B559f3Bb61e6')
const cube = new Entity()
cube.addComponent(new Transform({ position: new Vector3(x, y, z) }))
cube.addComponent(new BoxShape())
cube.addComponent(material)
engine.addEntity(cube)
```
2. Open the preview mode adding in the URL `&renderer-branch=feat/add-avatar-texture-component`
> feat: add avatar texture component

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Common/CloseCardModalButton.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/Realms/RealmSelector_Modal.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Modal.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/RealmViewer/RealmSelectorComponentView.cs
- unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs
- unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs
Add OnHover effect to sorting buttons in Realm Selector
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/Add-OnHover-effect-to-sorting-buttons-in-Realm-Selector
2. Open the realm Selector.
3. Test the sorting clicking on each header button.
> fix: Add OnHover effect to sorting buttons in Realm Selector

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/ReportBugButton.cs
> feat: desktop issues goes to `explorer-desktop` repo

- unity-renderer/Assets/Prefabs/Resources/Player.prefab
- unity-renderer/Assets/Resources/Prefabs/InputController.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/CameraChangeScroll.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/CameraChangeScroll.asset.meta
Fix #1770
Adds first/third person camera change on mousewheel 
...
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/mouse-scrollwheel-to-change-view
2. Use mouse scrollwheel to verify that the camera changes from first to third person and vice versa
> feat: add camera change on mouse scrollwheel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/Realms/RealmSelector_Modal.prefab
The message of the pop up has been modified.
From this
`Decentraland is distributed in different independent realms. Warp in between them to meet your friends or visit exclusive events in dedicated environments.`
To this
`Decentraland servers are run by the community. Each server is an independent realm. Wrap in between them to meet your friends or visir exclusive events in dedicated environments.`
> fix: realm message

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/BlockedAndMasterPromisesShould.cs
> fix: duplicated test caused by failed merge

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
> chore: plugin system and explorev2 visibility changes for desktop

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/AvatarEditorAtlas.spriteatlas
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Textures/Assets/LoadingAtlas.spriteatlas
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Textures/Teleport/TeleportLoadingAtlas.spriteatlas
- unity-renderer/Assets/Textures/SpinnerMulticolor/SpinnerMulticolorAtlas.spriteatlas
- unity-renderer/Assets/Tutorial/Atlas/TutorialStepsAtlas.spriteatlas
Improved different atlas texture compression for standalone target platform
> chore: improve atlas compression for standalone target platform

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
Added logout button toggle for desktop as there it is in a bottom container instead of separated
> chore: add logout button toggling for desktop client

- unity-renderer/Assets/Tutorial/Animations/Clips/Default_HideStep.anim
- unity-renderer/Assets/Tutorial/Animations/Clips/Default_ShowStepCamera.anim
- unity-renderer/Assets/Tutorial/Animations/Clips/Tutorial_StepCamera_Feedback.anim
- unity-renderer/Assets/Tutorial/Animations/Controllers/TutorialStep_Camera_Animator.controller
- unity-renderer/Assets/Tutorial/Prefabs/Steps/InitialTutorial/TutorialStep_Camera.prefab
- unity-renderer/Assets/Tutorial/Prefabs/Steps/InitialTutorial/TutorialStep_LockTheCursor.prefab
Fix #1949
Improves the initial and the camera switch tutorial steps
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/tutorial-improvs
2. Start the tutorial
3. Verify that the initial step works as intended
4. Verify that the camera switch from third person to first person step works both with the "V" key and the scroll wheel
> Fix: Improved tutorial steps

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Tests/NotificationHudTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/FPSLimitControlController.cs
Added targetframerate usage in FPS Cap controller for desktop
> chore: add fps cap for desktop

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/NFTItemToggle.prefab
Fix #1947
Fixes wrong categorization of items
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/wrong-item-category
2. Go to your backpack
3. Verify the correct categorization of your items, expecially top/bottom/eyewear
> Fix: fixed wrong categorization of backpack items

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
Fix #1927
Avoid minimap from disappearing when opening and closing the map with hiccups
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/minimap-issue
2. Open and close the map in multiple ways and see if it works fine or if it disappears
> Fix: avoid minimap from disappearing

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/DebugController/DebugBridge.cs
added logging enabling during debug methods call
> fix: debug bridge methods logging toggling

- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/IEmoteAnimationEquipper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/EmoteAnimationEquipper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/EmoteAnimationEquipperShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmotesHUD/EmotesHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
Some code review was forgotten in #1992, these changes are contained here.
> chore: emote catalog code review

- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/WearableItemResolver.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
Null handling for emotes in case the EmoteAnimationPlugin is not present.
> chore: null handling for emotes

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DataStore_Rendering_Extensions/DataStore_WorldObjects_Extensions.cs
> fix: key not found in dictionary issue

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/BuilderMainPanelController.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/LimitInputField/LimitInputField.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/NewProject/NewProjectSecondStepView.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Tests/BuilderMainPanelControllerShould.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishMapView.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/Scripts/Publisher.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/BuilderInWorldBridge.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Tests/BIWKernelBridgeShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/Protocol/ProtocolV2.cs
This PR makes some small improvements to the biw projects
1. Go to: https://play.decentraland.zone/?NETWORK=ropsten&renderer-branch=feat/biw-final&kernel-branch=feat/biw-invalidate-scene-info
2. Test builder in world projects
> feat: biw final refinement

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/Views/Projects/ProjectCardView.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishProjectDetailView.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/Scripts/Publisher.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestController.cs
Fixes #2023 
This PR fixes a problem with the cache of the images that we have in projects and some refinements from the dry run of the feature
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/biw-projects
2. Test that the project images are downloaded correclty
3. Test that the rotation of the project doesn't affect the scene
> feat: biw rotation and cache 

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/APK_AB_GameObject_Promise_Should.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/BlockedAndMasterPromisesShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AssetBundleDepMapLoadHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/APKWithPoolableAssetShouldWorkWhen_Base.cs
Fixed asset bundles not being able to load a second time
> fix: AB not loading a second time

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLTexture.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromise_Texture.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_TextureSize.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_TextureSize.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/TextureHelpers/TextureHelpers.cs
- unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Reverting the AssetPromise_Texture max size limitation due to issues in UI atlases breaking
> revert: "feat: AssetPromise_Texture now has a max size (#2067)"

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/AnalyticsHelper/AnalyticsHelper.cs
This PR changes the name of the analytics event 
1. Go to: https://play.decentraland.zone/?renderer-branch=style/param
2. Open an external link and check that is correctly send the new event
3. Start the voice chat and check that the event is sent correctly
> style: better naming for voicechat and external linkevent

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/BuildModeHUD/Resources/BuilderInWorldLoadingView.prefab.meta
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/BuildModeHUD/Resources/Common/ShortcutsView.prefab
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Resources/SearchBar/SearchContainerView.prefab
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/ScenesController/ScenesViewController.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/Views/Projects/ProjectCardView.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishProjectDetailView.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/SceneManager/SceneManager.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/Textures/white_close.png
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Visuals/Textures/white_close.png.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExperiencesViewer/Scripts/ExperiencesViewerComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Resources/LoadingHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_ExperiencesViewer.cs
This PR polish the biw tool and fix #1551 
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/biw-polish&kernel-branch=feat/biw-invalidate-scene-info
2. Test builder in world completly
> feat: biw polish

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Resources/UsersAroundListHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Scene Icon POI.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Scene Icon.prefab
- unity-renderer/Assets/TextMesh Pro/Resources/Fonts & Materials/Inter-BoldBlackStroke.mat
- unity-renderer/Assets/TextMesh Pro/Resources/Fonts & Materials/Inter-BoldBlackStroke.mat.meta
This PR fixes some small UI issues regarding broken textures, fonts and positions updates.
The screenshots bellow highlights the affected UI.
> style: UI fixes

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
Fix #2026
Fixes the situation in which other players wearable were shown in your backpack
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/wearables-change
2. Follow the steps explained in issue #2026 
3. Verify that it doesn't happen anymore
> Fix: fixed possibility of equipping others wearable

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/BuilderMainPanelController.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Analytics/BIWAnalytics.cs
Fix #2113 
This adds more analytics for biw
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/biw-add-analytic
2. Test that the analytics are added
> feat: add analytics for biw projects

- unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationsPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
Add links to ADRs in Emotes and AvatarSystem
> chore: add ADRs documentation to Emotes and AvatarSystem

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
Fix #2123
Fixes issue that prevented footsteps from being played in first person
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/footsteps
2. Walk in third person and in first person
3. Verify that your sounds are played correctly
> fix: footsteps in first person were unhearable 

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/ReportBugButton.cs
Solves https://github.com/decentraland/explorer-desktop/issues/234 by redirecting the report and adding new labels.
> chore: report bug update for desktop

- unity-renderer/Assets/Rendering/UI.meta
- unity-renderer/Assets/Rendering/UI/ChargeWheel.meta
- unity-renderer/Assets/Rendering/UI/ChargeWheel/M_ChargeBar.mat
- unity-renderer/Assets/Rendering/UI/ChargeWheel/M_ChargeBar.mat.meta
- unity-renderer/Assets/Rendering/UI/ChargeWheel/M_ChargeBarV2.mat
- unity-renderer/Assets/Rendering/UI/ChargeWheel/M_ChargeBarV2.mat.meta
- unity-renderer/Assets/Rendering/UI/ChargeWheel/SG_ChargeBar.shadergraph
- unity-renderer/Assets/Rendering/UI/ChargeWheel/SG_ChargeBar.shadergraph.meta
- unity-renderer/Assets/Rendering/UI/ChargeWheel/SG_ChargeBarV2.shadergraph
- unity-renderer/Assets/Rendering/UI/ChargeWheel/SG_ChargeBarV2.shadergraph.meta
- unity-renderer/Assets/Rendering/UI/ChargeWheel/UIChargeWheel.cs
- unity-renderer/Assets/Rendering/UI/ChargeWheel/UIChargeWheel.cs.meta
This PR adds the required elements to implement a loading wheel into the UI using a shader and a simple script to control it.
2. ...
> Feat: UI loading wheel

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DCL.Runtime.asmdef
> fix: missing TestUtils reference

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/IProfanityFilter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/IProfanityFilter.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/ProfanityFilterSharedInstances.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/RegexProfanityFilter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/ThrottledRegexProfanityFilter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/ThrottledRegexProfanityFilter.cs.meta
Adds a Throttling Profanity Filter to replace the old one, this one is much more performant and it throttles itself over several frames if needed.
Part of https://github.com/decentraland/unity-renderer/issues/2201 
> feat: Throttled Profanity Filter

- unity-renderer/Assets/ABConverter/Core.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/TaskUtils/TaskUtils.cs
- unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
- unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporterInspector.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Fixes local GLTF import by dragging an GLB into the Project folder
Fixes #2238 
Drag a GLB into the Project folder, it should be imported correctly,
> fix: local gltf import

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/EntityIdHelper.cs
This PR fix the problem with the UUID events not being fired correctly
2. ...
> fix: UUID events not being fired correctly

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/EntityIdHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/MessagingControllersManager.cs
This PR increments the budget of the messages to have better performance on scenes that handles lots of messages
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/entity-budget
> feat: add more budget to the processing of the messages

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
This is a mitigation for the problem of the avatars
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/avatar-problem
> fix: avatar player name bug

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/EntityIdHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/PhysicsCast/PhysicsCast.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/PhysicsCast/Tests/PhysicsCastTest.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
This PR fix the raycasting of the entities
1. Go to: https://sdk-test-scenes.decentraland.io/?position=-101%2C50&realm=localhost&renderer-branch=fix/raycasting-entity
2. The ray should make the box glow when it hits
> fix: entity raycast

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Test that avatar now has faces 
> fix: avatars have no facial features

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/BIWBridge.asmdef
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/BuilderInWorldBridge.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/ECSComponentSenderHandler.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/ECSComponentSenderHandler.cs.meta
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/IComponentSendHandler.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/IComponentSendHandler.cs.meta
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/LegacyComponentSender.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderInWorldBridge/LegacyComponentSender.cs.meta
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Data/BuilderScene/BuilderScene.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Interfaces/IBuilderScene.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/SceneManager/SceneManager.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/InitialSceneReferences/MainSceneFactory.cs
This PR does a small refactor for BIW so we are preparing the ground for the new ecs
1. Go to: https://play.decentraland.zone/?renderer-branch=refactor/biw-prepare-for-ecs7
2. Test that builder in world still works as normal
> refactor: biw prepare for ecs7

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Fixes the taskbar buttons when entering the world as a guest.
https://user-images.githubusercontent.com/56365551/169115825-e693f258-1f5a-45b6-ac37-5210c5a115f9.mov
1. Login as a guest
2. Click on the taskbar buttons
3. All of them should work properly
> fix: taskbar buttons when entering as a guest

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromise_Texture.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/APK_Texture_Promise_Should.cs
> fix: unhandled exception when loading base64 images

- README.md
- docs/how-to-connect-with-play-decentraland-org.md
> docs: how to connect from the Editor to play.decentraland.org

- unity-renderer/Assets/Scenes/InitialScene.unity
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Resources/Male/DontmindmejusttriggeringCI.anim.meta
Update the female walking animation.
Female walking anim was not looping correctly, it should be fixed here.
> fix: update female walking animation

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/Performance/PerformanceMetricsController.cs
Changed the way the scene memory scoring is presented to the analytics.
Also changed the name of the feature flag.
> fix: performance analytics id instead of position

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
`Links to #2321 `
Test coverage for `WorldChatWindowController`.
> chore: added tests for WorldChatWindowController

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/Performance/PerformanceMeterController/PerformanceMeterController.cs
Adds GC Allocation values to the performance meter report.
Search game object `Main`, right click on `DebugBridge`, and select `Run Performance Meter Tool for 30 seconds`
The report should contain GC Allocation values:
This will only work on Unity Editor, as far as I know, this value is always zero on WebGL
> chore: added GC allocations to performance meter report

- .gitignore
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/NativeBridgeCommunication/Tests/NativeBridgeCommunicationShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/MessagingBus.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/MessagingController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/QueuedSceneMessage/QueuedSceneMessage.cs
The reliableKey and tag keys are the same. This PR helps the GC to reduce the amount of reference counts by N=amount of messages.
This PR should help reducing the CG time in its first phase (mark).
> chore: help garbage collector with strings

- unity-renderer/Assets/Rendering/Culling/CullingController.cs
- unity-renderer/Assets/Rendering/Culling/CullingControllerUtils.cs
Reduced culling controller allocations to zero.
> chore: reduce culling controller allocations

- README.md
- docs/ecs7-component-creation.md
- docs/summary.json
This adds a small documentation about how to add components to the new system 
There are no changes to the code. this is the only documentation 
> feat: add docs to create components

- docs/summary.json
For docs scrapping: Removed mdx formatting from summary.json file
...
This change impacts menu generation in https://tech-docs.decentraland.org/
> fix: removed accidental mdx tags from json file

- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
Updated Particle UI package to the latest version.
Every few seconds a slight performance drop was noticed in the profiler that was caused by this package, so I've updated it to check if it was fixed and it was.
Now, this performance drop is being done just once at the start of the application.
> chore: update particle ui package

- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Editor/ProtobufEditor.cs
Fixes the code not being compiled on windows
> fix: code not compiling on windows editor

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Animator/DCL.ECSComponents.Animator.asmdef
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Animator/Tests/DCL.Components.AnimatorShould.asmdef
This PR fixes master
Unity should compile now
> fix: missing assembly references

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Events/PointerInputRepresentantion.cs
This PR adds the timestamp for the OnPointerEvents
Can't be tested
> feat: add lamport timestamp

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/VoiceChatHUD/VoiceChatWindowComponentView.cs
> fix: inconsistent state of voice chat bar

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/Resources/SignupHUD.prefab
> fix: typo in SignupHUD.prefab

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Scripts/UserContextMenu.cs
Fixes the click triggering event of the buttons inside the user contextual menu.
1. Open the friends UI
2. Click the three dots button over an entry
3. Click on any of the options
4. The action should trigger properly
> fix: user contextual menu button clicks

- unity-renderer/Assets/Rendering/Common/ForwardRenderer.asset
Reverted the forward renderer changes for blur since it's not implemented yet.
Everything should look as usual.
> revert: forward renderer changes for blur

- unity-renderer/Assets/Rendering/UI/Rainbow/M_UIRainbowTopBar.mat
- unity-renderer/Assets/Rendering/UI/Rainbow/M_UIRainbowTopBar.mat.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
This PR adds the animated gradient to the top bar of the main menu
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/UI-Gradient-Top-Bar
2. Open the main menu
3. Verify the gradient is animated
> Feat: UI Gradient Top Bar

- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/PBFiles/AudioSource.cs.meta
> fix: add meta file for desktop

- .github/auto_assign_config.yml
- .github/workflows/auto-assign.yml
Auto assign action to add reviewers automatically.
> chore: auto assing reviewer

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/NearbyChannelElement.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChannelElement.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatEntryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatEntryShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDTests.asmdef
Adds a label to show the member count of every channel in the conversation list.
1. Open the conversation list
2. Check that every channel shows the amount of members
3. Check that the nearby channel does not have the label
> feat: channel entries member count label

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
Fixes the interaction with the profile HUD from the start menu.
1. Click on your avatar's picture (top right)
2. Open the profile window
3. Interact with the different components, all of them should work
> fix: clickable profile hud components

- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
Update rider's package in Unity
This only affects editor
> chore: update rider package

- unity-renderer/Assets/Tutorial/Prefabs/Resources/TutorialView.prefab
- unity-renderer/Assets/Tutorial/Prefabs/Steps/InitialTutorial/TutorialStep_AvatarJumping.prefab
- unity-renderer/Assets/Tutorial/Prefabs/Steps/InitialTutorial/TutorialStep_AvatarMovement.prefab
- unity-renderer/Assets/Tutorial/Prefabs/Steps/InitialTutorial/TutorialStep_Camera.prefab
- unity-renderer/Assets/Tutorial/Prefabs/Steps/InitialTutorial/TutorialStep_OpenControlsPanel.prefab
- unity-renderer/Assets/Tutorial/Prefabs/Steps/InitialTutorial/TutorialStep_TutorialCompleted.prefab
- unity-renderer/Assets/Tutorial/Prefabs/Steps/InitialTutorial/TutorialStep_Welcome.prefab
- unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_Tooltip_StartMenu.cs
- unity-renderer/Assets/Tutorial/Scripts/Tutorial.asmdef
- unity-renderer/Assets/Tutorial/Scripts/TutorialStep.cs
- unity-renderer/Assets/Tutorial/Scripts/TutorialView.cs
Tutorial is using lot of World Position references to anchor UI, which translates to issues when having different canvas modes.
It should be fixed properly using screen position and doing a conversion instead of matching world position but let's not block the release with this.
Do the tutorial, it should work fine
https://play.decentraland.zone/?renderer-branch=fix/some-camera-canvases-issues&RESET_TUTORIAL
> fix: tutorial camera canvas issues

- browser-interface/src/index.ts
> chore: better help message

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
Small fixes
1. Added YOU prefix when sending a message in channels
2. Reparenting context menu wasn't working correctly
> fix: Add "You" in channels

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
> Send expeced action when rejecting a friendship request

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatHUD.prefab
Removes the disclaimer message on private chats.
1. Open private chats. No disclaimer should be present
> fix: remove disclaimer message on private chat

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
Fixes #2856
Change any wearable then try running, animations should work as expected.
We should also test if it works when another character changes a wearable, do we see it correctly being animated? 
> fix: animation states not being correctly updated

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/IFriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendsTabComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/FriendsHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/UserContextMenu/UserContextMenuPanel.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/FriendsHUDWindowMock.cs
This PR removes the usage of remote feature flag friends_by_online_status and modifies friends list UI to only keep implementation of this feature flag ON option (friends divided in two lists by online / offline status)
Check if friends lists work well
> Cleanup feature flag "friends by online status"

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/AnchorPointsGetterHandlers/GetAnchorPointsHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/Tests/AvatarAttachHandlerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/AvatarAttach/Tests/AvatarAttachHandlerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/AvatarAttach/Tests/AvatarAttachPlayerHandlerShould.cs
Mini hotfix release needed for the art week
> Release 2022-08-25

- unity-renderer/Assets/Scripts/Editor/PreBuildProcessing.cs
Added needed emscripten memory cap arguments in PreBuildProcessing script
> spike: unity 2021 emscripten memory cap update

- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
- unity-renderer/ProjectSettings/PackageManagerSettings.asset
Updating UI Particle package to 4.1.6 using scoped registry instead of direct github url
There should be no change visible to the user
> chore: update UI particle package to 4.1.6

- .github/auto_assign_config.yml
> chore: remove Pravus as reviewer

- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarCurator.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/Tests/PlayerNameShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Emotes.cs
Main -> Dev merge through intermediate branch
> Main -> Dev

- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/BaseAvatarReveal.cs
- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/RevealAnimation.anim
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatChannelController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
Fixed: https://github.com/decentraland/unity-renderer/issues/2970
Fixed: https://github.com/decentraland/unity-renderer/issues/2949
> release: hotfixes 20220912

- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/BaseAvatarReveal.cs
- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/RevealAnimation.anim
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatChannelController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
> hotfixes 20220912 into dev

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
Fix exit condition in emotes
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/loop-emotes
2. Play an emote
3. Verify all exit conditions (walk/jump/animation end)
> Fix: fixed exit condition in emotes

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
This branch is an equivalent to: fix/Avatar-hud-collectible-empty-list-message
As per a problem with commit signing not set up correctly, this new branch has been created and no difference should exist between them.
Please refer to: https://github.com/decentraland/unity-renderer/pull/3042 to see original details
> signed version of Avatar-hud-collectibles approved PR

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- Added missing nullcheck when removing an AvatarShape
Solves https://github.com/decentraland/sdk/issues/459
> fix: avatar shape null key fatal error when removed using SDK

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModel.cs
Under certain conditions, some Urls arrived incomplete. This PR aims to solve that, one of the consequences solved by this PR is the issue: https://github.com/decentraland/unity-renderer/issues/2812
In order to test this PR we need to get the kernel version from the PR: https://github.com/decentraland/kernel/pull/524
Unity Debug url: https://play.decentraland.zone/?kernel-branch=feat/add-base-url-to-profiles&
> Compose correct url for face and body

- README.md
- docs/how-to-use-asset-bundle-coverter.md
- docs/how-to-use-asset-bundle-coverter/Screen_Shot_2021-11-16_at_13.26.56.png
- docs/how-to-use-asset-bundle-coverter/Screen_Shot_2021-11-22_at_16.14.02.png
Moving from notion documentation about AB converter
> chore: add doc on how to use asset bundle converter

- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin.meta
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorMaterialsHolder.cs
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorMaterialsHolder.cs.meta
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorPlugin.asmdef
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorPlugin.asmdef.meta
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorPlugin.cs
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorPlugin.cs.meta
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorPrefabs.meta
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorPrefabs/Resources.meta
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorPrefabs/Resources/AbDetectorMaterials.prefab
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorPrefabs/Resources/AbDetectorMaterials.prefab.meta
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorTracker.cs
- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorTracker.cs.meta
- unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationsPlugin.cs
- unity-renderer/Assets/Materials/ABDetectorMaterial.mat
- unity-renderer/Assets/Materials/ABDetectorMaterial.mat.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystem.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DebugConfig.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Multimap.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Multimap.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/DebugBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.cs
- unity-renderer/ProjectSettings/TagManager.asset
This PR:
1. Adds a tool for highlighting which mesh renderers are rendering the content loaded with asset bundles and which ones are loaded with raw GLTFs. DebugBridge receives a call from Kernel triggered by the chat command. This calls is passed to a ABDetectorPlugin via DataStore values as an intermediary. ABDetectorPlugin loads dedicated debug materials lazily on first call and applies them to the whole scene.
2. Adds custom low level data structure Multimap which is a generic wrapper for a dictionary of lists. After discussion with Alex we figured there are no class like that and decided to try using this one since it allows to not repeat a lot of code.
[This PR](https://github.com/decentraland/unity-renderer/pull/2058) was used as a reference for implementation.
Closes #2911
This …
> feat: ab detection functionality

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDAudioHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
Changes where we consider an avatar dirty. Also updated catalog everytime independent the avatar is dirty or not.
1. Go to https://play.decentraland.org/?WITH_ITEMS=urn%3Adecentraland%3Amatic%3Acollections-thirdparty%3Acryptoavatars%3A0x28ccbe824455a3b188c155b434e4e628babb6ffa%3A0%2Curn%3Adecentraland%3Amatic%3Acollections-thirdparty%3Acryptoavatars%3A0x28ccbe824455a3b188c155b434e4e628babb6ffa%3A1%2Curn%3Adecentraland%3Amatic%3Acollections-thirdparty%3Acryptoavatars%3A0x28ccbe824455a3b188c155b434e4e628babb6ffa%3A2%2Curn%3Adecentraland%3Amatic%3Acollections-thirdparty%3Acryptoavatars%3A0x28ccbe824455a3b188c155b434e4e628babb6ffa%3A3%2Curn%3Adecentraland%3Amatic%3Acollections-thirdparty%3Acryptoavatars%3A0x28ccbe824455a3b188c155b434e4e628babb6ffa%3A4,urn%3Adecentraland%3Amatic%3Acollections-t …
> fix: collection not appearing in backpack

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelJoinErrorModal.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelJoinErrorModal.prefab.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowComponentView.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowController.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelJoinErrorWindowPlugin.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelJoinErrorWindowView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelJoinErrorWindowView.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelJoinErrorWindowComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelJoinErrorWindowComponentViewShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelJoinErrorWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelJoinErrorWindowControllerShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Channels.cs
Adds a modal that is shown whenever the join channel operation fails for unknown reasons.
1. The easiest way is to modify `ChatController.JoinOrCreateChannel` method forcing a `JoinChannelError(Errorcode.Unknown)`
2. Go to the channel browser
3. Click the join button on any channel
4. A Modal indicating the error should be shown
> implementation of join channel error modal for unknown reason

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CollapsableChannelMemberListComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelMembersComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
> fix: reloading of member list when is previously opened

- protocol-gen/package-lock.json
- protocol-gen/package.json
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/BillboardRegister.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Handler/BillboardComponentHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Billboard/Tests/BillboardShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBBillboard_Defaults.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBTextShape_Defaults.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBUiText_Defaults.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/ECSTextShapeComponentHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/Tests/ECSTextShapeShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/Tests/UiTextHandlerShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/ProtoConvertUtils.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Billboard.gen.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/TextShape.gen.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Texts.gen.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/UiText.gen.cs
Update from https://github.com/decentraland/protocol/pull/67
> fix: ECS7 billboard behavior and text align

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationsFeature.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/NotificationMessagesHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/NotificationMessagesTests.asmdef
Adds profanity filtering to the main chat notification panel and top chat notification panel.
1. Have both users joined a channel or available to talk through #nearby
2. Get the chat notification panel visible (close any chat window)
3. Send messages like: "shit", "fucking hell", "my ass is nice"
4. The messages should be filtered in the notification panel
5. Open any chat window, except conversation list
6. Repeat step 3
7. The messages should be filtered in the top notification panel
> feat: implemented profanity filtering on chat notification panel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/GeneralChatChannelHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/PublicChatPublicWindowMock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IPublicChatWindowView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatChannelComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatChannelControllerShould.cs
Adds the possibility to mute/unmute the nearby channel.
1. Open the #nearby channel
2. Click on the bell icon to mute it
3. Get someone to write messages in #nearby
4. Close any chat window
5. You should not receive any chat notification from #nearby
6. Open #nearby then unmute the channel
7. You should start receiving notifications again
> feat: implemented mute status on nearby channel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Hotfix for notification panel being above experiences panel
> hotfix 20221028

- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/BaseAvatarReveal.cs
- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/M_FinalGhost.mat
Fix #3383
Removed the Update method from the avatar revealer
...
1. Go to: https://play.decentraland.zone/?renderer-branch=chore/avatar-reveal-opt
2. Verify that all the avatars load as previously with the hologram shader
3. Go in different crowded areas and check that everything is looking normal for avatars
> Chore: improved avatar revealer script

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ConversationListHUD.prefab
Added "BROWSER" label to the channels header.
1. Open the conversation list
2. You should be able to see a label saying BROWSER aside of the channel browser button
3. Click it, should open the channel browser
> feat: added channel browser label

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
There was an exception going on produced by automatic-joined channels implementation:
```
NullReferenceException: Object reference not set to an instance of an object
WorldChatWindowController.ConnectToAutoJoinChannels () (at Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs:279)
WorldChatWindowController.HandleChatInitialization () (at Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs:273)
DCL.Chat.ChatController.InitializeChat (System.String json) (at Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs:68)
UnityEngine.GameObject:SendMessage(String, Object)
<ProcessMessages>d__17:MoveNext() (at Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunicat …
```
> fix: null reference exception when automatic channels feature flag is not set

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/FatalErrorReporter/WebFatalErrorReporter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Report the exception that triggered a ReportAvatarFatalError
Everything should work as usual, nothing specific to be tested.
> chore: add payload to ReportAvatarFatalError

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTAssetLoadHelper.cs
Adds fallback support for WEBP image formats into GIF until we have proper WEBP support
Fixes https://github.com/decentraland/unity-renderer/issues/3492
Go to `14,100`, animated gifs should work.
> fix: webp fallback support to gif

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Resources/NavMap.prefab
Remove the nonsense button that appears in the nav map
Open the map, and check if the button is not there.
> Fix: Remove the nonsense button that appears in the nav map

- .github/auto_assign_config.yml
> chore: update reviewer list

- README.md
Updated readme with 2021.3.14f1 Unity version
> chore: updated readme with new unity version

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/AssemblyInfo.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/AssemblyInfo.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/FriendRequestHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/FriendRequestHUDTests.asmdef.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDComponentViewShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDControllerShould.cs.meta
Adds the test coverage for `SendFriendRequestHUDController` & `SendFriendRequestHUDComponentView`.
> chore: send friend request tests

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
This reverts commit e25b7ed9a8c9e7aec88df1099adb5b54091b4ad7.
> revert: "feat: ecs7 plugin always enabled (#3618)"

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/CRDTService/CRDTServiceImpl.cs
> fix: crdt race condition with hotreload scene

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
> fix: avoid infinity values on VideoProgressEvent message (#3639)

- unity-renderer/Assets/DCLPlugins/RealmsPlugin/DCL.Plugins.RealmsPlugin.asmdef
- unity-renderer/Assets/DCLPlugins/RealmsPlugin/RealmPlugin.cs
- unity-renderer/Assets/DCLPlugins/RealmsPlugin/RealmsSkyboxModifier.cs
- unity-renderer/Assets/DCLPlugins/RealmsPlugin/RealmsSkyboxModifier.cs.meta
- unity-renderer/Assets/DCLPlugins/RealmsPlugin/Tests/RealmsSkyboxModifierTests.cs
- unity-renderer/Assets/DCLPlugins/RealmsPlugin/Tests/RealmsSkyboxModifierTests.cs.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/TimeReporter/Tests/TimeReporterShould.cs
- unity-renderer/Assets/Rendering/ProceduralSkybox/TimeReporter/TimeReporter.cs
- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/RealmsInfoBridge/RealmsInfoBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Bridges/RealmsInfoBridge/RealmsInfoHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/DynamicSkyboxControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/SkyboxTimeControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/ScriptableObjects/SkyboxControlledByRealm.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Resources/ScriptableObjects/SkyboxControlledByRealm.asset.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/SliderSettingsControlView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/CommonSettingsScriptableObjects.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/BaseControllers/SliderSettingsControlController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SettingsControllers.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/DynamicSkyboxControlController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/SkyboxTimeControlController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsData/GeneralSettings.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_SkyboxConfig.cs
- unity-renderer/Assets/Scripts/Tests/ValidationTests.meta
- unity-renderer/Assets/Scripts/Tests/ValidationTests/SettingAssetsValidationTests.cs
- unity-renderer/Assets/Scripts/Tests/ValidationTests/SettingAssetsValidationTests.cs.meta
Closes #3562
1. Goto /changerealm mgoldman.dcl.eth
2. Observe that skybox is changed to 10 AM - visually 
3. Observe that Settings for skybox in the UI Settings are non-interactable (grayed out) and fixedHours set to 10:00
> Feat: worlds skybox modifier v1

- protocol-gen/package-lock.json
- protocol-gen/package.json
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/TextShape/Tests/ECSTextShapeShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/ProtoConvertUtils.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/TextShape.gen.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/Texts.gen.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ProtocolBuffers/Generated/UiText.gen.cs
deprecate `Liberation Sans` font for SDK7
> fix: SDK7 deprecate `Liberation Sans` font

- unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/ECSScenesUiSystem.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
copy from this PR already merged to `dev` https://github.com/decentraland/unity-renderer/pull/3637
unloading an sdk7 scene with ui breaks the loading of other scenes due to an exception
how to reproduce:
1- go to https://play.decentraland.zone/?position=13%2C-137&renderer-branch=main
2- make sure you are inside the scene with the cubes and the psychedelic ui
3- now move away from the scene until it unloads
4- scenes will stop loading
> hotfix: SDK7 Ui breaking scenes loading

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
> Align dev history with main

- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
> hotfix: other avatar's emote not playing (#3709) 

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Resources/CameraController.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
Fixes #3677 
- UIs should look and behave as in product. Pay attention to the inputs and try to spot not working buttons or interactable elements.
> feat: remove UI camera

- .github/auto_assign_config.yml
Adding @mikhail-dcl to review pool
> chore: updated review list

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
> Align histories hotfix 12/19

- unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/DCLPlugins.LoadingScreenPlugin.asmdef
- unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/LoadingScreenPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/Bridge/LoadingBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/LoadingHUD/LoadingHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Tests/HUDTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/DCL.LoadingScreen.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Interfaces/ILoadingScreenView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/_LoadingScreen.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/DCL.LoadingScreen.Tests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/LoadingScreenControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
Adds the feature flag implementation to select which loading screen to use
> feat: feature flag for new loading screen

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelSearchHUD.prefab
- unity-renderer/Assets/Textures/UI/PlusIcon.png
- unity-renderer/Assets/Textures/UI/PlusIcon2.png
- unity-renderer/Assets/Textures/UI/PlusIcon2.png.meta
This branch fixes the missing asset in the create channel button.
1- Go to: https://play.decentraland.zone/?renderer-branch=style/CreateChannelButtonFixIcon
2- Open the chat view and then go to the channel browser. The create button now should show a plus icon instead of a white square.
> style: fix create channel icon

- unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/ISocialAnalytics.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalytics.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendRequest.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/FriendRequestHUDPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/ReceivedFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SentFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/ReceivedFriendRequestHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Scripts/UserContextMenu.cs
Adds metrics for the new friend requests
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/friend-request-metrics&&kernel-branch=feat/receive-friend-request-rpc
2. Make all kind of operations with the new friend requests flow, all should work as usual
3. Check that the metrics are being sent to metabase: `friend_request_sent`, `friend_request_approved`, `friend_request_rejected`, `friend_request_cancelled`
4. In case if any error occurs, `friend_request_error` should be registered
> feat: friend request metrics

- unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/LoadingScreenPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/DCL.LoadingScreen.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Interfaces/ILoadingScreenView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Tests/LoadingScreenControllerTests.cs
> feat: porting decoupled loading screen events to renderer

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDViewV2.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD_V2.prefab
This PR adds the V2 correction of the ProfileHUD onto the feat/passport-cleanup
To take into consideration:
- Currently there is no way to skip a line by design, we can add the capability if a decision on it is made.
> fix: profile hud v2

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/AssetPromise_GLTFast_Loader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Asset_GLTFast_Instance.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Asset_GLTFast_Loader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFDownloaderWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFTextureDownloaderWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFastDownloadProvider.cs
- unity-renderer/Packages/packages-lock.json
Updated dependencies, there should be no behavioural changes.
> chore: update gltfast to 5.0.0

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
Fixes a tutorial getting stuck issue
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/tutorial-avatar
2. Play the tutorial
3. Verify it finishes correctly
> Fix: fixed tutorial getting stuck in explore step

- unity-renderer/Assets/Rendering/Common/ForwardRenderer.asset
> Fix: Assign Postprocess data to the custom one to fix transparency

- unity-renderer/Assets/DCLPlugins/ECS7/Systems/ScenesUiSystem/Tests/ECSScenesUiSystemShould.cs
Re-added mistakenly removed test for issue fixed in [another PR](https://github.com/decentraland/unity-renderer/pull/3770)
> chore: re-add SDK7 ui text displacement test

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/UiElementUtils.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/UiElementUtils.cs.meta
related to https://github.com/decentraland/sdk/issues/519
+added `SetElementDefaultStyle` function to set up `Label` style properly.
> fix: sdk7 UiText style

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModel.cs
> hotfix dev alignment

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningNotification.prefab
Closes #2521 
- Adjusted messages in the code and in the prefab
0. First remove your browser from Windows settings of High Preformance (https://docs.decentraland.org/player/general/hardware-acceleration/)
1. Go to: https://play.decentraland.zone/?renderer-branch=chore/adjust-graphics-card-warning-message
2. Observe graphic card warning message to appear with a new text.
> chore: adjusted graphics card warning message

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/_LoadingScreen.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/LoadingFeedbackController.cs
- unity-renderer/ProjectSettings/ProjectSettings.asset
Adds a beta tag to the decoupled loading screen
Also, added the feature flag to stop the loading message to update when the decoupled loading screen flag is on
> fix: Added beta tag to decoupled loading screen

- ci-build.sh
Fix: https://github.com/decentraland/unity-renderer/issues/4094
> feat: disable sentry on prod

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab.meta
Restore old prefab to allow desktop compilation
...
> Fix: restored missing prefab for desktop build

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Resources/FriendRequestNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/TopNotificationHUD.prefab
Fixes #4049 
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/notification-icons
2. Login with two different users
3. Send friend request from user A to B
4. User B should add a notification with the heart icon a little bit smaller than before
5. Accept the friendship with user B
6. User A should receive a notification with the heart icon
> fix: improved friend request notification icon

- .circleci/config.yml
> chore: try to restore cache from `dev` branch if not exists

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDView.cs
Fix #4157
removes pointless log error
> Fix: removed pointless log error for passport opening ct exception

- browser-interface/packages/unity-interface/kernelConfigForRenderer.ts
- browser-interface/packages/unity-interface/loader.ts
Fix metrics and report correctly the version
> fix: consume @dcl/explorer instead of @dcl/unity-renderer/@dcl/kernel

- README.md
> chore: some README updates

- browser-interface/packages/shared/chat/sagas.ts
- browser-interface/packages/shared/rolloutVersions.ts
- browser-interface/packages/shared/session/getPerformanceInfo.ts
- browser-interface/packages/unity-interface/kernelConfigForRenderer.ts
- browser-interface/packages/unity-interface/loader.ts
- docs/how-to-renderer-protocol.md
It should fix the version for the metrics reports
> Hotfix 2023 02 01

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
> hotfix: avatar timeout and crash avoidance

- unity-renderer/Assets/Prefabs/Resources/Player.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Resources/Female/Idle.anim.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/CharacterPreview.prefab
Removes the female idle animation and standarizes it to the male one
1. Go to: https://play.decentraland.zone/?explorer-branch=fix/remove-female-idle-animation
2. Select a female character
3. Check that your idle animation in world is correct. 
4. Check that the idle animation in the backpack is correct. Try it with different emotes and wearables. Check that the snapshot after changing wearables is taken correctly. The profile icon should have a straight standing character (we had cases with wrong animations in which the head was tilted)
5. Check that the idle animation for other female characters is correct. 
> fix: remove female idle animation

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_RedBox.cs
The teleport get freezed for all users using DEBUG_MODE url param.
More context about the issue: https://decentralandteam.slack.com/archives/C02UW81R26B/p1675358573320379
1. Go to: https://play.decentraland.zone/?explorer-branch=hotfix/teleport-get-freezed-for-in-debug-mode&DEBUG_MODE
2. Teleport to any place.
3. Notice the app doesn't freeze.
> hotfix: The teleport get freezed for all users using DEBUG_MODE

- browser-interface/package-lock.json
- browser-interface/package.json
Should fix some critical Rollbar errors right now:
* https://rollbar.com/decentraland/World/items/72012/ thanks to https://github.com/livekit/client-sdk-js/pull/549 and https://github.com/livekit/client-sdk-js/pull/538
* https://rollbar.com/decentraland/World/items/73493/ by https://github.com/livekit/client-sdk-js/pull/568
> fix: livekit uncatched errors

- browser-interface/package-lock.json
- browser-interface/package.json
Just remerging https://github.com/decentraland/unity-renderer/pull/4239
> fix: comms errors

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/WebRequestControllerInterfaces.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequest.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestController.cs
This PR is aimed to refactor the WebRequestController extra layer by deprecating the old system, with the old system still working but in obsolete status, more frequent merges will be able to be made and the task can be divided into smaller bits.
The step for this PR:
- Create the new API and make old API obsolete [x]
For each step to be accepted all PlayTests must be correct.
Further steps will be implemented once this PR is accepted
> Web Request Layer new API

- browser-interface/packages/shared/scene-loader/sagas.ts
- browser-interface/runTestServer.js
- browser-interface/static/preview.html
BLOCKER, fixes preview mode in SDK7, please merge ASAP to dev
2. ...
> fix: preview mode

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/PBVideoPlayer_Defaults.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/VideoPlayer/VideoPlayerHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Decentraland/renderer/renderer_services/FriendRequestRendererService.gen.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Material.gen.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/VideoPlayer.gen.cs
VideoPlayer Loop for SDK7 was not working
> fix: video player loop for SDK7

- ci-build.sh
- ci-import-avpro.sh
- ci-setup-license.sh
- ci-setup.sh
- unity-renderer/ProjectSettings/ProjectSettings.asset
> chore: update from main

- .circleci/config.yml
- browser-interface/package.json
- browser-interface/scripts/checkFileSizes.ts
- browser-interface/scripts/publish.ts
- scripts/hash-unity-files.sh
Reduces build time by ~3 minutes
> feat: compress brotli in parallel

- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDControllerDesktop.cs
- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDViewDesktop_V2.cs
- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/ProfileHUDViewDesktop_V2.cs.meta
- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop_V2.prefab
- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Profile/Resources/ProfileHUDDesktop_V2.prefab.meta
> hotfix: bring profile HUD v2 to desktop

- .circleci/config.yml
This is too expensive and maybe we only need this test on `dev`...
> feat: drop file size test outside main/dev

- .circleci/config.yml
> chore: fix merge queue to main to build mac

- ci-build.sh
> chore: enable sentry on prod

- browser-interface/packages/shared/comms/adapters/voice/loopback.ts
- browser-interface/packages/shared/voiceChat/VoiceCommunicator.ts
Tackles https://rollbar.com/decentraland/World/items/72012/ in a not-so-elegant way
> fix: setRemoteDescription failing on stable

- browser-interface/packages/shared/comms/sagas.ts
Tackles https://rollbar.com/decentraland/World/items/73707/
> fix: don't fail on retry realm

- .gitignore
Minor update to run local setup with StreamingAssets
> chore: gitignore update

- browser-interface/packages/unity-interface/UnityInterface.ts
Partial fix for: https://github.com/decentraland/unity-renderer/issues/4393
> fix: do not depend on lodash

- browser-interface/packages/shared/comms/adapters/voice/loopback.ts
- browser-interface/packages/shared/voiceChat/VoiceCommunicator.ts
Reverts decentraland/unity-renderer#4388
> Revert "fix: setRemoteDescription failing on stable"

- browser-interface/packages/config/index.ts
- browser-interface/packages/unity-interface/initializer.ts
Useful for debugging on machines without a graphics card
> feat: allow swift shader as debug flag

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Resources/ChatNotificationMessage.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Resources/FriendRequestNotification.prefab
`Fixes #3957 `
Adds click & hovering sound effects to chat and friend request notifications.
1. Go to: https://play.decentraland.org/?explorer-branch=feat/hover-chat-noti-sfx
2. Send or receive messages in the chat
3. Send or receive friend requests
4. Open the chat notification panel
5. Hover the notifications with the mouse
6. Click them
7. You should hear a sound effect
> feat: added audio component to chat & friend request notifications

- browser-interface/Makefile
> feat: add unity files to run explorer locally

- browser-interface/packages/shared/apis/host/Players.ts
- browser-interface/packages/shared/comms/peers.ts
- browser-interface/packages/shared/social/avatarTracker.ts
Fix getPlayersInScene
...
2. ...
> Fix players observables

- unity-renderer/Assets/Rendering/Common/UniversalRenderPipelineAsset.asset
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/BaseNoise.bmp.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/CubemapPlazaCut.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/Default_Skybox_FarClouds.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/Default_Skybox_NearClouds_2.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/SingleCloud.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/SingleCloud_Normals.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/T_Moon.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/T_Star01.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/T_Stars01.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/T_Sun.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/T_ToonClouds01.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/T_ToonStar.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/SkyboxAddressables/ProceduralSkyboxAssets/Textures/moon.png.meta
- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxCamera.cs
- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxController.cs
- unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/RenderingScaleControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/SettingsControlModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/SettingsControlView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSComponentManagerLegacy/ECSComponentsManagerLegacy.cs
- unity-renderer/Assets/Tutorial/Prefabs/Resources/TutorialView.prefab
Skip the queue and merge these PRs all together:
- https://github.com/decentraland/unity-renderer/pull/4449
- https://github.com/decentraland/unity-renderer/pull/4447
- https://github.com/decentraland/unity-renderer/pull/4446
- https://github.com/decentraland/unity-renderer/pull/4441
- https://github.com/decentraland/unity-renderer/pull/4415
> chore: merge pending PRs

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSComponentManagerLegacy/ECSComponentsManagerLegacy.cs
Omit the useless unknown error
> fix: omit useless error

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Resources/FriendRequests/SendFriendRequestHUD.prefab
`Fixes #4424 `
1. Go to: https://play.decentraland.zone/?explorer-branch=fix/friend-request-cursor
2. Open the passport of other user
3. Click the add friend button
4. Click over the input field to send a message in the friend request
5. You should be able to see the cursor blinking in the input area
> fix: show caret in friend request input field

- browser-interface/package-lock.json
- browser-interface/packages/entryPoints/index.ts
- browser-interface/packages/lib/browser/persistentStorage.ts
- browser-interface/packages/shared/session/index.ts
- browser-interface/packages/shared/session/sagas.ts
Addresses https://github.com/decentraland/unity-renderer/issues/4467
> fix: authentication not checking for expiration

- unity-renderer/Assets/AddressableAssetsData/AssetGroups/Map Renderer.asset
- unity-renderer/Assets/DCLServices/MapRendererV2/Addressables/PlayerMarkerObject.prefab
- unity-renderer/Assets/DCLServices/MapRendererV2/Addressables/PlayerMarkerObject.prefab.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/ColdUsersMarkersInstaller.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererChunkComponentsFactory.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererConfiguration.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererDrawOrder.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/PlayerMarkerInstaller.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/PlayerMarkerInstaller.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/CoordsUtils/ChunkCoordsUtils.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/CoordsUtils/ICoordsUtils.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker/IPlayerMarker.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker/IPlayerMarker.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker/PlayerMarker.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker/PlayerMarker.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker/PlayerMarkerController.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker/PlayerMarkerController.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker/PlayerMarkerObject.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/PlayerMarker/PlayerMarkerObject.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/Tests/Factory/MapRendererChunkComponentsFactoryShould.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapRendererV2Tests.asmdef
- unity-renderer/Assets/DCLServices/MapRendererV2/Tests/PlayerMarker.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/Tests/PlayerMarker/PlayerMarkerControllerShould.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/Tests/PlayerMarker/PlayerMarkerControllerShould.cs.meta
> Add Player Marker

- browser-interface/scripts/publish-preview.sh
- ci-publish-preview-artifacts.sh
Fix https://github.com/decentraland/unity-renderer/issues/4404
> chore: skip preview publish for merge queue branches

- .github/workflows/set-rollout.yml
> Update dev from main

- browser-interface/packages/shared/comms/sagas.ts
- browser-interface/packages/shared/meta/types.ts
This reverts commit 145daee853de0b3d360fd5658a4a21f7523cbb87.
...
2. ...
> Revert "feat: reconnect flag to test unexpected behavior (#4549)"

- unity-renderer/Assets/DCLPlugins/SentryPlugin/DCL.Plugins.SentryPlugin.asmdef
- unity-renderer/Assets/DCLPlugins/SentryPlugin/SentryController.cs
Adds wallet ID to sentry.
- Ensure build still runs.
- The actual changes can only be tested in Sentry on deployment.
> feat: add wallet address to better track sentry errors

- unity-renderer/Assets/Prefabs/Resources/Bridges.prefab
> chore: removed missing monobehaviour

- browser-interface/packages/config/index.ts
- browser-interface/packages/lib/decentraland/authentication/signedFetch.ts
- browser-interface/packages/renderer-protocol/inverseRpc/services/signRequestService.ts
- browser-interface/packages/shared/comms/adapters/LivekitAdapter.ts
- browser-interface/packages/shared/comms/sagas.ts
- browser-interface/packages/shared/loading/sagas.ts
- browser-interface/packages/shared/meta/sagas.ts
- browser-interface/packages/shared/portableExperiences/sagas.ts
- browser-interface/packages/shared/renderer/sagas-helper.ts
- browser-interface/packages/unity-interface/portableExperiencesUtils.ts
- browser-interface/test/index.ts
- browser-interface/test/unit/portableExperiences.test.tsx
* fix: race condition on wearables
* fix: onLoginCompleted -> waitForRenderer
* fix: tests to check dummy rpcClient
* fix: linter
* refactor: move initialize PX to shared/PX
* fix: document why debouncing
* add empty parcels copy to build process
* restore export for disconnectRoom
---------
...
2. ...
> fix: race condition on PX (#4611)

- browser-interface/packages/shared/friends/sagas.ts
Fixes the issue: [link](https://github.com/decentraland/social-service/issues/161).
When sending a friend request to someone, the first try is erring. A second attempt will properly create the friendship request in the service.
2. Send a Friendship Request to a user you have not previously sent one to.
3. The Friendship Request is sent successfully.
> hotfix: friendship requests

- unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
Wearables are filtered on the lambda service level so they are not propagated further in an invalid state
...
2. ...
> hotfix: Remove invalid wearables from the collection

- browser-interface/packages/shared/profiles/sagas/handleSaveLocalAvatar.ts
Addresses https://github.com/decentraland/unity-renderer/issues/4628
> hotfix: only update avatar if it changed

- browser-interface/packages/shared/profiles/sagas/comms/index.ts
> hotfix: delay and return value issues in fetch peer profile

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Asset_GLTFast_Loader.cs
> chore: align main 20230322

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/MainChatNotificationsComponentView.cs
After some time using the client, the taskbar becomes unusable.
This pr fixes this exception:
```
NullReferenceException: Object reference not set to an instance of an object
at DCL.Chat.Notifications.MainChatNotificationsComponentView.ShowNotifications () [0x00015] in <e58e993a0c7e4744a3635d3e58da92c3>:0 
at DCL.Chat.Notifications.ChatNotificationController.ResetFadeOut (System.Boolean fadeOutAfterDelay) [0x00000] in <e58e993a0c7e4744a3635d3e58da92c3>:0 
at DCL.Chat.Notifications.ChatNotificationController.SetVisibility (System.Boolean visible) [0x00000] in <e58e993a0c7e4744a3635d3e58da92c3>:0 
at DCL.Chat.Notifications.ChatNotificationController.VisiblePanelsChanged (System.Collections.Generic.HashSet`1[T] newList, System.Collections.Generic.HashSet`1[T] oldList) [0x00007] in …
```
> hotfix: chat notification exception when using the taskbar

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
- unity-renderer/Assets/Rendering/Culling/CullingController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseSettings_Rendering.cs
> hotfix: force update when offscreen by feature flag

- .github/workflows/sync-main-to-dev.yml
Fix https://github.com/decentraland/unity-renderer/issues/4350
You can test forking the following repo and testing: https://github.com/kuruk-mm/action-test
> chore: add action to auto-sync main to dev

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
Closes #4487 (Potentially)
- set transition time to `0` if `animationState is null` 
2. Check avatar animations are working fine, especially with transition to expressions
> fix: avatarAnimatorLegacy animationState is null in State_Expression

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendshipException.cs
Adds a message with the error code on FriendshipExceptions thrown.
1. Launch the explorer with `&DEBUG_MODE` param
2. Send friend requests, should work as usual
3. If by any means one fails, you should be able to open the logs and see the error code of the request
> chore: improved log message for FriendshipException

- browser-interface/packages/shared/comms/logic/rfc-4-room-connection.ts
Hotfix for https://github.com/decentraland/unity-renderer/pull/4782
> hotfix: profile messages need not be reliable

- browser-interface/packages/shared/comms/sagas.ts
We need this to debug reconnection problems
> hotfix: more comms logs

- browser-interface/packages/config/index.ts
- browser-interface/packages/shared/analytics/types.ts
- browser-interface/packages/shared/comms/adapters/LivekitAdapter.ts
- browser-interface/packages/shared/comms/adapters/voice/liveKitVoiceHandler.ts
> hotfix: cherry pick from dev

- unity-renderer/Assets/Resources/Sentry/SentryOptions.asset
- It lowers the transaction recording so we avoid hitting the limits too quickly.
- Observe sentry limitations after deployment
> fix: lower transaction rate limits for sentry

- docs/ecs7-component-creation.md
fixed js-sdk-toolchain protocol command directory
> chore: update component creation document

- docs/scene-boundaries-checking.md
Added ADR-192 reference in the SBC md document.
> chore: update SBC documentation ADR-192

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
Fixed the performance meter tool that is triggered by the debug config in Unity Editor.
Also, it now logs the loading time. 
> fix: performance meter not working for loading flow

- browser-interface/package-lock.json
- browser-interface/package.json
- scripts/package-lock.json
- scripts/package.json
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Defaults/Tests/TextureDefaults/TextureShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/Texture.gen.cs
Issue: https://github.com/decentraland/sdk/issues/516
Related PRs
* https://github.com/decentraland/protocol/pull/151
* https://github.com/decentraland/js-sdk-toolchain/pull/594
> chore: sdk7 remove texture mirror-once

- unity-renderer/Packages/packages-lock.json
- update hash for several packages (most importantly - gltFast)
> Chore: updated gltFast, UniTask and shared-dependency packages

- unity-renderer/Assets/DCLServices/EmotesCatalog/EmoteEntityDto.cs
- unity-renderer/Assets/DCLServices/EmotesCatalog/EmotesRequestWeb.cs
Fixes emote not having rarity
Open backpack or inspect other players' passport, emotes should have the correct rarity.
> fix: emote rarity

- browser-interface/packages/shared/apis/expressionExplainer.ts
- unity-renderer/Assets/DCLPlugins/EmoteAnimations/Addressables/EmbeddedEmotes.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Addressables/Female/cry.anim.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Addressables/Female/hands_in_the_air.anim.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Addressables/Male/cry.anim.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Addressables/Male/hands_in_the_air.anim.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Materials/Particle Expression/Particle Expression Confetti Material.mat
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Materials/Particle Expression/Particle Expression Confetti Material.mat.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Materials/Particle Expression/Particle Expression Cry Material.mat
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Materials/Particle Expression/Particle Expression Cry Material.mat.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Prefabs/AvatarExpressionConfetti.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Prefabs/AvatarExpressionConfetti.prefab.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Prefabs/AvatarExpressionCry.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Prefabs/AvatarExpressionCry.prefab.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Textures/AvatarParticleExpressionConfetti.png
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Textures/AvatarParticleExpressionConfetti.png.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Textures/AvatarParticleExpressionCry.png
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Textures/AvatarParticleExpressionCry.png.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/StickersController/Resources/StickersFactory.asset
Local branch from https://github.com/decentraland/unity-renderer/pull/5228
> feat: expression confetti and cry

- unity-renderer/Assets/Rendering/UI/Blur/Simplified.meta
- unity-renderer/Assets/Rendering/UI/Blur/Simplified/DCL_GaussianBlur.mat
- unity-renderer/Assets/Rendering/UI/Blur/Simplified/DCL_GaussianBlur.mat.meta
- unity-renderer/Assets/Rendering/UI/Blur/Simplified/SimpleGaussianBlur.shader
- unity-renderer/Assets/Rendering/UI/Blur/Simplified/SimpleGaussianBlur.shader.meta
Created a simple Gaussian blur for UI, its not being used yet
> feat: added a simple gaussian blur compatible with unity UI

- unity-renderer/Assets/Rendering/Culling/CullingController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/BasicMaterial.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/AssetPromise_GLTFast_Instance.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/AssetPromise_GLTFast_Loader.cs
- unity-renderer/Packages/packages-lock.json
Removed a few `OperationCancelledExceptions` in an effort to fix https://github.com/decentraland/unity-renderer/issues/5344
Removed warnings about GLTF not supporting certain features in prod.
Fixed a Missing Reference Exception at the culling controller
> chore: clean console

- unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/ISocialAnalytics.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalytics.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/ReportFriendRequestToAnalyticsExtensions.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/ReceivedFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SentFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/FriendRequestHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/Tests/SendFriendRequestHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Scripts/UserContextMenu.cs
Fix https://github.com/decentraland/unity-renderer/issues/5238
> chore: add friends analytics parameters

- browser-interface/packages/shared/analytics/types.ts
- browser-interface/packages/shared/chat/sagas.ts
- browser-interface/packages/shared/types.ts
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatMessage/ChatMessage.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatWindowControllerShould.cs
Fix https://github.com/decentraland/unity-renderer/issues/5266
> chore: add chat analytic parameters

- browser-interface/packages/shared/friends/sagas.ts
Fixes a bug in messages with new friendships flow, the messages weren't being shown
> Remove friend request check for messages

- browser-interface/packages/shared/wearablesPortableExperience/sagas.ts
Fix smart wearable that doesn't provide a scene.json
> hotfix: smart wearables without scene.json

- browser-interface/package-lock.json
- browser-interface/packages/config/index.ts
- browser-interface/packages/entryPoints/index.ts
This PR ensures that the SSO_URL parameter is a valid URL and has the same top-level domain that the URL of the current browser
> hotfix: validate-sso-url

- unity-renderer/Assets/DCLPlugins/ECS7/InteractionHoverCanvas/Resources/ECSInteractionHoverCanvas.prefab
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/InteractionHoverCanvas/Resources/InteractionHoverCanvas.prefab
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/InteractionHoverCanvas/Resources/PointerButtonHoverIcon.prefab
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/InteractionHoverCanvas/Resources/PrimaryButtonHoverIcon.prefab
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/InteractionHoverCanvas/Resources/SecondaryButtonHoverIcon.prefab
This PR fixes the missing textures for key and mouse inputs on SDK7 scenes.
> fix: add interaction missing textures

- browser-interface/package-lock.json
- browser-interface/package.json
Update eth-connect dependency to temporarily remove number validation for rpc call id response
> feat: update eth connect

- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
- Loading GLTFs should work like it is on prod, this mostly affects the Desktop version.
> fix: gltf repo reference

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ConfirmationPopup/Resources/GenericConfirmationPopup.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/MyAccountHUD/Prefabs/BlockedList.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Notifications.cs
This PR was created to update the blocking accounts copies which turned misleading once we discovered that blocked users could still see the avatar of the person who blocked them.
1. Open this [link](https://play.decentraland.org/?explorer-branch=style/blocking-copies)
2. Try to block someone and check the block prompt copy updated has been implemented.
Before:  `Blocking someone means that you and that person can no longer see each other's avatars, messages, and send friend requests.`
After: `Blocking someone means that you will no longer see their avatar in-world. Both of you will also not see each other's messages in private and public chats and will not be able to send each other messages or friend requests.`
3. Then go to the "Blocked Accounts" section and check the new description …
> style: update blocking accounts copies

- browser-interface/package-lock.json
- browser-interface/package.json
- browser-interface/packages/shared/world/runtime-7/sourcemap/index.ts
https://github.com/decentraland/scene-runtime/pull/211
https://github.com/decentraland/unity-renderer/assets/8042536/a9095a07-f237-4802-9780-12144597231a
https://github.com/decentraland/unity-renderer/assets/8042536/607cb164-24dd-43f3-84d8-a675dc5d9e19
> fix source-mapping in preview mode

- scripts/package-lock.json
- scripts/package.json
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/UIText/UiTextHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DecentralandProtocol/UiText.gen.cs
Reverts decentraland/unity-renderer#6207
> Revert "chore: support for uiText wrapping"

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFastDownloadProvider.cs
- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
Manifest will be reversed when the branch is merged in the plugin repository.
> chore: Updated the GLTFast plugin

- browser-interface/packages/shared/comms/adapters/WebSocketAdapter.ts
- browser-interface/packages/shared/realm/connections/ArchipelagoConnection.ts
> fix: comms handshake
