- browser-interface/scripts/publish.ts
UnityLoader.js was renamed to unity.loader.js in #279
> chore: fix ci unity.loader.js name

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/DeployedScenesFetcher.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/DeployedScenesFetcher.asmdef.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/DeployedScenesFetcher.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DeployedScenesFetcher/DeployedScenesFetcher.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/CatalystTypes.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/Land/LandHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/TheGraph.cs
Helper class to fetch:
* Lands (with their scenes) owned (or with permissions) by a ETH address
* Deployed scenes at chosen parcels
> feat: add helper to fetch user deployed scenes

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BuilderInWorldGodMode.cs
_In builder in world, if you select multiple entities and start dragging ( or unselect them clicking on a selected entity) them from a entity, all entities will be centered in the pointer. The desired movement will be to drag them from where they are with the mouse offset, instead of center them._
1. Go to: https://play.decentraland.zone/?index.html&renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-Dragging-multiple-entities-centers-them-in-the-pointer&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=100,100
2. Press `K` to open the Builder In World editor.
> fix: [BiW] Dragging/Unselecting when multiple entities are selected center them in the pointer

- unity-renderer/Assets/Builder/Scripts/Gizmos/DCLBuilderScaleGizmo.cs
_Scale gizmos is working strange when you try to scale in the three axis at the same time_
_If you have multiple entities selected and scale in the Z axis, they move as well when they should only scale_
1. Go to: https://play.decentraland.zone/?index.html&renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-scale-is-not-working-correctly&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=100,100
2. Press `K` to open the Builder In World editor.
> fix: BiW scale tool is not working correctly

- README.md
Link to test builds are incorrect in README.md. And it was loading master kernel version instead of the desired branch with the wrong link.
Example:
bad usage (don't load proper kernel version)
https://play.decentraland.zone/branch/feat/gpu-metrics/?index.html&renderer=urn:decentraland:off-chain:renderer-artifacts:feat/gpu-metrics
correct link:
https://play.decentraland.zone/branch/feat/gpu-metrics/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:feat/gpu-metrics
> docs: fix README bad link format

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWCreatorController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDController.cs
If you drag and drop an entity from the collection menu the entity is not created when you drop but when you click again in the scene. The entity should be created right when you drop it in the scene (Fixes #383).
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-Editor-dropping-an-entity-in-the-scene-should-place-it-right-there&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=100,100
3. Drag some items from the Catalog to the scene.
4. Notice that the item is directly placed in the floor.
> fix: BiW Editor dropping an entity in the scene should place it right there

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BuilderInWorldGodMode.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/FreeCameraMovement.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/BuildModeHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/GodMode/TopActionsButtons/ExtraActionsView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/TopActionsButtons/ExtraActionsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/TopActionsButtons/ExtraActionsView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/ExtraActionsControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/ExtraActionsViewShould.cs
The camera view should be reset to the center of the scene (Fixes #375).
We have added a new "Reset Camera" option menu:
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:feat/BiW-editor-add-functionality-to-reset-the-camera-view&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=100,100
3. Move the camera around the scene.
4. Click on the "Reset Camera" button.
5. Notice that the camera is reset to its original position.
> feat: BiW - Add functionality to reset the camera view

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWOutlinerController.cs
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-Entities-in-the-scene-dont-un-highlight-if-you-interact-with-the-UI&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=80,154
> fix: BiW - Entities in the scene dont un-highlight if you interact with the UI

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/UI/Adapters/CatalogItemAdapter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/Common/QuickBarController.cs
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-fixes-on-catalog-item-thumbnails&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=80,154
> fix: BiW - Several fixes on thumbnails management

- .gitignore
- unity-renderer/.gitignore
**WHY**
The locally dumped ABs folder duplicated rule in the `/root/.gitignore` file is triggering problems tracking the [ABs controllers folder](https://github.com/decentraland/unity-renderer/tree/master/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles) when creating new repos like @kuruk-mm  is doing for the desktop-client repo.
**WHAT**
* Removed unneeded ABs folder rule at `/root/.gitignore` (since we already have a rule for the dumped local ABs at `/root/unity-renderer/.gitignore`
* Updated `/root/unity-renderer/.gitignore` ABs folder rule to point to the closest relative `/AssetBundles/` folder (the one used when dumping ABs locally, that we don't want to track in git)
* Tested that everything is tracked and ignored correctly locally
> chore: update asset bundles folder git ignore rule

- unity-renderer/Assets/ABConverter/ABConverter.asmdef
- unity-renderer/Assets/ABConverter/VisualTests.cs
- unity-renderer/Assets/ABConverter/VisualTests.meta
- unity-renderer/Assets/ABConverter/VisualTests/AssetBundlesVisualTestHelpers.asmdef
- unity-renderer/Assets/ABConverter/VisualTests/AssetBundlesVisualTestHelpers.asmdef.meta
- unity-renderer/Assets/ABConverter/VisualTests/AssetBundlesVisualTestHelpers.cs
- unity-renderer/Assets/ABConverter/VisualTests/AssetBundlesVisualTestHelpers.cs.meta
- unity-renderer/Assets/ABConverter/VisualTests/Editor.meta
- unity-renderer/Assets/ABConverter/VisualTests/Editor/GameViewUtils.cs
- unity-renderer/Assets/ABConverter/VisualTests/Editor/GameViewUtils.cs.meta
- unity-renderer/Assets/ABConverter/VisualTests/Editor/GameViewUtilsTests.cs
- unity-renderer/Assets/ABConverter/VisualTests/Editor/GameViewUtilsTests.cs.meta
Added AB converter own visual tests helper to avoid problems when importing unity-renderer project as a UPM in desktop-client.
> chore: add AB converter own visual tests helper

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BuilderInWorldGodMode.cs
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-Editor-Error-while-reseting-scale-values&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=80,154
> fix: [BiW Editor] Error while reseting scale values from details panel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/SearchHandler/SearchHelper.cs
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-Panel-Search-in-collections-should-not-be-case-sensitive&ENV=zone&ENABLE_BUILDER_IN_WORLD
2. Click on the "**Builder In World**" button in the taskbar.
3. Use the search textbox.
> fix: [BiW Panel] Search in collections should not be case sensitive

- unity-renderer/Assets/Rendering/Culling/CullingController.cs
- unity-renderer/Assets/Rendering/Culling/CullingObjectsTracker.cs
- unity-renderer/Assets/Rendering/Culling/Interfaces/ICullingObjectsTracker.cs
- unity-renderer/Assets/Rendering/Culling/Tests/CullingControllerShould.cs
- unity-renderer/Assets/Rendering/Culling/Tests/CullingObjectsTrackerShould.cs
- unity-renderer/Assets/Rendering/Culling/Tests/CullingObjectsTrackerShould.cs.meta
This PR attempts to fix the CullingController issue that prevents the "Done" button to work correctly on avatar editor due to a nullRef error.
- added null checks on `CullingController.ResetObjects()`
- ensure `CullingObjectsTracker` doesn't include the avatar preview meshes.
Go to avatar editor, put some wearables and click on Done.
> fix: culling controller avatar editor issue

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
Sometimes the materials attached to the facial features are destroyed. It can be "easily" tested in our current .zone build when going through the signup process in a couple of our default avatars.
> fix: materials on facial features were being destroyed while loading

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Common.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/NFTItemToggle.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/Uncommon.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/NFTItemInfo.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
#573 
Now the NFT info card shows the network the wearable belongs to. The implementation is not ideal, using the protocol in the `urn` and finding key words will work for now but wont last long. Unfortunately we cannot retrieve the information correctly until the catalysts provide it https://github.com/decentraland/catalyst/issues/535.
Open the avatar editor and click in the small info button in the bottom left corner of a collectible. It should show the network properly.
Test L2 Collectible: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:feat/network_in_wearable_card&WITH_COLLECTIONS=urn:decentraland:mumbai:collections-v2:0xa5e32410f4d58f0b6c4d747287f1148f41e13fa3
Normal collections: …
> feat: network flag now is visible in the wearables info card

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldInputWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BuilderInWorldGodMode.cs
1. Go to BiW.
2. Edit a Scene.
3. Add entities.
4. Click on Publish.
5. Click on the Entities in the background.
1. Go to Builder in World.
2. Edit a Scene.
3. Select an entity with rotation tool.
4. Start Publish flow.
5. Rotation gizmo and highlights are shown in the thumbnail.
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-Entities-selection-issues-during-publication-process&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=80,154
> fix: [BiW Editor] Entities selection issues during publication process

- unity-renderer/Assets/Rendering/Culling/Interfaces/CullingControllerSettings.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
- unity-renderer/Assets/Tutorial/Scripts/TutorialController.cs
The culling controller was culling the tutorial robot due to a race condition.
We fix it by having the robot disabled until needed (and the CullingController's ignore mask is ready as well).
#588
> fix: tutorial robot is culled

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldBridge/BuilderInWorldBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWSaveController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BuilderInWorldGodMode.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/FreeCameraMovement.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/BuildModeHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/Common/NewProjectDetailsView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/Common/NewProjectDetailsView.prefab.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDInitializationModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/Common/PublicationDetailsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/BuildModeHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/BuildModeHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/PublicationDetailsControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/Protocol/ProtocolV2.cs
BiW creates a Project in Builder, every time the Players edit a Scene that does not have a Project associated.
BiW must update the Project thumbnail of the project:
* Consider this last should only happen if there are unpublished changes
* Automatic screenshots will always be done using the reset camera view
1. Go to: https://play.decentraland.zone/branch/feat/BiW-should-update-Project-metadata-and-thumbnail-Kernel-side/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:feat/BiW-should-update-Project-metadata-and-thumbnail&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=80,154
2. Press 'K' to open the Builer In World editor and test the 3 use cases.
> feat: [BiW Editor] BiW should update Project metadata and thumbnail (Unity side)

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
Until we receive the first profile, the Done button in the avatar editor can be pressed. This causes an upwards crash in kernel by reporting a "not ready" profile.
#590
> fix: avatar editor race condition

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs
fixes #609
testing:
1- go to https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/609-biw-teleport-edit-correct-scene&ENABLE_BUILDER_IN_WORLD
2- open builder panel
3- choose to edit a scene next to a land where you are owner/operator
4- click on "editor" button
6- after loading screen, the correct scene should be loaded to edit.
> fix: BiW loading incorrect scene after teleport

- unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/BuildModeHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/BuildModeHUDControllerShould.cs
While editing a Scene, the Player may decide to exit without publishing the changes. This does not mean the player loose the Project done so far, but they will need to be reminded:
"There are unpublished changes in this project. But don't worry, next time you enter the editor you will be able to continue where you left off!" 
A "Got it!" button will allow you to exit the editor. 
A "Back" button will cancel the Exit action
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:feat/BiW-confirmation-dialog-while-exiting-the-editor&ENV=zone&position=80,154
2. Press 'K' to open the Builder In World editor.
3. Make any change in the scene.
4. Exit from the editor.
5. Notice the modal message.
Finally I had not have to use the new implemented …
> feat: [BiW Editor] Confirmation dialog while exiting the editor

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Resources/BuilderProjectsPanel.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/Resources/ControlsHUD.prefab
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:feat/BiW-editor-shortcut-needs-to-be-added-to-the-list&ENV=zone&position=80,154
2. Press 'C' to open the main Controls panel.
3. Click on the Builder In World icon in the taskbar.
Finally I had not have to use the new implemented class `SettingsPanelDataStore` for this issue, but I would like to keep it in the project because I think it is something useful that we're going to use in the future. This data store class let us to change any setting control from any place of our code without the necessity to go and click fisically in the control inside the SettingsPanelHUD.
> feat: [BiW Editor] Editor shortcut needs to be added to the list

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs
When an user tap on enter in builder in world in a land where the user don't have permission, the scene reloads.
This fix that issue
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-genesis-dissapear
2. Try to enter in a land where you don't have permissions ( like genesis plaza) and the world should stay
> fix: fixed bug of reload scenes when you don't have permission

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Graphics/Images/LoadingImage01.png
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Graphics/Images/LoadingImage02.png
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/BuilderInWorldLoadingView.prefab
> style: BiW carrousel images updated

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Analytics/BIWAnalytics.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldInputWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BuilderInWorldGodMode.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/Views/SceneCardView.cs
Fixes #721 
- Scene editor button is working as jump in
- Square multi selection is not released if you do it on top of a UI
- Double click on a locked entity will focus on it
- if you duplicate and entity, and then you lock it, the original entities are locked as well
- Voxel and other objects are selected differently
- After playing around in the biw, I wasn't able to select the rotation or scale tool by UI, I needed to use the shorcut, after using the shorcut everything worked as expected
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/big-bug-fixing-4
3. Check if the bug are correctly fixed
> fix: biw bug fixing

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCardHUD.prefab
In order to fix the text issue after clicking on collectibles section:
- Size and characters spacing increased in all the text components of each section.
- The font style is uppercase now.
> fix: [Passport] collectibles section selected

- .github/workflows/unprioritize-issues.yml
Fix #754 
Add GitHub Action to set "unprioritized" label to new issues.
1. Go to https://github.com/kuruk-mm/unity-renderer/issues and open an issue (this fork it's exactly the same as this PR)
2. Wait some seconds, and it will be labelled as "unprioritized"
> chore: set "unprioritized" label to opened issues

- .circleci/config.yml
- .github/workflows/main.yml
- ci-playmode-test.sh
- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
Fix #700
- Add code coverage package to Unity
- Upload code coverage report to S3
- Now GitHub Bot to comment the link of the report
Maybe this would be an intermediate step to upload the code coverage to a service like http://coveralls.io/.
1. Go to the bot comment on this PR (https://github.com/decentraland/unity-renderer/pull/777#issuecomment-875648113)
2. See if it reported the code coverage and if you can see it well.
> chore: upload code coverage report

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWSaveController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BuilderInWorldGodMode.cs
This PR ensures that we are saving biw scenes each 5 seconds instead of each change, this will make the servers more stables
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-save-time
3. Check that the scene is not saved each time that you made a change
> feat: biw save each 5 seconds

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_BIW.cs
This PR fixes #795 , If you exit from builder in world with an entity outside the parcel, the explorer will end in a unexpected state and you won't be able to do anything
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-feedback
3. Put an entity outside the parcel
4. Exit from builder in world
> fix: biw exit correctly with an entity outside scene 

- browser-interface/scripts/build.ts
Including `../package.json` to check files generated a whole new structure of files that wasn't properly handled in https://github.com/decentraland/unity-renderer/pull/688
A test was added, the build should fail if it doesn't work
> fix: typing roots

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/AvatarEditorHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/Interfaces/ITheGraph.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/Interfaces/Nft.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/Interfaces/Nft/NftTypes.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/Interfaces/Nft/NftTypes.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/TheGraph.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/TheGraphQueries.cs
Fix #145 
When clicking sell CTA on any collectible item, it took the players to their assets URL on the marketplace when it should be taking them directly to the wearable URL instead.
Currently, the sell button takes you to `https://market.decentraland.org/account` and it needs to go to
`https://market.decentraland.org/contracts/[COLLECTION-SMART-CONTRACT]/tokens/[WEARABLE-TOKEN-ID]`
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/Sell-item-wrong-URL&ENV=org
2. Open the AvatarEditorHUD.
3. Go to Collectibles tab.
4. Click on the `i` icon of any wearable.
5. Click on the SELL button.
6. Notice that you will be redirected to the correct wearable page.
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-st …
> fix: Sell item wrong URL

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Fix #799 
Some scenes are breaking the character controller gravity when jumping, letting us to make infinite jumps. See this [video](https://decentralandteam.slack.com/files/UB4ENQ750/F027WJJ3NBX/screen_recording_2021-07-13_at_22.30.20.mov).
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/A-deployed-scene-bugs-the-character-controller-gravity&ENV=org&position=50,75
2. Try to jump multiples times.
3. Notice the avatar is only able to make a single jump and not inifinites as before.
> fix: Some scenes bug the character controller gravity

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/AvatarName.cs
Fixes #491. Now the Avatar name is renderer behind the scene UI
1. Go to: https://play.decentraland.org/?ENABLE_BUILDER_IN_WORLD&ENV=org&position=-118%2C136&realm=unicorn-blue&ws=ws%3A%2F%2Flocalhost%3A4999%2Fdcl
2. Try to put an avatar name on top of the scene UI
> fix: name renderer behind the canvas

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/BaseComponent.cs
Fixes #826 
It's easier to test this in Unity. Just lock the editor window to an avatar and either move the avatar away or move yourself away to see how the mouth, eyes and eyebros dissapear.
All of our AvatarShape tests are disabled (it takes too long to load an Avatar) and there's an ongoing effort to first refactor AvatarShape/AvatarRenderer and then implement a proper test suite. Therefore I decided to not waste time on making a test that is going to be disabled.
Instead of checking each time the player or the other avatars change position, I decided to have a routine running and performing the distance calculation.
I was worried of triggering a Distance calculation (expensive) each time (possibly multiple times).
> feat: disable facial features based on distance to player

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Fix #476 
Through comms we always report the CAMERA rotation but we should be reporting the CHARACTER rotation, otherwise when players are using the third person camera, they think the rest of the users see them in the direction they point their avatar but they actually see the rotation of the camera...
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/Fix-users-comms-reported-rotation (You have to open the app in 2 browsers with different users)
2. From one of the browsers, look to different places with your avatar in both modes 1st and 3rd person camera mode.
3. Notice from the other browser that your avatar is looking always to the correct place depending on his body forward and not on the camera. …
> fix: Fix users comms reported rotation

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatHUDView.cs
Fix #123 
Seems to be that when the chat history gets quite long, every new chat message received takes some milliseconds in processing, and that causes noticeable hiccups
- Each time a message entered the chat, we was forcing to update **ALL** the existing entries layouts with `Utils.ForceUpdateLayout(transform as RectTransform, delayed: false)`, that had having a huge impact on the performance when the chat had accumulated a lot of messages.
- After a message entered the chat, we was setting the vertical position of the HUD scroll to 0 with `scrollRect.verticalNormalizedPosition = 0`, and it was affecting negatively to the performance.
- **BEFORE**: Hiccups up to `~287.50ms` per each entry added in the chat.
- **NOW**: Hiccups up to `~3.45ms` per each entry added in the chat.
1. Go to: …
> fix: Noticeable hiccups when receiving a chat message and the chat history is long

- browser-interface/scripts/publish.ts
Parameters in the `triggerPipeline` function weren't in the correct order
> chore: fix `triggerPipeline` parameters order in publish.ts

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/HighlightScenes/HotSceneCellView.cs
Fix #244
It is a second part of the previous PR (https://github.com/decentraland/unity-renderer/pull/781). We found an issue when we tried to re-joinning to the next best realms that was making it always failed. This PR fix it!
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/JumpIns-from-Explore-dont-work-correctly&ENV=org
2. Open the Explore window.
3. Select different scenes to jump in.
> fix: Connect to the next best realm if the Explore JumpIn fails (II)

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
Fix #772 
There were lots of mesh count related to TextMeshPro on unity's profiler.
We should analyze if the TextShape component is destroyed correctly
1. Each time a `TextShape` object is created, we store a copy of the shared material in a private variable.
2. Instead of using `text.fontMaterial...`, we use `text.fontSharedMaterial...` in order to not to provoke new copies of the material.
3. Once the `TextShape` object is destroyed, we destroy our stored material.
**NOTE:** Making different tests with the `TextShape` components loading isolated, I have not seen a huge memory saving (the most important issue that I've detected with the number of materials in the profiler has been telated to this other [ISSUE](https://github.com/decentraland/unity-renderer/issues/876)). Anyway, in order …
> fix: TextMeshPro materials used by TextShape are not properly destroyed

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs
This PR is a defensive measure, if you have lots of lands the explorer will process a lot of information, this way we ensure to only process the information in case that you want to use builder-in-world
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/release-defensive-fix&ENV=org
2. Try to use the biw shorcut ("K") in a land where you are operator
3. You shouldn't have access until the query is done, try again after some seconds
4. It should enter now
OR
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/release-defensive-fix&ENV=org
2. Enter with a land that have a lots of lands
3. Check that everything work as expected …
> fix: only check for lands if the shortcut or panel is used

- unity-renderer/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
…o use it on unity-desktop
This code was deleted here: https://github.com/decentraland/unity-renderer/commit/9031228244c37aa6298f1affcfd85f60ab654620#diff-2a171cfb86bcc979ce96b8c8bb2809ebb910c4903bd65bb30a73a23859fe58a4
And it was implemented here: https://github.com/decentraland/unity-renderer/pull/611
This code is used by explorer-desktop to login as a guest and in the future with wallet connect
> fix: restore deleted code from `auth from explorer-desktop` feature to use it on explorer-desktop

- unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
Fixes #803
How to test:
- Run the game
- Set graphics preset to Ultra
- Shadow resolution should be 4096
> fix: shadow resolution on Ultra is now 4096

- unity-renderer/Assets/UnityGLTF/Scripts/Async/AsyncCoroutineHelper.cs
For some mysterious reason using Unity's coroutine runner was leaving some GLTF in a state where they never finish loading.
Replacing `StartCoroutine` for `StartThrowingCoroutine` solved that issue.
> fix: GLTF's AsyncCoroutineHelper coroutine runner

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromiseKeeper_AB.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromiseKeeper_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromiseKeeper_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/AssetPromiseKeeper_Gif.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Material/AssetPromiseKeeper_Material.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromiseKeeper_Texture.cs
Due to the implementation of the singleton pattern in `AssetPromiseKeeper` overridden methods for classes that extends it (like `AssetPromiseKeeper_GLTF` `OnSilentForget`) were not being called.
> fix: AssetPromiseKeeper singleton

- unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs
Fixes #896
Entering in builder in world by the shortcut is not working correctly. This PR changes that adding a message and trying to edit the land after the permissions of the lands has been checked if the shortcut has been pressed
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-shorcut-flow
2. Try to enter in your land with the shortcut "K" without opening the builder in world panel
3. Restart the session and try to enter in a land where you don't have permissions
> feat: correct biw flow with the shortcut

- unity-renderer/Assets/Resources/ScriptableObjects/MovingPlatformRotationDelta.asset
- unity-renderer/Assets/Resources/ScriptableObjects/MovingPlatformRotationDelta.asset.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateFPS.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Tests/CharacterControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/Variables/QuaternionVariable.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/Variables/QuaternionVariable.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/Variables/Tests/VariableTests.cs
Fixes #477 
How to test: 
- Go to Genesis Plaza flying tour carts or any moving platform that rotates
- On first person, the camera should rotate as the platform rotates
- On third person, the camera should stay still and the character should rotate as the platform rotates
> fix: Moving platforms now rotate character avatar and first person camera

- browser-interface/scripts/publish.ts
Adds an `await` to the remote pipeline trigger and cleans up things that are no-longer necessary
2. ...
> fix: await in pipelines

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Tests/PoolManagerTests.cs
Fixes #876 
When teleporting, the renderer is being turned off and every pool instantiates new objects instead of using the unused ones.
I'm not sure if this is the best fix for this issue
> Fix: pools instantiating additional objects when renderer was turned off

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Resources/CameraController.prefab
Fixes #958 
The third-person camera is a **Cinemachine Free Look Camera**, this type of camera has 3 rigs with their own set of lens properties ( fov/far clip/etc).
By setting the lens as common: all rigs will have the same properties.
...
1. Change draw distance while being on third-person camera, it should work now.
> fix: third person camera lens is now common

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
The email is now sent through `SendPassport()`.
> chore: remove unused sendUserEmail message

- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Catalyst.cs
Content server is desambiguated from realm domain, _must_ use the content server URL to resolve content.
2. ...
> fix: use desambiguated content server

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
TextShape is rendering a "Hello" when created, before the component model is updated.
fixed by setting an empty string as it value when component is created or sent to pool.
Can be tested at coords -119,136
> fix: TextShape showing "hello" when created

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs
Fix #902   
This PR fix the problem where scenes are not getting the details of the name and description
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-name-twice
3. Publish an scene with a name
4. Go to another land or unpublish the scene
5. Enter again in builder in world
6. The names should be different
> fix: name corrected assigned

- unity-renderer/Assets/ABConverter/Tests/ABConverterCoreShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/BuilderProjectsPanelController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils/ContentServerUtils.cs
Fixes #937 
Remove instances of old `peer.decentraland.org` link
> chore: replace old peer url

- .github/workflows/set-rollout.yml
10% has proven to generate too much signal-noise ratio. Increasing to 50% to reduce falloff to prevent older versions to be selected in rollouts.
2. ...
> fix: prod rollout percentage

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs.meta
This PR Fixes: #750 
We this change builder and builder in world uses the same criteria for the scene limits
1. Go to https://builder.decentraland.io/ and create a scene with smart items, then publish that scene
2. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-scene-limit
2. Enter in the scene that you has been from builder
3. Check that both builders have the same criteria with the scene limits
> fix: builder and builder in world use the same metrics

- unity-renderer/Assets/Scenes/InitialScene.unity
- unity-renderer/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
- unity-renderer/ProjectSettings/EditorSettings.asset
This PR changes two things:
This improves the editor performance by 1000%, at least in my case.
NOTE: Be aware that this setting can expose some null reference exceptions that are related to using the null-coalescing operator on unity objects.
The `fenrir-amber` option is set by default as its acknowledged as stable by the contributors.
You have to test the branch in editor mode to test them and try to go to play mode. 
Note that without the `Enter Play Mode Options` play mode may be delayed even by one full minute in some cases. 
With this option enabled, enter play mode only takes a few seconds and the client runs a lot smoother.
> chore: enable project settings that improve unity editor performance

- browser-interface/scripts/build.ts
Closes #1010
Change NPM format similar to `@dcl/explorer-website` and `@dcl/kernel` to:
`{major}-{minor}-{build}-{dateYYYYMMDDhhmmss).commit-{hash}`
Open the CircleCI pipeline, in the `publish-renderer` stage, and the `npm run publish` step.
Check if the NPM version is in the correct format.
> chore: add date and commit hash to npm package version

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Catalyst.cs
The preview now loads so fast that unity doesn't finish loading itself before we start sending information about scenes to it.
2. ...
> fix: race conditions

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRendererInterface/IAvatarRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
Fixes #1009 
Also should fix #1019 
* Write `/emote headexplode` in the chatbox 
* Enter the backpack before the animation ends
* When getting back from backpack, the avatar should look correctly
> fix: deformed avatar when backpack interrupts "head explode" emote

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/LoadingFeedbackController.cs
Fixes #1001 
This PR removes the loading feedback message sent to kernel if the loading view is not visible
1. Go to unity editor and download the branch
2. Debug the messages send to kernel and check that the messages are not sent anymore
> fix: remove loading feedback message when the loading view is not visisible

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Analytics/BIWAnalytics.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWPublishController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWCommonShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Utils/BIWUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/BuilderProjectsPanelController.cs
Fix #919
This PR fix some biw analytics that werent' send correctly and improve the scene limits event
Analytics fixed: 
-"Player Open Builder in world Panel" now the event is sent correctly
-Scene size value of all events is now correct
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-analytics
2. Open de builder in world panel
3. Check in the network tab that the scene is send correctly
4. Enter builder in world
5. Check that the scene size is sent correctly
6. Overpass the scene limits
7. Check that the the event now includes the scene limit and an array with the limit overpass
> fix: biw analytics improvements

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/FreeCameraController/FreeCameraMovement.cs
This PR fixes a rare situation where the camera to do the screenshots in builder in world is null
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/biw-publish-photo
3. Try to publish, you should see a photo of the scene
> fix: biw publish photo is getting the correct camera

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/QuestsController/QuestsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/QuestsController/Tests/QuestsControllerShould.cs
Fixes #1052 
Fixed an edge case in the `QuestController` due to a badly constructed logic operation.
It's easier to test this issue in UnityEditor, previously you would find an error in the console in the Genesis Plaza (with quests enabled), you should no longer see it.
> fix: solve a null reference edge case in quest controller

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/SceneSFXVolumeControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Settings.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Fixes issue #1005, where scene SFX (aka world SFX) would not adhere to the "Master" or "World SFX" sliders.
I also included a fix for scene SFX not playing while testing in the editor, since this was needed for testing.
Additionally, I changed the "Scene SFX" slider title into "World SFX", as requested by Alvaro.
1. Go to the playtest link: https://play.decentraland.zone/?renderer-branch=fix/world-sfx-volume-sliders
2. In the Genesis Plaza, listen to the waterfall and the birds.
3. Open settings and notice that the "World SFX" and the "Master" sliders are affecting the aforementioned sounds.
> fix: world sfx volume sliders

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/FacialFeatureController.cs
Many null references were detected on crowded places related to facial features controller trying to set colors before the body shape controller was ready. This PR fixes this issue.
1. Go to WonderMine in editor mode
2. Note that in `master` we get a bunch of null references coming from `FacialFeatureController.PrepareWearable`.
3. This shouldn't happen anymore on this branch.
> fix: race condition null reference issue in BodyShapeController

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarVisibility.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarVisibilityTests.cs
Fixes #1089 
The AvatarModiferArea should hide every avatar that enters the area, and display every avatar that gets out of it.
Lastraum reported that currently this feature is bugged and only works for the own player and not the other avatars.
Let's create some tests to cover the correct functionality of the feature.
1. Create a new scene with `dcl init` and paste this code:
```
const modArea = new Entity()
modArea.addComponent(
new AvatarModifierArea({
area: { box: new Vector3(16, 4, 16) },
modifiers: [AvatarModifiers.HIDE_AVATARS],
})
)
modArea.addComponent(
new Transform({
position: new Vector3(8, 0, 8),
})
)
engine.addEntity(modArea)
```
2. Play the scene in preview mode (`dcl start`) and debug it from Unity (using this branch).
3. Open other browser in incognito mode with the same …
> fix: AvatarModiferArea is only hiding own avatar (should hide all)

- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/DepthNormalsOnlyPass.hlsl
- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/GPUSkinning.hlsl
- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/PBRForwardPass.hlsl
- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
- unity-renderer/Assets/Rendering/Shaders/Toon/ShaderGraph/Master_ToonShader.shadergraph
Now, the avatar rendering should be identical as before the GPU skinning was applied. Address #1125.
* Matrix calculations for GPU skinning were rewritten to be compatible with normal transformations. Also the formula looks nicer now.
* Normal transformations don't depend anymore on the object transform (before, rotating the mesh renderer rotated the normals when they shouldn't).
* Changed fragment normal from tangent space to object space.
* Nullified world normal recalculations caused by Variants.hlsl on vertex shader because they conflicted with our calculated normals, as the output of the normals of the skinning operation are already in world space.
...
2. ... …
> fix: gpu skinning normal issues

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateFPS.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Disabled camera rotation when platforms rotate on First Person camera.
Player rotation report is now based on camera rotation only.
Fixes #1122 
Go to Dragon Rush, get on the dragon and smash F, neither FPS or TPS cameras should go helicopter mode.
> fix: special rotating platforms going full helicopter

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarNamesHUD/AvatarNamesTracker.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarNamesHUD/Tests/AvatarNamesHUDViewShould.cs
Fixes #1136 
The AvatarLODs controller introduced an optimization that allows us to remove one of the checks for the AvatarNames. Sadly it made the feature to stop working properly with LODs disabled. Be sure to test this with `DISABLE_AVATAR_LODS` or in `.org`.
> fix: avatar names outside frustrum are now hidden

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/Asset_AB.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
Fixes #1114.
This also fixes the following:
- Asset_AB nullReference issue that could potentially cause issues with models
- Fixes animator issue caused by item toggles that shouldn't happen because the avatar editor is closed
Go to WonderMine using Unity editor and ensure the avatar animators don't have the component multiple times.
> fix: avatar audio event not removed issue

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
Signed-off-by: Alejandro Jimenez <ajimenez@decentraland.org>
Culling controller were messing with our avatars optimizations, transitions and impostors. We ignore them from now on.
To test this PR just go to a crowded scene (or put some bots in) and check if small avatars in the distance get culled off if the setting is enabled. It shouldnt.
> chore: set AvatarShape layer to ViewportCullingIgnored

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShapeTests.cs
Added a test to ensure that the culling controller is ignoring the avatars
You cant =D
> chore: test to ensure culling controller ignores AvatarShape

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShapeTests.cs
This should fix the issue with the Passport and probably avatar trigger area issues.
> fix: set AvatarCollider and PointerEventCollider layers properly

- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/How to generate this shader.md
- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
Fix #1154 
The Toon Shader had `absolute paths` to include other files, and when I imported it from `explorer-desktop` it fails. So I changed for `relative paths` to work correctly in `unity-renderer` and `explorer-desktop` and I added the step to do it on `How to generate this shader.md`
1. Open `explorer-desktop` and check if the issue stopped happening
2. Then, go to https://play.decentraland.zone/?renderer-branch=fix/toon-shader-path-for-desktop and test if your character looks OK
> fix: relative paths for toon shader to work in `explorer-desktop`

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Camera.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraDampOnGroundType.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateTPS.cs
Fix #999 
...
1 - `/goto 10,10` camera should point forward
2 - `/goto 0,0` camera should point forward and should not move through the floor
> fix: camera rotation on teleport or forced set

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/InputSpikeFixer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/InputSpikeFixer.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/OverrideCinemachineAxisInput.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/SmoothAxisProvider.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/InputSpikeFixerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/InputSpikeFixerShould.cs.meta
Fix #1104 
...
Do random stuff on the world and change the focus state often ( pressing ESC and clicking on the screen over different points in the viewport).
Either when locking on or off, the camera shouldn't move abruptly.
> fix: input spikes when changing lock states

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
Fixes #1177 
Reduce the resolution of the body snapshot taken.
The only way to test it would be to save your avatar in the backpack and then retrieve your profile from https://peer.decentraland.org/lambdas/profile/{wallet}
> chore: reduce body snapshot resolution

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/LazyTextureObserver/LazyTextureObserver.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/LazyTextureObserver/Tests/LazyTextureObserverShould.cs
Fixes #1199 
The `LazyTextureObserver` was not calling back methods that tried to add themselves to the observer but were already added.
Fixed it and added a test.
You can see that the spinner is no longer stuck in your profile snapshot.
> fix: profile spinner is stuck

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
The following scenario was leaving some GLTF orphan:
* keep `promiseA` for gltf asset `X`
* forget `promiseA`
* keep `promiseB` for gltf asset `X`
* 
if `promiseB` finish loading gltf `X` before `promiseA` (since we are waiting for gltf to finish loading) we will end up having an orphan gltf `X`
can be tested in [WonderMine `-26,59`](https://play.decentraland.zone/?renderer-branch=fix/orphan-gltfs&position=-26,59) when not using asset bundles
> fix: race condition leaving orphan gltf

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromiseKeeper_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/BlockedAndMasterPromisesShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/GLTF_PromiseShould.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
related to PR https://github.com/decentraland/unity-renderer/pull/1194 (refactored changes done there)
related to issue #1196 
In some situations GLTFs were added more than once to the library sometimes leaving orphan GLTF and wasting memory unnecessarily 
also: closes #1205 by adding test coverage
> fix: gltf added to library more than once

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
Fixes #1219 
NFTShapeLoader was not disposing asset promises properly.
It might translate to fewer memory crashes in place with lot of NFTShapes (as in -73,-33). You can test against that parcel and compare to master.
NFTShapes should behave as before.
> fix: now asset promises are disposed properly in the NFTShapeLoader

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Animator/Tests/AnimatorTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/Tests/AvatarMeshCombinerHelperShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/GLTFImporterTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/APKWithPoolableAssetShouldWorkWhen_Base.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/AssetLibrary_Poolable_Should.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWNftsShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MemoryManager/Interfaces/IMemoryManager.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MemoryManager/MemoryManager.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/PoolManager.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Tests/PoolManagerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Tests/PoolManagerShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Environment.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScenesCleaner.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScenesCleaner/Interfaces/IParcelScenesCleaner.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
- unity-renderer/Assets/Scripts/Tests/IntegrationTestSuite/IntegrationTestSuite.cs
- unity-renderer/Assets/Scripts/Tests/IntegrationTestSuite_Legacy.cs
- unity-renderer/Assets/Scripts/Tests/TestHelpers.asmdef
This PR add small tweaks to how we free memory when teleporting.
* When clearing entities in "immediate mode" now the pool is cleaned up.
* When the rendering is deactivated to start a teleport, `ParcelScenesCleaner` pending entities are cleaned up and `Resources.UnloadUnusedAssets` is called. (before this happened when the rendering was **activated**, leading to potential unwanted memory spikes)
* Added a few refactors to improve `MemoryManager` and `ParcelScenesCleaner` encapsulation. `MemoryManager` now just exposes a `OnCriticalMemory` event. `MemoryManager` responsibility was simplified, and now it doesn't uses `ParcelScenesCleaner` anymore. The `MemoryManager` responsibility of cleaning pools is still in place, but the pool cleaning code was moved to `PoolManager`.
These changes …
> fix: teleport memory handling

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
Detected nullref that interrupts teleportation by following these steps:
1. Enter https://play.decentraland.org/?position=8,18
2. Teleport elsewhere (use the worldmap or /goto 0,0) and you'll see the teleport never finishes. In the browser console you can see a nullref error.
--------
* Added missing nullcheck
* The problem is fixed on this PR build: https://play.decentraland.zone/?renderer-branch=fix/SceneBoundariesCheckerNullRef&position=8,18
> fix: scene boundaries checker nullref

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombinerHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
* Combined avatar meshes were leaking because the renderer used to retrieve the mesh references for unload was being destroyed before the unload was called.
* Fix unhandled error when the face wearables can't be fetched from wearables endpoint.
* Instance many avatars by using `clientDebug.InstantiateBotsAtCoords({ amount: 200 })`
* Clear the bots by using `clientDebug.ClearBots()`.
Notice that when doing this in `master` a lot of dangling meshes can be seen on Unity's profiler, incurring a leak of around 2.4 mb per avatar.
On the version of this PR, the meshes should be destroyed and the memory freed.
> fix: combined avatar mesh leak

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/UIContainerRect.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/UIContainerStack.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIShape.cs
- unity-renderer/Assets/Scripts/Tests/CursorControllerTests/CursorControllerTests.cs
related to https://github.com/decentraland/sdk/issues/75
It's not uncommon for scenes developers to leave UIContainers on screen since by default it alpha is 0 so they don't see it.
This generate issues like hover feedback not being display or not being able to lock the mouse.
So I've added an alpha tolerance to decide if a UIContainer should be a target for raycast or not.
issue can be reproduced here: https://play.decentraland.zone/?position=-29,55 trying to lock the mouse on the bottom-right corner of the screen is impossible cause an invisible UIContainer is blocking it
test issue is fixed here: https://play.decentraland.zone/?renderer-branch=fix/invisible-ui-container-blocking-raycast&position=-29,55
> fix: invisible UI container blocking raycast

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Gizmos/DCLGizmos.cs
not a relevant fix. 
does not happen in prod but it was crashing the client while running test-scene -102,102
> fix: model null ref in Gizmos component

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/MaxHQAvatarsControlConfiguration.asset
Sets the min value for Max HQ Avatars setting to 25.
To test it go into an incognito mode an check the default value of that setting.
> chore: set min value for Max HQ Avatars to 25

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/StickersController/StickerAnimationListener.cs
`Animation.Blend` was causing all the animation events to trigger at once when playing an Emote twice in a row. We fix it by setting the weight of the animation properly and using it to discard events in the transitions.
It's hard to implement a test for this because it's mostly due to how unity handles the animation. It would require the test to play an animation twice and count the events received.
Just make sure that the emotes are triggering as usual and nothing is broken.
> fix: animation blending was firing all events at once

- unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
Basic, Medium presets had the value for MaxHQAvatar below the minimum for the setting.
Just check that you can set quality presets to Basic or Medium.
> chore: adjust presets for MaxHQAvatar

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
Fixes #1198 
The friend button wasn't working the first time that you opened a profile and if you used the friend panel, the pending request will appear on others profiles
Now the button is working as expected and pending request too 
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/friend-button
2. Ask a user to be a friend by the friends panel
3. Look at other dude profile to check if there is a pending friend request ( it shouldn't be here) 
> fix: friend button enabled or disable since the first time

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/CombineLayerUtils.cs
This PR forces all the opaque wearables that use double-sided materials to use back-face instead. This greatly enhances the performance of avatar rendering given by the avatar mesh merging system. 
The performance improvement works because using back-face on all opaques will reduce the need to create new materials for render state change. So, avatars with far less submeshes will be produced, in most cases only taking a single submesh (and this means a single draw call/no gl pipeline flush).
Wearables that use double-sided opaques should be tested. A clear example are the wearables of the `urn:decentraland:ethereum:collections-v1:tech_tribal_marc0matic` collection.
Those wearables are currently in process of being fixed. When the wearables are fixed, then this PR could be merged. …
> feat: enable avatar merge cull optimization heuristic

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDView.cs
Fixes [#1117](https://github.com/decentraland/unity-renderer/issues/1117)
Caret position of chat input field is moved to the end of the line when replying a whisper
1. Whisper a friend user typing _/w [friend] anything_ in chat
2. The friend user should reply typing _/r_ in chat
3. The chat should automatically write the name of the user you are replying positioning the caret at the end of the line
> Caret position is moved to the end of the line when replying a whisper

- unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
Solves issue [#1242](https://github.com/decentraland/unity-renderer/issues/1242)
Updated preset values for different graphic quality levels
1. Go to settings menu
2. Graphics tab
3. Alter between different quality levels
4. Check `Assets/Resources/ScriptableObjects/QualitySettingsData.asset` has corresponding values specified at [#1242](https://github.com/decentraland/unity-renderer/issues/1242)
> Improved graphic settings preset values

- unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
If the same texture is used as both BaseColor and Normal mapping now won't be marked as normal map.
> fix: asset bundle converter gives priority to albedo

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/ReportBugButton.cs
Fix #1433 
Press report a bug, the issue must have `explorer`/`explorer-desktop` and `new` labels
> chore: add labels to differentiate webgl vs desktop

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldEditor.cs
This PR fixes biw, right now it is not working because the builder API has changed the way we sign the headers
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/biw-api
2. Check that builder in world work as intendeed
> fix: biw new way to sign the calls

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab
`Closes #178 `
Fixes an incorrect offset of the player's icon in the minimap.
After several tests and approaches i went through the simplest solution i found.
1. Go to: https://play.decentraland.org/?renderer-branch=fix/minimap-player-offset
2. Type `/goto 3,-17` (the roads acts as a reference where the player should be)
3. The player icon in the minimap should be perfectly positioned according to the map space
4. Press `M`. All the map icons should be correctly positioned
5. Go to any populated zone. Peer player icons should be correctly positioned in the minimap
> fix: player minimap icon incorrect offset

- unity-renderer/Assets/Rendering/Shaders/Toon/Compiled/GPUSkinning.hlsl
Fixes GPU skinning on Metal-based graphic API platforms
Shadows are still broken
Fix #1144 
Run on `Editor` or [Desktop](https://github.com/decentraland/explorer-desktop/pull/29) build while on `MacOS` the "Flashmob" error should be gone
> fix: gpu skinning on Metal graphics API

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/Tests/UIInputTextTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/UIInputText.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
* fix input field being clear and string value set to empty after submit: after submit an `onChanged` was triggered with and empty value
* fix input field adding an unknown character at the end of the string when ESC key was pressed (happening in OSX)
+ added a single event for text changes. kept old events to maintain compatibility with old scenes
> fix: UIInputText component events

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUDView.cs
Fix #1414 
Set transparent background in NFT prompts.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/Set-transparent-background-in-NFT-prompt
2. Go to any place where there are NFT frames.
3. Click on one of these frames to open the NFT prompt.
4. Notice the image's background is transparent.
> fix: Set transparent background in NFT prompts

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetPromiseKeeper.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/FeatureFlags/Data/FeatureFlag.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
- unity-renderer/Assets/UnityGLTF/Scripts/UnityGLTFAssembly.asmdef
Fixes #1340 
Skewed scaling is breaking the GPUOnly meshes collision. We make the optimization dependan on a disabled feature flag until we decide how to handle this scenario.
You can use `ENABLE_USE-GPU-ONLY-MESHES` flag to enable the GPUOnlyMeshes and find the collision failing
> fix: set GPUOnly meshes dependant on a feature flag

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/Resources/Profanity/badwords.json
Adds `hitler` to profanity words filtering
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/filter-hitler
2. Go to settings menu and check profanity filtering is enabled
3. Write hitlerrrr123 on general chat it should be filtered
4. Change your user name to hitler and write something on general chat. Your name should be filtered
> fix: added hitler into profanity words

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIShape.cs
#1437 
Now UIShapes are only refreshed when the user is on the scene. 
Pros:
A nearby scene with a heavy usage of the SDK UI and layouts (which kills performance) won't affect the performance of your scene.
Cons:
We no longer have prewarm of UIs as long as you walk around the world. When you enter the scene, your UI will be readjusted and it might take a frame for things to look correctly.
> fix: UIShape only refreshes itself if the user is on the scene

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab
`Closes #1511 `
- Modified the position calculation of map's parcel highlight object.
- Modified the anchor of the highlight object to match the visual position
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/map-parcel-offset
2. Press `M` to open the navmap
3. Move the mouse through the map, you should se its aligned with the visual parcels
> fix: navmap parcel offset

- unity-renderer/Assets/ABConverter/VisualTests.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
- unity-renderer/Assets/UnityGLTF/Scripts/Loader/GLTFFileLoader.cs
* Added missing check for invalid meshes triangles that trigger a fatal error on mesh construction
* Updated some fatal errors to regular logs
> fix: asset bundles converter fatal errors

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab
Fixes an the offset of the highlighted parcel when scrolling the map.
The highlighted object `ParcelHighlight` was childed into `Map Renderer/Container/Overlay Layer` root in prefab hierarchy.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/map-parcel-offset
2. Press `M` to open the navmap
3. Move the mouse around the map. The highlighted parcel should fit respectly to the map reference
4. Scroll the map. Move the mouse around the map. The highlighted parcel should fit respectly to the map reference
> fix: map parcel highlight due map scrolling

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombiner.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombinerUtils.cs
This PR attempts to fix the hiccups caused by `ComputeBoneWeights` function when an avatar is loaded.
Before:
After:
Note that:
* Most of the overhead the `List<T>` capacity setting went away due to use of arrays
* Very high GC overhead almost was almost wiped
* In the shown case, the ms cost went from 4.51ms to 0.10ms with the improvement enabled
> fix: ensure capacity hiccup

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/IPlayerPrefsSettingsByKey.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/IPlayerPrefsSettingsByKey.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/ISettingsRepository.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/ISettingsRepository.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsAudioSettingsRepository.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsAudioSettingsRepository.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsGeneralSettingsRepository.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsGeneralSettingsRepository.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsQualitySettingsRepository.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsQualitySettingsRepository.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsSettingsByKey.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsSettingsByKey.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/ProxySettingsRepository.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/ProxySettingsRepository.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Settings.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsData/AudioSettings.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsData/GeneralSettings.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsData/QualitySettings.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsModule.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Tests.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Tests/ProxySettingsRepositoryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Tests/ProxySettingsRepositoryShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Tests/SettingsTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Tests/SettingsTests.asmdef.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/PlayerPrefsUtils.cs
`Closes #1482 `
Fixes the preset dropdown that was always showing `Custom` at quality settings menu.
Settings data structures were changed from classes to structs so that `equals` compares values instead of references.
A new persistence architecture was implemented to solve the problem of being unable to default a new/non-existent attribute of a user that already had any settings saved. It saves each setting's attribute into a new player prefs key. This architecture also holds retrocompatibility issues by migrating the previous settings saved to the new persistence schema.
1. Go to: https://play.decentraland.org
2. Change your settings (general, quality & audio) to anything you'd like, preferably something different than default settings
3. Close the settings menu
4. Go to: …
> refactor: settings persistence

- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
this check was introduced when debugging the AB converter, as this check affects performance in runtime, we are removing it.
https://play.decentraland.zone/?renderer-branch=chore/RemoveInvalidVerticesCheckInGLTFSceneImporter&DISABLE_ASSET_BUNDLES
> chore: remove invalid triangles check in gltfsceneimporter

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/Resources/Profanity/badwords.json
Word "tit" removed from profanity filtering due there are problems with words like "competitive"
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/tit-filter
2. Write tit in chat, it shouldnt be filtered
> fix: removed tit from badwords

- README.md
- browser-interface/scripts/publish-artifacts.sh
- browser-interface/scripts/publish.ts
- docs/resources/circleci-unity-activation-file-v2020.3.0f1.alf
- docs/setup-circleci.md
Fix #1591 
chore: update CI to work without CLOUDFRONT_DISTRIBUTION and without the publish tokens
Note: This is a PR from a forked unity-renderer!
Add documentation to `unity-renderer` repo to know how to set up CircleCI
**Next steps:**
We need to configure the `GitHub Bot comment` to comment with the URL using the external S3 Bucket.
> docs: add how to setup circleci

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/GLTF_PromiseShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
`AssetPromise` for GLTF and AB_GameObjects were not updating `asset.renderers` on certain cases when using the promise with a parent set.
This would end up in incongruences between `asset.container.GetComponentsInChildren<Renderer>()` and `asset.renderers`.
> fix: rendereable incongruence

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
fix: "camera mode" is only reported when mode changes, so scenes can't get the current "camera mode" unless user press `V` button
> fix: camera mode change event

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/PortableExperienceItem.prefab
context menu for quitting portable experience was not appearing after pressing the portable experience's button in the taskbar.
> fix: portable experiences taskbar button

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
*fix: process enqueued messages on `OnMessageFromEngine` subscription.
Enqueued messages to kernel were only processed when trying to send a new message, sometimes leaving the initial messages in the queue without sending them and leaving kernel stalled, waiting for renderer's message that is ready.
test: connect using ws to this kernel version: `1.0.0-1537672436.commit-92098d5`
https://play.decentraland.org/?kernel-version=1.0.0-1537672436.commit-92098d5&ws=ws://localhost:5000/dcl
> fix: process queued messages on ws open

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Using `Application.OpenURL` instead of sending the message to the Kernel
> fix: open url from Unity instead of kernel for desktop

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Resources/BuilderProjectsPanel.prefab
Go to the Builder section in the manu and check the X alignment of the dropdown menu opened in comparison with its button.
Before
Now
Test link: https://play.decentraland.zone/?renderer-branch=fix/BuilderDropdownMenu
> Fix: builder dropdown menu position

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEventColliders.cs
There is a renderer turning into null at some point in the meshesinfo given certain circumstances and that interrupts the scene logic for example when entering (walking from outside) the etheremon wolves scene at [-138, -123](https://play.decentraland.org?position=-138%2C-122). The error can be seen in the browser console.
When the OnPointerEvent colliders are initialized on those entities, 1 renderer in the meshesinfo collection is null for some reason. I found out that we already had placed nullchecks for this case in other places in the OnPointerEvent pipeline, so I added the missing nullcheck now and created [this other issue](https://github.com/decentraland/unity-renderer/issues/1654) to some day get in the rabbit hole and find out why some renderers turn to null at some point.
> fix: onpointerevent colliders renderer missing null check

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
Fix #1656
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/backpack-nft
2. Test that the NFTs are loaded again after a minute
> fix: add a timer to call the owned wearables each minute

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Resources/BuilderProjectsPanelMenuSections/SectionDeployedScenesView.prefab
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Resources/BuilderProjectsPanelMenuSections/SectionLandsView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Common/Button_ShowMore.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/PlacesAndEventsSubsectionSelector.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Long.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventsSubSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/HighlightsSubSection/HighlightsSubSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlacesSubSection.prefab
**What does this PR change?**
- Builder No results and empty messages are now centered in the screen.
- Paddings and margins in the explore highlights section.
- Font size on the large event's card.
- Day and players information is now horizontally responsive on the event's cards.
How to test the changes?
1. Go to:  https://play.decentraland.zone/?renderer-branch=fix/BuilderSectionLayouts
2. Open the main menu and go to the explore and builder sections.
> fix: builder and explore layouts

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ProfanityFiltering/Resources/Profanity/badwords.json
Removed s.o.b & sh!+ from badwords due unexpected filtering for words like _snowball_
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/snowball-word-filter
2. Write `/emote` on chat
3. None of the emote words should be filtered
> fix: removed s.o.b & sh!+ as badwords due unexpected filtering

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUD.prefab
The map rendering was overlapping the cardinal points references. Now they are visible again.
Before
After
Test link: https://play.decentraland.zone/?renderer-branch=fix/CardinalPointsVisibility
> fix: cardinal points visibility in the minimap

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmotesHUD/EmotesHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/MouseCatcher/MouseCatcher.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Disables cursor locking that was occuring on `EmotesHUDController` which caused the locking during the first loading or the first time you create an avatar as a guest.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/incorrect-mouse-locking
2. Enter as a guest from a clean session
3. While the app is loading, click anywhere on the screen. The cursor should not be locked
4. Enter into the avatar creation flow. Click anywhere on the screen. The cursor should not be locked
5. Enter the metaverse. Press `B` to open Emotes HUD. Everything should work as expected
> fix: incorrect cursor locking during loading and avatar creation

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCardHUD.prefab
`Fixes #1651 `
"Active since {Date}" has been disabled from player information cards.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/active-since-removal
2. Click on any user's avatar around you
3. The card should not display "Active since" label
> fix: disabled active since date label on player profile cards

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/PortableExperienceItem.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
- unity-renderer/Assets/Textures/UI/ChatIcon.png.meta
- unity-renderer/Assets/Textures/UI/FriendsIcon.png.meta
- unity-renderer/Assets/Textures/UI/MicrophoneIcon.png.meta
Task bar right margin decreased.
How to test? **
Test link: https://play.decentraland.zone/?renderer-branch=fix/PortableExperiencesUIPosition
1- Write the following in the browser console:
**spawnPortableExperienceScene("urn:decentraland:off-chain:static-portable-experiences:radio", "main")**
2- Check that the right margin is now correct.
> fix: portable experiences container X position

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Animator/DCLAnimator.cs
address isssue: https://github.com/decentraland/sdk/issues/142
`animation.play(false)` resetting animation from start when it shouldn't
> fix: animation play with reset flag as false

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/AvatarOnPointerDown.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Utils/WorldStateUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/MainScripts.asmdef
issue: https://github.com/decentraland/sdk/issues/98
report to player's current scene click input on other players' avatar
*decoupled passport from onclick collider (collider was being disabled to avoid open passport interaction)
*removed old onclick uuid report since avatar onclick component is not actually an uuid component so it was not working
+report onclick when avatar is clicked in the same scene as the player is
> feat: add sdk event for avatar clicked

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/FirstPersonCameraReference/FirstPersonCameraEntityReference.cs
`Camera.main` was `null` on `Awake`
setting the `GameObject` as child of `firstPersonParent` was leaving it orphan.
`cameraPosition` is set, in the prefab, with the transform for the first person camera.
fixed using `cameraPosition` transform instead of `Camera.main.transform`
> fix: entity attach to first person camera

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Shortcuts/ShortcutsController.cs
`Fixes #1688 `
Prevents the user to open start menu by pressing TAB key during the avatar creation on signup flow.
1. Open an incognito tab
2. Go to: https://play.decentraland.zone/?renderer-branch=fix/avoid-start-menu-during-onboarding
3. Enter as a guest
4. On first avatar edition press TAB, it should not open the start menu
5. Confirm your avatar and follow the tutorial
6. When time comes to open the start menu press TAB, it should open as expected
7. Finish the tutorial, press TAB and the start menu should open as expected
> fix: avoid start menu during on-boarding flow

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/DebugController/Resources/DebugView.prefab
- unity-renderer/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSDisplay.cs
- unity-renderer/Assets/Scripts/MainScripts/Debugging/Panels/StatsPanelToggler.cs
- unity-renderer/Assets/Scripts/MainScripts/Debugging/Panels/UserBenchmarkToggler.cs
Add the title "**[Y] Debug Panel [P] Settings [I] Backpack**" on Preview Mode in order to inform the users how they can open/close the backpack.
**IMPORTANT:** This is a TEMPORAL solution while we adapt the new StartMenu to the PreviewMode flow. The idea will be that the StartMenu can be usable in PreviewMode in the same way as in the normal "world" flow.
1. Create a new empty scene
2. Play it as preview mode
3. Add in the url the url para: `&renderer-branch=fix/Backpack-not-available-on-preview-temporal-solution`
4. Notice the new informative panel is being showed by the user avatar profile.
> fix: [Preview Mode] Add informative title about how to open/close the backpack and settings (TEMPORAL SOLUTION)

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/DebugController/Resources/DebugView.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesAndEventsFeature.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesAndEventsFeature.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Shortcuts/ShortcutsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_ExploreV2.cs
- unity-renderer/Assets/Scripts/MainScripts/Debugging/Panels/UserBenchmarkToggler.cs
Fix #1722 
The StartMenu is now usable in PreviewMode in the same way as in the normal "world" flow. In this mode there will be some sections deactivated (for example "Explore" or "Builder"), only those that have sense to use in preview mode will be activated in the menu.
1. Create a new empty scene
2. Play it as preview mode
3. Add in the url the url para: `&renderer-branch=feat/Integrate-StartMenu-into-PreviewMode`
4. Notice the StartMenu is now usable in Preview Mode.
> feat: Integrate StartMenu into PreviewMode

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Common/ExploreEventsHelpers.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Common/ExplorePlacesHelpers.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/HighlightsSubSection/HighlightsSubSectionMenu/HighlightsSubSectionComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/HighlightsSubSection/HighlightsSubSectionMenu/HighlightsSubSectionComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlacesSubSectionMenu/PlacesSubSectionComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlacesSubSectionMenu/PlacesSubSectionComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/EventsSubSectionComponentViewTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreEventsCommonTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExplorePlacesCommonTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/HighlightsSubSectionComponentViewTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/PlacesSubSectionComponentViewTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/PoolManagerFactory.cs
Fix #1728 
We realized something that was wrongly implemented related to the Pool creation: When we used the `ForcePrewarm()` function (from our `Pool` class) after creating a pool, the number of instantiated objects was half of what was indicated in the `maxPrewarmCount` param.
So our Pools system was not working correctly, in fact in all places where we were using a prewarming, it was always creating the half of objects.
```
public void ForcePrewarm()
{
if (maxPrewarmCount <= objectsCount)
return;
for (int i = 0; i < Mathf.Max(0, maxPrewarmCount - objectsCount); i++)
{
Instantiate();
}
}
```
```
public void ForcePrewarm()
{
if (maxPrewarmCount <= objectsCount)
return;
int objectsToInstantiate = Mathf.Max(0, maxPrewarmCount - objectsCount);
for (int i = 0; i < objectsToInstantiate); i++) …
```
> fix: Fix pools prewarming + Explore section loading improvement

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/FirstPersonCameraReference/FirstPersonCameraEntityReference.cs
reverted fix done here: https://github.com/decentraland/unity-renderer/pull/1716
added method `GetCamera` to `CameraController` and use it `Transform` as reference for parenting to first person camera
reason: since `GameObject` of `cameraPosition` was being disable, on camera mode changes, it was triggering GLTF animations when reparenting
> fix: attach to first person camera

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
`AttachToAvatar` and `Transform` components can't coexist in the same Entity.
We must make sure that `AttachToAvatar` is removed from the Entity when a `Transform` is added to it.
closes https://github.com/decentraland/sdk/issues/159
> fix: remove AttachToAvatar when Transform is added

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Tests/SceneMetricsControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
Some NFT tests needs the API of OpenSea to work in order to pass, but this API is down and all these tests fail. We will temporarily set these specifi tests as `Explicit` while we implement the correct solution in our project (it is needed to mock the calls to the API in order to remove the dependency with OpenSea).
> chore: Set some NFT tests as Explicit temporally

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
Second part of https://github.com/decentraland/unity-renderer/pull/1786 (2 tests were set as `Explicit` but it was not necessary).
> chore: Set some NFT tests as Explicit temporally (II)

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/AvatarOnPointerDown.cs
WHY
OnPointerEvent hover feedback is flickering on every avatar ApplyChanges() call (avatars loading, avatars changing wearables, emotes, etc.). It affects any onpointer event feedback, not only avatar on pointer down feedback
A video with the issue can be seen: https://github.com/decentraland/unity-renderer/issues/1745
WHAT
Removed unneeded interaction hover feedback update in `AvatarOnPointerDown.SetPassportEnabled()`, since that update is already done in its `SetHoverFeedback()`.
> fix: flickering pointerevent hover feedback

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
This reverts commit d269cb61efc917bc6f1a2c9c38fa99a986daba1f.
Revert https://github.com/decentraland/unity-renderer/pull/1783
> Revert "fix: main player comms reported rotation (#1783)"

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
Fix #1738
Removes the exit button in first character creation.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/remove-close-button-first-creation
2. Start a new session as a guest user
3. Verify that the exit button doesn't appear anymore
4. Verify that the bahavior of the exit button in the explorer once the character has been created works as before
> fix: removed exit button in first character creation

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
Fix #1782
Hides avatar names in HIDE_AVATARS modified areas
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/hide-nametags-in-modifier&position=-134%2C74
2. Go to the tennis court inside
3. Verify that other players are entirely hidden and even their name disappears
> fix: added avatar name in hide gameobject list

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapToastViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
Closes #1750
removes the mouse hold on parcels event in the map
Forces the parcel toast to appear only on the parcel click
Adds the auto closure of the toast when the cursor is at least 40 parcels away
Restores an old explicit test
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/remove-mouse-over-on-map
2. Open the map
3. Test the toast opening and closing with the new behavior
> fix: removed mouse event over in map parcels

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
Fix #1829
With this PR the avatar preview doesn't fail loading anymore in the backpack
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/backpack-loading-failure
2. Open the backpack
3. Verify that everything loads properly
> fix: workaround for backpack avatar preview loading failure

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/PortableExperienceTaskbarItem.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/PortableExperienceItem.prefab
context menu, for portable experiences, won't open on clicked while icon is still loading
> fix: click on PEX icon while loading

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/Tests/UIContainerStackTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIShape.cs
`Fixes #1714 `
Looked like all the shapes were refreshing after another when screen size changed messing up the size. Now `UIShape` refreshes when its the root shape only.
1. Go to wondermine (-29,55), resize the browser tab, the UI (bottom right) should stay where it was
2. Go to casinos and repeat
3. Another list of scenes: Wilderness : (-45, 107), Salmonomicon:  (-52, 1), Museum District: (15,80), Golfcraft: (47, -45)
> fix: scene ui not refreshing correctly when screen size changes

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/ContentProvider.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/Tests.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/Tests/ContentProviderShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/Tests/ContentProviderShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/Tests/ContentProviderTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/Tests/ContentProviderTests.asmdef.meta
Fixes #1823 
Handle duplications  exceptions in the content map hashing (because of the use `ToLower()` to the name) to prevent scenes from crashing the explorer.
`-16,-126` surroundings are affected by this bug, test there but also extensively in other parts of the world, since this changes a core aspect of the project.
> fix: duplicated keys in content mappings

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Tests/CharacterControllerTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Tests/CharacterControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Fixes #476
WHY
Through comms we always report the CAMERA rotation but we should be reporting the CHARACTER rotation, otherwise when players are using the third person camera, they think the rest of the users see them in the direction they point their avatar but they actually see the rotation of the camera...
<s>kernel PR need to be merged first: https://github.com/decentraland/kernel/pull/181</s>
> fix: main player comms reported rotation

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Chunk.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Textures.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Textures/MinimapPlaceholder.png
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Textures/MinimapPlaceholder.png.meta
Fix #1749
Removes the gaps between map tiles 
Adds a placeholder image when map chunks are still loading
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/remove-map-tiles-gaps
2. Open the map
3. Verify that by moving around no gaps appear between tiles
> fix: added texture wrap mode to avoid map tile gaps

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
Fix #1752
Sets Collectibles as the default panel in the backpack section
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/collectibles-as-default-section
2. Open the menu
3. Go to backpack
4. Verify that collectibles is the default selected panel
5. Change panels and verify the consistency of the selections
6. Verify selections persistency on close/open menu
> fix: set collectibles as default backpack panel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/SettingsPanelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.cs
fix: SetTutorialButtonEnabled is used after the view is disposed of, add check to avoid null reference
Fix partially: https://github.com/decentraland/unity-renderer/issues/1759
> fix: avoid the websocket server to close inactive connections

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
Moves the StartMenu initialization before the `RendererState` is activated in order to avoid unnecessary hiccups when the world is up.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/Move-StartMenu-initialization-before-the-world-is-up
2. Wait for the world is up.
3. Open the StartMenu and check that everything is working fine.
> fix: Move the StartMenu initialization before the world is up

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
Revert the PR #1828: "set collectibles as default backpack panel"
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/revert-set-collectibles-as-default-backpack-panel
2. Open the Backpack.
3. Notice the default open section is BODY.
> Revert "set collectibles as default backpack panel"

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
Reverts https://github.com/decentraland/unity-renderer/pull/1852 because it seems this change affected to the Map behaviour and broke it.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/revert-start-menu-initialization-improvement
2. Open the Map.
3. Notice it is working correctly.
> fix: Revert "Move the StartMenu initialization before the world is up"

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
Moves the StartMenu initialization before the `RendererState` is activated in order to avoid unnecessary hiccups when the world is up.
**NOTE**: It is the second part of https://github.com/decentraland/unity-renderer/pull/1852
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/move-start-menu-initialization-before-the-world-is-up-II
2. Wait for the world is up.
3. Open the StartMenu and check that everything is working fine.
> fix: Move the StartMenu initialization before the world is up (II)

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
Fix #1856 
The default panel of the guest onboarding is no longer collectibles but body shape
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/backpack-default-panel-for-guest
2. Connect with a guest session
3. Verify that the first panel is the first one and not collectibles
4. Disconnect
5. Connect with a valid user
6. Verify that opening the backpack loads the collectibles panel first
> fix: change default panel for guest users from collectibles to body shape

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
Fixes an issue caused by the prefab merging from the branch fix/backpack-default-panel-for-guest  to master. In short it re enables the collectibles panel as default for regular users
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/resolve-backpack-hud-merge-failure
2. Open the backpack as regular user and verify that the first panel is the collectibles
3. Start a new session as guest and verify that the first panel is the body shape
> fix: fixed prefab merging failure for backpack panel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
Fix #1671 
Extends the profile collider to the top right corner
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/profile-icon-hitbox-improvs
2. Click on the top right profile icon
3. Verify that the collider gets the click up till the top right corner
> fix: extends profile icon collider to top right corner

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/FreeMovementController.cs
Fix #1753
With this PR the avatar movement speed should not be influenced by FPS anymore
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/fps-affecting-avatar-movement
2. Go to a crowded area and maximize the settings
3. Walk around
4. Lower the settings to minimum
5. Walk around
6. Verify the consistency between speeds
> fix: avoid fps affecting movement speed

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/Realms/RealmSelector_Modal.prefab
The message of the pop up has been modified.  
From this  
`Decentraland is distributed in different independent realms. Warp in between them to meet your friends or visit exclusive events in dedicated environments.`
To this  
`Decentraland servers are run by the community. Each server is an independent realm. Warp in between them to meet your friends or visit exclusive events in dedicated environments.`
> fix: realm message 

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Fix #1888
Avoid camera change when using mouse scrollwheel and cursor over an UI element
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/disable-scrollwheel-when-ui-mouseover
2. Scroll in and out to change from first to third person camera
3. Place the cursor above an UI element
4. Scroll in and out and verify that the camera mode doesn't change
> fix: disable scrollwheel camera change when mouse on UI element

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/BlockedAndMasterPromisesShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/CoroutineHelpers/CoroutineUtils.cs
This PR fixes #1890 
**WHY**
* When traversing long distances without stopping, (as shown in #1890 with the railroad scene) the user can be loading and unloading a lot of scenes around him very quickly. In that scenario, many asset promises get cancelled while loading.
* When a same asset is requested from different scenes, if the first instance of the asset promise is still loading, the subsequent ones get into a WAITING blocked state that gets resolver AFTER the first one finishes downloading the asset and loading it. Those first asset promises are what we call **master promises**, and when those promises [are told to be forgotten](https://github.com/decentraland/unity-renderer/blob/ab815ad8c95bf5ddd1fb43dc80a799e28ea72af0/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetMa …
> fix: scenes stuck loading on GLTF promises silent forget

- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/OpenSea/RequestController.cs
In editor and desktop, opensea was giving 403 for all our requests.
This should fix the issue temporarily without having to use an api key.
An easy way to test this is running from desktop or editor and go to 45,93. Or any scene that makes heavy use of NFTShapes.
> fix: opensea 403 workaround

- .circleci/config.yml
Pipeline error because of missing apt-get update
> chore: update apt-get before installing a package

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUDView.cs
`fixes decentraland/explorer-desktop/#118`
1. Go to desktop launcher (--developer-mode) and set `fix/overlapping-gif` over explorer-desktop branch
2. Go to soho plaza (-88,8) and enter into the gallery
3. Open the nft preview on all the gifs you see
4. The gifs should be previewed correctly
> fix: gif nftshapes preview modal breaks subsequent preview modals

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BlockerController/BlockerHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BlockerController/Interfaces/IBlockerInstanceHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BlockerController/WorldBlockersController.cs
**WHY**
When we are initializing the world, sometimes it happens that we end up loading (and prioritizing) the parcel next to the one we specified in the URL instead of the desired one because the character collides with the world blockers when the rendering is OFF. The problem is specially annoying for debugging entering to a specific scene with LOS=0 for example.
**WHAT**
Added world blocker colliders enabled state initialization and toggling based on renderer state
> chore: toggle world blocker colliders on renderer state change

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
Fix #1954 
avoids the chat focus to be lost when pressing + or - keys when typing
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/minus-key-removes-chat-focus
2. Open the chat
3. Start typing
4. Type the "+" or "-" character
5. Verify that the focus is still on the chat input
> Fix: avoid plus/minus key focus removal from chat input text

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventsSubSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/HighlightsSubSection/HighlightsSubSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlacesSubSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Resources/Chat Widget.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/HUDCommon.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ScrollRectSensitivityHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ScrollRectSensitivityHandler.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCardHUD.prefab
commit to debug webgl build after CI passes
temporary debug stuff
Additional changes for sensitivity handling with debug stuff
Minor compilation bugfix
minor changes
additional test changes for slider sensitivity
Cleanup of scroll rect sensitivity adjustment
fixed windows and default slider sensitivity multipliers
adapted windows multiplier
changed os based multiplier values
minor change
applied scroll rect wherever required
fixed scroll values in avatar scroll rects
minor improvements to scroll values
TESTING
https://play.decentraland.zone/?renderer-branch=fix/scroll-sensitivity-in-player-card-collectibles-2
> fix: added OS based system to force scroll rect sensibility

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMovementController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
for the moment we do not officially support using `AvatarShape` through the sdk, but devs can still use it.
so here are some fixes to mitigate the possibility of the explorer malfunctioning when an `AvatarShape` is created by a scene.
changes:
*avoid adding scene avatars to `DataStore` variable `otherPlayers`
*fix issues generated by avatar model's field `id` not being set
*use local scene position instead of world position to translate avatars created by a scene (we might want, in the near future, to start supporting devs using `AvatarShape` in their scenes)
*removed some duplicated code regarding avatar movement (the calculation was already done by `AvatarMovementController`)
*relocated subscription to entity's transform changes, since the subscription was done after the avatar is …
> fix: non global-scene avatars

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/TextureHelpers/TextureHelpers.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
* In many parts of the world we are resizing every texture loaded that is bigger than 1024x1024. We even have lots of textures in the first base wearables that get resized every time we enter the world if any avatar is using them. (With Asset Bundles this resizing is avoided as those textures were already resized when converting the asset to AB).
* If we can move to the GPU the textures resize we do in runtime for the Desktop Client, it will run smoother now that we have removed the runtime compressions for the Desktop Client as well.
* This optimization of using `Graphics.CopyTexture()` (copying everything directly in the GPU without passing through the CPU) instead of reading from the `RenderTexture` with `Texture2d.ReadPixels()` + `Texture2d.Apply()` that's quite expensive, can only be …
> chore: move GLTFs texture resize to the GPU for desktop client

- unity-renderer/Assets/DCLPlugins/DebugPlugins/PreviewMenu/DebugPlugins.PreviewMenu.asmdef
- unity-renderer/Assets/DCLPlugins/DebugPlugins/PreviewMenu/View/Scripts/PreviewMenuPositionView.cs
in preview mode menu user can copy the current position by clicking on the panel displaying it, but there is no visual feedback on what happen on click, so it's look more like a "hidden feature"
*added toast to notify user that the position was copied to the clipboard
fixes https://github.com/decentraland/sdk/issues/213
> fix: preview menu display toast on position copied

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateFPS.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateTPS.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/CameraTests.cs
fixes https://github.com/decentraland/sdk/issues/121
camera was not rotating correctly when receiving rotation message from kernel
*modified `OnSetRotation` math from first and third camera state controller
> fix: set camera rotation from kernel message

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTAsset/NFTInfoLoadHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Tests/NFTInfoLoadHelperShould.cs
added missing nullref check, saw this nullref appearing when moving out of the museum district scene.
> fix: missing nullref check in nftshape info success event

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioClip.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Asset_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Asset_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MeshesInfo/MeshesInfoUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MeshesInfo/Rendereable.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_WorldObjects.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DataStore_Rendering_Extensions/DataStore_WorldObjects_Extensions.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/BaseComponent.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/SceneMetricsModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneMetricsCounter/MetricsScoreUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneMetricsCounter/MetricsScoreUtils.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneMetricsCounter/SceneMetricsCounter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/MemoryScoreFormulasShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/MemoryScoreFormulasShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneMetricsCounterShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/WithAudioClip_SceneMetricsCounterShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/WithAudioClip_SceneMetricsCounterShould.cs.meta
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporterUtils.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporterUtils.cs.meta
- unity-renderer/Assets/UnityGLTF/Scripts/IGLTFComponent.cs
This PR implements limits score counting for memory. The memory we are counting per scene covers:
- Textures
- Meshes
- AnimationClips
- AudioClips
For now, the counting is enabled for GLTF loading only. Convering asset bundle loading requires to bundle meta-data to each AB package and will be covered in other PR.
The memory metrics are counted only, not limited or enforced in any way (yet).
The scoring formulas aren't exact. To deal with the lack of accuracy in a safe way, they are designed to overshoot the actual memory footprint. This is covered by tests.
https://play.decentraland.zone/?renderer-branch=feat/better-scene-metrics
As this PR doesn't add visible functionality, you should at least see that the existing limit counting mechanics keep working. …
> feat: better scene metrics (memory)

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/TextureHelpers/TextureHelpers.cs
left only the `Graphics.CopyTexture()` approach in `TextureHelpers.CopyTexture()` as it works in WebGL.
I ran countless test scenarios with local builds and for some reason `Graphics.CopyTexture()` works fine in WebGL in our `TextureHelpers.CopyTexture()` (even though `SystemInfo.copyTextureSupport == CopyTextureSupport.None` in WebGL) but it doesn't in `TextureHelpers.Resize()`.
bugged in master: https://play.decentraland.zone/?position=-20,1&DISABLE_ASSET_BUNDLES
fixed in this PR: https://play.decentraland.org/?position=-20,1&renderer-branch=fix/CopyTexture&DISABLE_ASSET_BUNDLES
> fix: CopyTexture

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/CharacterPreview.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/PreviewCameraRotation.cs
This reverts commit ae278536b1738e08a248abbb3052e4db1033ebc9.
Reverts the avatar hud changes to avoid conflicts with nft emotes
> Revert "Chore: various avatar preview improvements (#1963)"

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Asset_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Asset_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MeshesInfo/Rendereable.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_WorldObjects.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/DataStore_Rendering_Extensions/DataStore_WorldObjects_Extensions.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/SceneMetricsModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneMetricsCounter/MetricsScoreUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneMetricsCounter/SceneMetricsCounter.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/MemoryScoreFormulasShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneMetricsCounterShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/WithAudioClip_SceneMetricsCounterShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/WithTexture_SceneMetricsCounterShould.cs
* Add support for profiler backed memory metrics to be able to better validate our memory scoring formulas (this only works on development and editor)
* Many null ref and general fixes
* Small scoring fixes to be able to count memory usage correctly
2. ...
> fix: metrics counting issues

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmotesHUD/EmotesHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Resources/ExternalUrlPromptHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GotoPanelHUD/Resources/GotoPanelHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Resources/HelpAndSupportHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/Prefabs/OwnersPopup.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/Resources/NFTPromptHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/QuestsPanelHUD/Resources/QuestsPanelHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/Resources/TeleportPromptHUD.prefab
- Recover the close button in the some HUDs that were missed it.
- Fix the issue of the unavailable base emotes when the feature flag was disabled and the user didn't open the wheel.
- **TEST WITH FEATURE FLAG ENABLED**: https://play.decentraland.zone/?renderer-branch=fix/Several-fixes-in-the-emotes-ui-2&ENABLE_EMOTES_CUSTOMIZATION
- **TEST WITH FEATURE FLAG DISABLED**: https://play.decentraland.zone/?renderer-branch=fix/Several-fixes-in-the-emotes-ui-2&DISABLE_EMOTES_CUSTOMIZATION
> fix: Several fixes in the Emotes UI (II)

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/TestScene/APK_GLTF_InteractiveTest.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
Fixes a Memory Leak caused by textures being created asynchronously and the process being canceled before those textures were handled correctly for their deletion.
This was introduced with #1761 
Unity Only:
- Open up APK_GLTF_InteractiveTest scene and run it
- Open up the Profiler and check out current Texture and Mesh memory and **save those numbers**.
- Press Z to spawn GLTFs and X to delete the last one loaded, you can press C for an automated and randomized Loading and Deletion and press again to toggle it Off.
- Press X until no GLTFs are loaded
- Check the Texture and Memory usage and compare it with the initial values, they must be equal or somewhat close (< 1 MB of tolerance )
> fix: memory leak caused by cancellations

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs
Reduces the memory usage of the Map Textures by ~75%
Before ( 7x7x10.6 = 519.4 MB ) 
After: (7x7x2.7 = 132.3 MB )
**IMPORTANT NOTE:**  The side effect of doing this is that there's a new hiccup when opening the map. 
> feat: compress map texture chunks to reduce memory usage

- unity-renderer/Assets/Scripts/MainScripts/DCL/EmoteAnimationsPlugin/EmoteAnimationsPlugin.cs
Embedded emotes were being disposed by mistake due to not being in the `emoteOnUse` collection.
Just change your bodyshape and play emotes
> fix: now embedded emotes are not wrongly removed

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs
Fetches texture as non readable for map chunks, avoids generation of mipmaps but lowers the memory impact
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/revert-map-chunk
2. Verify that the map opens and visualises correctly
3. Verify how commonly the app crashes
> Fix: removed mipmaps generation on map chunks

- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Reduce max texture size to 512
> chore: set max texture size to 512

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Long.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Modal.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Common/ExploreEventsUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventCard/EventCardComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/EventCardComponentViewTests.cs
- unity-renderer/Assets/Textures/UI/JumpIcon.png
- unity-renderer/Assets/Textures/UI/JumpIcon.png.meta
- unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
Add a mini-JumpIn button for non-live event cards, in order to let the users teleport to the place even if the event has not started.
**NON-LIVE EVENT (CARROUSEL CARD):**
**LIVE EVENT (CARROUSEL CARD):**
**NON-LIVE EVENT (NORMAL CARD):**
**LIVE EVENT (NORMAL CARD):**
> feat: Add jump in button to non-live event cards

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Common/CloseCardModalButton.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Long.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Modal.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/HighlightsSubSection/PlaceCard_Long.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/FriendHeadForPlaceCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlaceCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlaceCard_Modal.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesAndEventsSectionComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventCard/EventCardComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/HighlightsSubSection/HighlightsSubSectionMenu/HighlightsSubSectionComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlaceCard/PlaceCardComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/PlacesSubSection/PlacesSubSectionMenu/PlacesSubSectionComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/EventCardComponentViewTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/EventsSubSectionComponentControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/HighlightsSubSectionComponentControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/PlaceCardComponentViewTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/PlacesSubSectionComponentControllerTests.cs
- unity-renderer/Assets/UIComponents/Scripts/Components/Image/ImageComponentView.cs
- Use the **caching option provided by the `Image` UI Component** for the event and place cards (before this improvement the images were being requested each time the card was instantiated and it took a lot of time).
- Set a **min time of 1 minute to request the data to the API** (before this improvement were always requesting data to the API each time the start menu was open).
- **Remove some unneeded calls** in the code.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/explore-v2-loading-improvements
2. Test the "Explore" section of the Start Menu.
> fix: Explore V2 loading improvements

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
Fix #2017
Removes the usage of ESC to open the explore
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/escape-explore
2. Press esc and verify it unlocks the cursor
3. Open the map and press escape to close it
4. Start chatting and press esc to close the chat
> Fix: Remove esc to open explore

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab
Fix #2064 
Renders player icon above other player icons
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/player-icon
2. Verify that in a crowded area your player icon in the map is above others
> moved player icon render above other player icons

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/BuilderMainPanelController.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/Handlers/SceneContextMenuHandler.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/Unpublish/UnpublishPopupController.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Tests/UnpublishPopupShould.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/ProjectPublishHUD/Scripts/Projects/PublishMapView.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Publisher/Scripts/Publisher.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuilderEntity/BIWEntity.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/BuildingTool.asmdef
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Gizmos/BIWGizmos.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Scripts/Interfaces/IPublisher.cs
This PR fixes #1712. It enables the unpublish from the builder in world again
This PR fixes #1945. The physics are now sync correctly when we end transforming items
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/biw-unpublish&kernel-branch=feat/biw-invalidate-scene-info)
2. Test that you can unpublish an scene
> fix: biw unpublish and physics update

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/AvatarModifierArea.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/Tests/AvatarModifierAreaShould.cs
Avatar inside `AvatarModifierArea` were losing it modifiers every time the component was updated.
For example, in the following code, the avatar inside the area becomes visible every time the area size changes and the avatar must move out and in the area to become invisible again.
```
let active = true
const e1 = new Entity();
const m = e1.addComponent(new AvatarModifierArea({ area: { box: new Vector3(16, 1, 14) }, modifiers: [AvatarModifiers.HIDE_AVATARS] }))
e1.addComponent(new Transform({ position: new Vector3(16 * 0.5, 1, 9), scale: new Vector3(16, 1, 14) }))
e1.addComponent(new BoxShape()).withCollisions = false
Input.instance.subscribe("BUTTON_DOWN", ActionButton.PRIMARY, false, ev => {
if (active) {
m.area = { ...m.area, box: new Vector3(16, 2, 14) }
log(`change avatar area`)
} …
```
> fix: AvatarModifierArea losing modifiers after model update

- unity-renderer/Assets/Scripts/Editor/BuildCommand.cs
Needed by https://github.com/decentraland/explorer-desktop/pull/193
to fix: https://github.com/decentraland/explorer-desktop/issues/192
> chore: set SetOSXUniversal Architecture to Intel x64

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
Changes the behavior on exiting the application, this might fix some errors when exiting the application from Desktop (https://github.com/decentraland/explorer-desktop/issues/116).
Enter play mode, wait until genesis plaza is loaded and exit play mode, no error should show up after exiting.
> fix: changed how the application quit is handled

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLAvatarTexture.cs
Fix #2088
Removed unused face and face128 variables in Snapshots class
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/remove-face
2. Change wearables
3. Save
4. Close and reopen
5. Verify the correctness of the profile pic
> chore: removed unused face/face128 definitions

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
Fix #2111 
Avoids map to be invisibile when closing the explore
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/minimap-invisible
2. Open explore with shortcuts
3. Close it
4. Verify minimap is still visible
> Fix: show minimap on explore closure

- unity-renderer/Assets/ABConverter/Core.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/CoroutineHelpers/CoroutineUtils.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
- unity-renderer/Assets/UnityGLTF/Scripts/IGLTFComponent.cs
- unity-renderer/Assets/UnityGLTF/Tests/GLTFBenchmark.cs
Fixes #1980 throttling regression.
Bonus:
Removed all local throttles as they do little to no difference on performance rather than fix very specific use cases. 
Also added an option to force the coroutines to be run synchronously to fix the Asset Bundle converter. 
Run through the world with Asset Bundles disabled, meshes should be correctly throttled on their creation and should be fewer hiccups.
> fix: GLTF mesh creation throttling regression

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
Tried other solutions to fix the problem we get on **the desktop client** character controller getting "floaty" for a second when reaching the ground but since those other solutions (like using `FixedUpdate()`) require to re-balance gravity, etc. I went for the simpler solution that doesn't affect the web client and solves the issue at the desktop client: decreasing a bit the ground check extra distance value.
In case you want to test that the character controller jump height and slope walking keeps working as expected you can enter this scene at ropsten network:
https://play.decentraland.zone/?NETWORK=ropsten&position=59%2C-67&realm=thor&renderer-branch=chore%2FImproveCharacterGroundCheckExtraDistance
And test that the last slope (47.5º) cannot be "walked on" (all the previous can):
And …
> chore: improve character ground check extra distance

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Possibly fixes #1900
Adds a small offset for movements input to avoid unwanted movements caused by controller drift
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/controller-drift
2. Move around
3. Move around with a controller plugged to the pc
4. Verify that there are no unwanted movements
> Fix: adds a small offset to avoid controller drift induced movements

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
Fix #2133 
Removes the possibility of changing camera mode with mouse wheel in no camera change modifier areas
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/force-fp-wheel
2. Go to an area enforcing first person view
3. Try to change mode with mouse wheel or with the v key
> avoid camera change if in no change zone

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
Currently when we override 3D assets loaded container GameObject with "AB:..." or "GLTF:..." many times the "AB:..." is not applied (but the "GLTF:..." is not applied either).
Moved editor naming of ABs and GLTFs to the right place
> chore: improve AB GLTF editor naming

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUD.prefab
Fix #2120 
Adds sound effects to three dots button, closes the new panel when the cursor gets locked again (same behavior as taskbar panels)
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/minimap-menu-improvs
2. Verify the sound effects on the minimap menu button
3. Lock the mouse and verify that the panel closes itself
> minor fixes in minimap new panel

- unity-renderer/Assets/Scripts/Tests/VisualTests/VisualTestsBase.cs
- unity-renderer/ProjectSettings/QualitySettings.asset
This PR enables mipmap streaming, so all the loaded mipmaps have a max budget of 512 MB and are loaded/unloaded by a process.
https://docs.unity3d.com/Manual/TextureStreaming.html
> fix: enable mipmap streaming

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShape.cs
Fixed memory leaks caused by references in a dictionary that was holding objects with references that should be cleaned up.
This should fix #2082 
I ran some tests with this steps:
- I made use of the `LOCAL_COMMS` URL parameter that prevents the loading of other avatars, this removes "noise" from the profiling.
- The first snapshot is taken at 0,0 (Genesis Plaza) when the boards finish loading.
- The second snapshot is taken after I teleport to 100,100 (mostly barren land) and go back to 0,0 and repeat this process 2 times. So when the snapshot is taken, Genesis plaza was loaded and destroyed 3 times in total.
- Between A and B I've closed unity to prevent the profiler to have garbage
Snapshots A has the fix
Snapshots B doesn't.
Although Unity memory profiler has its issues, it still …
> fix: memory leak

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
Fix #2106
Avoids explore from being stuck between transitions
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/explore-stuck
2. Open and close the explore multiple times
3. Verify that it never gets stuck as in the screenshot attached to the issue #2106 
> Fix: fixed explore being stuck in transitions

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCardHUD.prefab
Fix #1702 
Avoids user passport to close randomly
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/passport-closing
2. Inspect a random player
3. Try to use the passport
4. Verify it doesn't randomly close
> fix: random passport close

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatEntryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDShould.cs
Fix #2134 
In this screenshoot we can appreciate how ilegible the player's name is. This is because in runtime the code is automatically adding the bold command when it is not necessary. See the screenshot bellow.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/players-names-in-general-chat-are-not-legible
2. Write something in the chat and notice the message is showed correctly legible.
3. Write a private message and notice the message is showed correctly legible (in both places general and private window).
> fix: Players' names in General Chat are not legible

- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
The avatar loading was not rethrowing when cancelled and breaking some flows
> fix: rethrow OperationCancelled exception to be caught upstream

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
Player profiles update were not being tracked and therefore names in the AvatarShape or the chat.
> fix: react to updates in player profiles

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
Fixes a crash caused by opening a thread to process Regexes and not going back to the main thread.
Desktop Client shouldn't crash.
> fix: chat messages crashing desktop client

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/EntityIdHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/EntityIdHelperShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/EntityIdHelperShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
This PR changes the way we get the long number for an entity id from a string, we were using the GetHashCode approach but since that approach can make some iDs to collide I have changed it to decode the base36 string
I also has done some perfomance benchmark to ensure that we are not losing too much perfomance with this changes.
For the benchmark I just stay at the casino while everthing is loading. Since a lots of messages are sent in the casino scene, we can meassure if there is an impact when a lot of entityIds are converted
Testing in the casino , we lose 0.01 seconds (in total) when you are standing in the casino for 30 seconds with the conversion . The GetHashCode approach lose less than 0.00001 seconds
1. Go to: https://play.decentraland.org/?renderer-branch=fix/entity-collision&pos …
> fix: change to decode instead of GetHashCode for entity ids

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
Fixed a crash that was caused by doing unity stuff while on a worker thread, whoops.
This fixes https://github.com/decentraland/explorer-desktop/issues/278
Open a user profile in desktop client, it shouldn't crash.
> fix: desktop crash due to multithreading issues

- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/Tests/UUIDComponentTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/EntityIdHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Messaging/MessagingControllersManager.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/EntityIdHelperShould.cs
- unity-renderer/Assets/Scripts/Tests/TestUtils.cs
Test link: https://play.decentraland.zone/?renderer-branch=fix/entity-dissapear
Increases the performance of the entity id back and forth conversion.
My tools for C# are limited and I couldn't get Unity + IDE to work in time. So here are the tests that need to be added:
```c#
public void test(string s, long expected) {
Console.WriteLine("For string {0}", s);
var	r = GetConvertedEntityId(s);
if (r != expected) {
Console.WriteLine("  ERROR! Num expected={0} (0x{0:X}) given={1} (0x{1:X})", expected, r);
throw new Exception("failed");
} else {
Console.WriteLine("  OK     Num expected={0} (0x{0:X}) given={1} (0x{1:X})", expected, r);
}
var gen = GetOriginalId(r);
if (gen != s) {
Console.WriteLine("  ERROR! Gen expected={0} given={1}", s, gen);
throw new Exception("failed");
} else { …
```
> fix: increase performance in hot code path

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Fix #2251
Users can now play emotes on moving platforms
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/platform-anim
2. In genesis plaza go on the air balloon
3. Try to play emotes on it and verify it works
4. Play emotes in other contexts and verify a regular behavior
> Fix: allow user to play emotes on moving platforms

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
Avoids triggering freefall camera when standing on invisible colliders
> fix: disabled freefall camera when standing on invisible colliders

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntryBase.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntryModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntryModel.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendRequestEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendRequestEntryModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendRequestEntryModel.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/IFriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/CollapsableSortedFriendEntryList.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendRequestsTabComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendsTabComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendEntryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendRequestEntryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/FriendsHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/FriendsHUDWindowMock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- unity-renderer/Assets/UIComponents/Scripts/Components/CollapsableSortedList/CollapsableSortedListComponentView.cs
`closes #2340 `
Some users have many friends to list and/or many pending friend requests (more than 1k), pushing the limits of the webgl application. To solve this issue:
-  load/unload friend's profile pictures on demand depending on what is visible in the scroll.
-  throttle the load of friend request to avoid hiccups.
-  improve list sorting & layout updating to avoid hiccups.
-  searching friends on the search bar should query all the friends, no matter if they are displayed or not.
Limit friend entries:
-  load a maximum of 50 entries at start
-  online friends has no limit
-  add a button show more at the bottom of the scroll. Whenever you click it, it will load 30 entries
-  friend requests should have the same behaviour
1. 50+ friends is required
2. Open the friends window, there …
> fix: performance optimizations when user has many friends

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
The linked wearables dropdown was in the backpack sections hierarchy instead with the wearables categories which is the place it belongs.
BEFORE
AFTER
1. Go to: https://play.decentraland.zone/?renderer-branch=style/LinkedWearablesDropdown
2. Open the avatar section in the backpack. You will notice that the linked wearables dropdown has been moved on the wearables categories hierarchy.
> style: linked wearables dropdown

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/Tests/WearableItemShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
Some wearables contain "body-shape" in their hides lists. This breaks our avatar loading process because the bodyshape is never retrieved.
You can test this wearable in this url
https://play.decentraland.zone/?WITH_ITEMS=urn%3Adecentraland%3Amatic%3Acollections-thirdparty%3Acryptoavatars%3A0x28ccbe824455a3b188c155b434e4e628babb6ffa%3A673&CATALYST=peer.decentraland.org&DEBUG=true&NETWORK=ropsten&realm=v2%7Epeer.decentraland.org&renderer-branch=fix/wearables-hidding-bodyshapes
> fix: remove bodyshape from hides lists

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendsTabComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ConversationListHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/WorldChatWindowViewMock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CollapsableChatSearchListComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IWorldChatWindowView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PrivateChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- unity-renderer/Assets/UIComponents/Scripts/Components/CollapsableSortedList/CollapsableSortedListComponentView.cs
`Closes #2344 `
1. check that list is displayed correctly
2. check the search bar works as expected
3. all profile pictures of the visible entries should be displayed correctly
1. a max of 50 entries should be loaded at start
2. when you scroll to the bottom an option saying "show more" should be displayed with label indicating how many entries are hidden
3. click the "show more" button, it should display another 30 entries
4. use the search bar. All entries should be displayed matching your input, no matter if they were displayed or not
5. check that all profile pictures of the visible entries are displayed correctly
> fix: limited the amount of private chat channels & optimized loading hiccups

- unity-renderer/Assets/Resources/Prefabs/InputController.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ChatNextInHistory.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ChatNextInHistory.asset.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ChatPreviousInHistory.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ChatPreviousInHistory.asset.meta
`Closes #1666 `
Press `UP arrow key` or `DOWN arrow key` to set the previous messages sent in the chat input field.
1. Send any message in the chat
2. Pressing `UP arrow key` the last message should be set in the input field
3. Keep sending messages
4. When `UP arrow key` or `DOWN arrow key` should iterate over the whole chat history
5. The last history iteration should be filled with an empty text
6. Messages should not be duplicated in the history
> feat: chat history iteration with up & down keys

- .gitattributes
Updated `gitattributes` to force conflicts in unity files.
A simple test is to create two branches from this one, modify the same prefab changing values (both values should be far away in the file, to ensure no text conflicts) and merge one into another. With the `gitattributes` change a conflict should arise, and without it the file should auto-merge.
> chore: disable prefabs merge

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/Helpers/FriendsController_Mock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/IFriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendRequestsTabComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/GeneralChatChannelHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatChannelComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/WebInterfaceFriendsController.cs
- private & public chat windows are resized to avoid overlapping with scene UIs
- hide direct chats loading spinner when the user is a guest
- received friend request notifications count at taskbar
1. Authenticate as a guest, open the chat list window, search for a friend. No UI components should be overlapped.
2. Go to ice poker scenes, check that the chat in transparent mode does not overlap with their UI.
3. Receive a friend request, the notification count should be updated correctly in the taskbar.
> fix: friend request notification count, direct messages spinner for guests & chat window resizing on preview mode

- unity-renderer/Assets/Rendering/Shaders/URP/FadeDithering.hlsl
Due to some camera tricks for the new floor, the objects hidden in the negative Y of the world were being displayed. This fixes it by discarding the pixels directly.
Test below the floor is rendered. Also take a look at the world, GLTF transition effect and such.
> fix: discard pixels below Y plane

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionHeart.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Textures/AvatarParticleExpressionHeartPride.png
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Textures/AvatarParticleExpressionHeartPride.png.meta
When a user does the "Kiss" avatar expression, it spawns hearts. This PR applies a random color from a set of colors, based on the pride flag - as celebration of pride month (June).
This is done by using the sprite sheet animation module in the particle system which is on the Kiss avatar expression prefab. There is a multi-sprite with 10 new heart sprites. Each sprite has a different color. The sheet animation module picks a random sprite every time it spawns a heart.
...
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/heart-emotes-with-pride-colors
2. Open the Expressions menu
3. Select the "Kiss" expression
4. Notice the color of the hearts
> feat: Avatar expression hearts get random pride-color

- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/Skybox3DElements/SkyboxElements.cs
Fix #2426
Fixes null reference in skybox initialization
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/null-ref-skybox
2. Verify that Decentraland starts correctly
3. Verify the correct behaviour of the skybox
> Fix: null reference in skybox init

- unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Fixes GLTF importing in Editor throwing timeouts because of async calls that weren't correctly functioning and should have been ignored by the forceSyncCoroutines flag.
Fixes #2436
Import #2436 example glb, it should be imported almost instantly.
> fix: gltf importer having undesired async calls when force sync was true

- unity-renderer/Assets/Rendering/Utils/GPUSkinning/SimpleGPUSkinning.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombiner.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/AvatarMeshCombinerUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMeshCombiner/Tests/AvatarMeshCombinerUtilsCan.cs
When a lot of avatars spawn, the GarbageCollector causes hiccups very frequently, this is caused by very large allocations every time an avatar is spawned. 
Reduced the allocations of copying arrays by using Unity's NativeArray which provides allocation-free management of arrays.
Performance Score incremented from `68,78` to `73,87`
Allocations over 30 seconds lowered from `544.585,61` to `509.632,536`
(results might differ because genesis plaza is chaotic and people move, the test started when the first avatar was about to spawn)
For more information, read the comments below.
> chore: reduce allocations from avatar system

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowHUDShould.cs.meta
`FriendsHUDController` listens to friend profile changes and updates the view with latest changes.
This change attempts to fix a problem when sometimes you cannot see the user names of your friends correctly displayed in the list.
1. Wait until all friends are loaded
2. Open the friend list, all friends should be displayed correctly
3. If any of your friends changes its name, it should be replicated into the list
> fix: update friends entries when the profile changes

- README.md
- unity-renderer/Assets/Scripts/Editor/PreBuildProcessing.cs
- unity-renderer/Assets/Scripts/Editor/PreBuildProcessing.cs.meta
- Emscripten build toolchain for WebGL builds on Unity 2020.3 depends on Python 2.7 or later. [WebGL builds on Unity 2021.2 and later require Python 3].
- MacOS doesn't include Python anymore since macOS 12.3 (and removes the previously-existent version). So making a WebGL build locally in Mac 12.3+ always fails because Python can't be found.
1. Download Python 3+ at https://www.python.org/downloads/release/python-3105/
2. Have a PreBuildProcessing script in place (added in this PR) to re-map Python path when building. 
Resources:
- https://forum.unity.com/threads/case-1412113-builderror-osx-12-3-and-unity-2020-3-constant-build-errors.1255419/#post-7993017
- https://answers.unity.com/questions/1893841/unity-2020328f1-webgl-build-failed-on-macos-monter.html
Added PreBuildProcessing script …
>  fix: mac (12.3+) local web building

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ManaCounterView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
Fixed mana counter parser to use Culture invariant parses.
Fixes https://github.com/decentraland/explorer-desktop/issues/125
Log in with a wallet with mana, the counter should be correctly parsed.
> fix: mana counter value not being correctly parsed

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmotesWheelHUD/EmotesWheelController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
Fix #2430 
Avoids emote wheel from opening on emote shortcut usage
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/emote-wheel
2. Open the emote wheel
3. Use Emotes
4. Use emotes with the shortcuts and verify that the wheel doesn't open
5. Use the wheel in combination with the taskbar button
> Fix: emote wheel no longer opens on shortcut usage

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/Realms/RealmSelector_Modal.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GotoPanelHUD/Resources/GotoPanelHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/Resources/TeleportPromptHUD.prefab
The close button UI was not aligned with the UI guidelines not in the teleport/goto panels nor in the realm selector.
Animation on mouse interactions are now added too.
Teleport & Go to panel before vs. after
Realm selector panel before vs. after
1. Go to: https://play.decentraland.zone/?renderer-branch=style/CloseButton
2. Go to the scenes column in the genesis plaza and click any of the scene's card jump in button. You should see the new close button (squared + animation on mouse hover & click).
3. Then go to the main menu and click the realm selector. You should see the new close button in the realm selector panel  (squared + animation on mouse hover & click).
> style: close button

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Resources/ChatEntrySeparator.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/ChatEntryReceived.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/ChatEntrySent.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Chat/ChatEntry.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatEntrySeparator.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatEntryReceived.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatEntrySent.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PublicChatEntrySent.prefab
After we updated the project's unity version with a hacky fix (3-frame wait when populating a chat entry) for a crash that happened in the web client build, that same hack provoked a problem with chat entries positioning.
This PR moves that hack to the closest point to the crash-provoking code (the body.text manipulation as explained [here](https://github.com/decentraland/unity-renderer/pull/2345#issuecomment-1155753538)) and that solves the problem with the chat entries positioning.
I also removed all the placeholder texts that we had in several chat entry prefabs (as that placeholder text can be seen by a quick eye during the 3-frame wait)
**master branch build**
**This PR build**
- Test that opening the main menu -> Places and clicking in Wondermine -> Jump In doesn't freeze/crash the …
> fix: chat messages order

- unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationLoader.cs
- unity-renderer/Assets/DCLPlugins/EmoteAnimations/Tests/EmoteAnimationLoaderShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/EventCardComponentViewTests.cs
explorer-desktop repo always fail several tests due to the `EmoteAnimationLoader` tests being async: they are not awaited during the test run and their expected exceptions are thrown later while other tests are running, making those other tests fail.
These are 3 examples, notice that the error has nothing to do with the failed tests:
- [First unity version update in desktop client playmode tests fail](https://app.circleci.com/pipelines/github/decentraland/explorer-desktop/1185/workflows/7b96c093-8b23-4ce2-a1a1-1736ebfd6b0e/jobs/6122)
- [Second unity version update in desktop client playmode tests fail](https://app.circleci.com/pipelines/github/decentraland/explorer-desktop/1185/workflows/e40b1bcf-18aa-4ddb-8f97-2bad4ff682f6/jobs/6129)
- [Third uniy version update in desktop client …
> fix: emote animation loader tests async

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarLODController/AvatarLODController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/Tests/AvatarsLODControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/Tests/AvatarModifierAreaShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/Tests/AvatarModifiersTest.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Tests/UsersAroundListHUDShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Tests/UsersAroundListHUDTests.asmdef
Removed the avatars lod feature flag. Also removed the enabled bool attribute, since it was redundant without the flag's presence. Moved the flag initialization code into the Initialize method.
Some tests started failing since they were dependent on the enabled bool. Modified these tests accordingly to the modified code.
Go to: https://play.decentraland.zone/?renderer-branch=chore/remove-avatar-lods-feature-flag
Go to WonderMine scene
Check that the avatar lods are present when the number of avatars exceeds the Max HQ Avatars setting
> chore: remove avatar lods feature flag

- unity-renderer/Assets/Rendering/UI/ChargeWheel/M_ChargeBarV2Thicker.mat
- unity-renderer/Assets/Rendering/UI/ChargeWheel/M_ChargeBarV2Thicker.mat.meta
- unity-renderer/Assets/Rendering/UI/ChargeWheel/M_LoadingSpinnerBackgroundBlack.mat
- unity-renderer/Assets/Rendering/UI/ChargeWheel/M_LoadingSpinnerBackgroundBlack.mat.meta
- unity-renderer/Assets/Rendering/UI/ChargeWheel/SG_ChargeBarV2.shadergraph
- unity-renderer/Assets/Rendering/UI/ChargeWheel/S_LoadingSpinner.shader
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/IFriendsHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendRequestsTabComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendsTabComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/FriendsHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/FriendsHUDWindowMock.cs
- unity-renderer/Assets/UIComponents/Resources/LoadingSpinnerBlack.prefab
- unity-renderer/Assets/UIComponents/Resources/LoadingSpinnerBlack.prefab.meta
- friend entries loaded when you scroll down to the bottom on friend list and friend request list
- the "show more" option has been changed adding a loading spinner & a label modification
- the loading spinner style has been changed
1. Open the friends window from the taskbar
2. While the friend service is not initialized, check that the loading spinner has been resized to 40px
3. Force the initialization of friends
4. Scroll down to the bottom of the friend list
5. There should be an ui component indicating that we are loading more entries
6. Load all the available entries, the "show more" component should be hidden
7. Go to friend request tab and repeat the process
> feat: friend entries loaded by the scroll position & visual improvements on the loading spinners

- ci-benchmark-upload-report.sh
Unzip was missing in the benchmark report batch.
> fix: adding unzip needed for benchmarking upload

- unity-renderer/Assets/Tutorial/Scripts/TutorialController.cs
- unity-renderer/Assets/Tutorial/Tests/TutorialControllerShould.cs
- unity-renderer/Assets/Tutorial/Tests/TutorialControllerTests.asmdef
The tutorial was not starting because there was a check on `CommonScriptableObjects.rendererState.Get()` before subscribing the `OnRenderingStateChanged` method, which eventually triggered the tutorial. If the user went first to the avatar customization scene, renderState was true, and the event was not subscribed when the user got to Genesis Plaza. 
This was fixed by removing the check.
1. Delete cookies or start Incognito Window to have a fresh start
2. Go to: https://play.decentraland.zone/?renderer-branch=fix/tutorial-not-starting
3. Check that the tutorial appears after avatar customization
> fix: Tutorial not starting on new user

- unity-renderer/Assets/ABConverter/Tests/ABConverterCoreShould.cs
- unity-renderer/Assets/DCLPlugins/BuilderInWorld/HUD/ProjectsPanelHUD/Scripts/BuilderMainPanelController.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Editor/TestScene/ECSTestScene.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils/ContentServerUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Catalyst.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Wearables/WearablesAPIData.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Wearables/WearablesFetchingHelper.cs
Change "peer-lb.decentraland.org" in code base and change to "peer.decentraland.org"
The new load balancer is located at peer.decentraland.org
Nothing to test. All "peer-lb.decentraland.org" urls should now point to "peer.decentraland.org"
> chore: change peer load balancer url

- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/AvatarReveal.asmdef
- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/BaseAvatarReveal.cs
- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/RevealAnimation.anim
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarWithHologram.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/BaseAvatar.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/IBaseAvatar.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/IBaseAvatarRevealer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/BaseAvatarShould.cs
Disables hologram renderer after the animation ends.
The fadeOut method is now async
> fix: hologram renderer not being disabled after usage

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_AvatarConfig.cs
- unity-renderer/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Fixes the import of GLTF with Import Materials not checked.
**Important note**: Importing a GLTF with materials during the first import is still broken, this PR does not fix that, it just gives us an option.
When starting Decentraland, the avatar should load correctly.
> fix: GLTFImporter to generate a mesh when materials are ignored.

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GLTFShape/Handler/GLTFShapeComponentHandler.cs
This PR removes the GLTF component erasing all the renderer component when it is destryoed. This way the hot reload work as expected since we are not removing the renderers from the pool
Can't be tested
> fix: GLTF hot reload for new ECS

- unity-renderer/Assets/Rendering/LoadingAvatar/CrossSection/BaseAvatarReveal.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarWithHologram.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/BaseAvatar.cs
Fixes a bug where the avatar failed to stay visible when changing wearables by fixing how the FadeOut cancellation is being handled.
Change a wearable and press done, the avatar should go through the hologram phase and should work correctly.
> fix: wearable change failure

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TransactionHUD/TransactionHUD.cs
Updated the text displayed when the user wants to sign a transaction. Now it should say "This scene is requesting the signature of a message. If you are interested, please click the Allow button to receive it in your Wallet Connect application. This action does not imply message approval."
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/update-misleading-text-on-pending-transactions
2. Login using WalletConnect
3. Teleport to (61,-27)
4. Try to start a transaction with any of the items there
5. The message that popups should say "This scene (61,-27) is requesting the signature of a message. If you are interested, please click the Allow button to receive it in your Wallet Connect application. This action does not imply message approval." …
> fix: update misleading text on signing request

- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/PointerEventsController/PointerEventsController.cs
This PR fix a null reference that sometimes appears while walking in the world. They are harmless but can introduce noise
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/genesis-null-pointer
2. Go outside the building of genesis plaza and walk a bit to see if you see any null reference in the editor
> fix: null references while walking for the world

- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Performance.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
Adds some debug options to tweak how the renderer behaves on Unity editor, this is mostly used when profiling:
1.  Disable Asset Bundles
2.  Disable Texture Compression
3.  Disable GLTF Download Throttling
> feat: added some debug settings

- unity-renderer/Assets/Resources/ScriptableObjects/ForcePerformanceMeter.asset
- unity-renderer/Assets/Resources/ScriptableObjects/ForcePerformanceMeter.asset.meta
- unity-renderer/Assets/Scenes/InitialScene.unity
- unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/DebugBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugParameters.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/Performance/PerformanceMeterController/BenchmarkResult.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/Performance/PerformanceMeterController/BenchmarkResult.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/Performance/PerformanceMeterController/PerformanceMeterController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/Performance/PerformanceMetricsController.cs
Updated the performance meter tool to give us frame data instead of fps, also added error margins
Fixes #2460
run `clientDebug.RunPerformanceMeterTool(30)` in the browser console an wait for the results
> chore: performance meter update

- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxCamera.cs
- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Camera.cs
Our current Camera Stack is:
```
- Skybox (Base)
- World Camera (Overlay)
- HUDs Camera (Overlay)
```
Going into a fullscreen HUD will disable the cameras for performance's sake. Since the HUDs are now in camera space, we were forced to change the camera mode of the HUD camera to Base (instead of Overlay) when in this mode. 
Now the skybox camera is never disabled, even if we are in a fullscreen HUD. The impact in performance is not even noticeable and simplyfies a lot the design.
> chore: ui camera is now always an overlay

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/IPrivateChatComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Friends/FriendEntry.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/PrivateChatHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/PrivateChatWindowMock.cs
There used to be a feature that when a friend was online, their status would be reported as well as its whereabouts and it was possible to jump to the position of that user. However as of today, it seems this is not longer possible:
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/join-feature-not-working-as-expected
1. Check friends that are online
1. Verify that the position and realm are visible in the friends list or the chat window
1. Verify it's possible to jump in the user by clicking the join button
> fix: Join feature doesn't work correctly

- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarSystemUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/IWearableLoader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/BodyShapeLoader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/Loader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/WearableLoader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/CharacterPreview.prefab
When using an Avatar with a Hologram all the renderers (including the Bodyshape's ones) point its bones to the BaseAvatar (the hologram). This is done to have smooth transitions from hologram to real avatar.
The bug goes as follow:
- Spawn in Genesis Plaza with more people
- Avatars with holograms are rendered
- Bunch of bodyshapes are pointing its bones to their corresponding BaseAvatar
- You teleport to another location,  avatars from other people are disposed (renderers are returned to the library to be reused)
- Open Backpack
- CharacterPreview loads an AvatarWithoutHologram, that means using the upperbody as the bones orchestator)
- Most wearables are retrieved from the library because they are already loaded, bodyshape included.
- All wearables use the upperbody bones to animate …
> fix: invisible character preview

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
Passport was not set in camera space canvas
Open the passport and then other UI's on top, it should be behind them.
> chore: set passport's canvas in camera space

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapUserIcon.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapUtils.cs
Player positions in minimap was being clamped into integers.
Go to a crowded place, player position should correspond to its representation in the minimap
> fix: player positions in minimap is not unclamped

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
It fixes a layout issue that was causing the chat messages to be trimmed when they are too long.
1. Open any chat window
2. Write very long messages
3. The scroll should behave correctly
> fix: layout updating when long messages are added to the chat

- unity-renderer/Assets/Prefabs/FPSPanel.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
Some items inside the DebugView prefab were not in the UI Layer.
Additionally the camera was not being used for the TMPro utility to check the mouse over the link
Using `DEBUG_MODE` should make the FPS panel visible.
Hovering coordinates in chat should show a toast
Clicking coordinates in chat should open a popup.
> fix: debug mode and chat coords are fixed

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/DefaultChatEntryShould.cs
Fixes a crash when you write special messages, for example: `-100,-100` or `-ewoifjweo -ewfew-ff fweowfj`.
1. Open the nearby channel window and write anything that starts with `-` character, for example `-30,-30`
2. Open the start menu, go to places and then jumpin to Wondermine
3. The application should not freeze
> fix: special characters in chat crash

- unity-renderer/Assets/Scenes/InitialScene.unity
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/Resources/UIText.prefab
- Fixed UIText not being culled when its alpha or its alpha group parents had 0 alpha.
- Fixed TextShapes being rendered when their alpha or size was <= 0
Closes #2717 
PROD ( ICE Poker - The Stronghold ) [ NO AVATARS ]
```
PerformanceMeter - Data report step 2 - Processed values:
* PERFORMANCE SCORE (0-100) -> 40
* lowest frame time -> 41.8ms
* average frame time -> 51.9ms
* highest frame time -> 100.0ms
* 1 percentile frame time -> 43.7ms
* 50 percentile frame time -> 50.2ms
* 99 percentile frame time -> 100.0ms
* error percentage -> ±1.4%
* total hiccups (>0.05ms frames) -> 296 (51.21% of frames were hiccups)
* total hiccups time (seconds) -> 16.60201
* total frames -> 578
* total frames time (seconds) -> 30.00612
```
THIS PR
```
* PERFORMANCE SCORE (0-100) -> 64
* lowest frame time -> …
```
> fix: UIText and TextShapes being rendered when not visible 

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Textures/WalletIllustration.png
Update of the wallet image for the skins and collectibles sections of the backpack when a player enters as a guest. Now it includes Coinbase as an option.
1. Enter as a Guest here: https://play.decentraland.zone/?renderer-branch=style/ConnectWalletImage
2. Open the backpack in the sections skins and collectibles to see the new image.
> style: coinbase added on the wallet illustration

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Animator/Handler/AnimatorComponentHandler.cs
This PR fixes a situation where if you have more than 1 animator and changes the animation of 1 of them, it is not working
1.- Download the scene https://github.com/decentraland/ecs7-template (recommended branch: feat/cube-spawner)
2.- Follow the instructions and start the scene with npm start
3.- Use this URL: http://127.0.0.1:8000/?position=0%2C0&ENABLE_ECS7=&renderer-branch=fix/animator-component&kernel-branch=main&SCENE_DEBUG_PANEL=&realm=v1%7E127.0.0.1%3A8000
4.- Change the code to see if everything works as expected
> fix: animator bug sometimes not playing ECS 7

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/Resources/ControlsHUD.prefab
The emotes icon in the Controls HUD was missed:
It has been restored:
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/emotes-missing-sprite-in-controls-hud
2. Press C to open the Controls HUD.
3. Notice the emotes icon is visible.
> fix: Missing sprite in Controls panel HUD

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarModifierArea/Handler/AvatarModifierAreaComponentHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Utils/ECSAvatarUtils.cs
This fixes the Avatar modifier area component for ECS 7
1.- Download the scene https://github.com/decentraland/ecs7-template (recommended branch: feat/cube-spawner)
2.- Follow the instructions and install this SDK version `npm install "https://sdk-team-cdn.decentraland.org/@dcl/js-sdk-toolchain/branch/feat/readd-avatar-modifier-area/dcl-sdk-7.0.0-2718342601.commit-6cf89b2.tgz"`
3.- start the scene with npm start
4.- Use this URL: http://127.0.0.1:8000/?position=0%2C0&ENABLE_ECS7&renderer-branch=fix/avatar-modifier-area&kernel-branch=main&SCENE_DEBUG_PANEL=&realm=v1%7E127.0.0.1%3A8000
5.- Change the code to see if everything works as expected
> fix: avatar modifier area for ECS7

- .github/auto_assign_config.yml
QA team has been added as reviewers for the auto-assign tool.
Also added a new label to exclude the auto-assign tool
> chore: add QA to reviewers and exclussion label

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateTPS.cs
Changes the default vector for the avatar rotation after teleport. It was set to `Vector3.zero`, which caused Unity to spam a warning into the Console. Now it's set to a default value of `Vector.forward`; so the default-looking direction for every scene will be North.
1. Go to 102,-32. Check that your avatar started looking **North**, and no _Look rotation viewing vector is zero_ warning is logged into the console. 
2.  Go to -74,53. Check that your avatar started looking **West**, and no _Look rotation viewing vector is zero_ warning is logged into the console. Move around a little bit to change the character starting looking direction
1. Go back to 102,-32. Check that your avatar started looking **North**, and no _Look rotation viewing vector is zero_ warning is logged into the console. …
> fix: Remove "Look rotation" warning

- unity-renderer/Assets/ABConverter/AssetBundleMetadata/AssetBundleMetrics.cs
- unity-renderer/Assets/ABConverter/AssetBundleMetadata/AssetBundleMetrics.cs.meta
- unity-renderer/Assets/ABConverter/Core.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/Asset_AB.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
Fixes #2124 
Added metrics generation file for ABs to have memory scoring for GLTFs and Animation Clips.
Cannot really be tested, just do a smoke run with and without Asset Bundles, everything should be fine.
> chore: add memory metrics to ab

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/VoiceChatHUD/VoiceChatWindowController.cs
Change this text by `No one else is here`:
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/change-info-message-in-the-voice-chat-bar-
2. Go to any place woth nobody around.
3. Notice that the message in the Voice Chat bar is `No one else is here`.
> fix: Change message of the Voice Chat bar when no one else is in your area

- unity-renderer/Assets/DCLPlugins/UIRefresherPlugin/UIRefresherController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIShape.cs
Fixes hiccups included in #2756 due to an error while refactoring.
Go to [ICE Poker](https://play.decentraland.org/?renderer-branch=fix/uishape-regression&realm=dg&position=-100%2C126)
The scene should load more smoothly than in #2786
> fix: uishape performance regression

- .github/auto_assign_config.yml
Added Not QA Needed label for auto assign github action to follow the agreed process.
> chore: add "Not QA Needed" exclusion label to auto-assign action

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/NotificationBadge_FriendsRequestTab.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- The notification count from friend requests tab is showing the received friend request count.
- GetFriends & GetFriendRequests are only called once
- Replaced general channel id for nearby
1. Set the custom test url: https://play.decentraland.zone/?kernel-branch=feat/add-friends-lazy-load&
2. Open friends and check the number on the requests tab, it should be the same as the taskbar
3. Check that nearby channel keeps working as expected and is listed correctly
4. Check that friends are loaded correctly
> fix: changes noted from review 06082022

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CollapsableChatSearchListComponentView.cs
- unity-renderer/Assets/UIComponents/Scripts/Components/CollapsableSortedList/CollapsableSortedListComponentView.cs
Correctly updates the empty state container when searching conversations.
1. Open the conversation list (click on chat button, from nearby click back)
2. Search for any text
3. If no results are retrieved then a label should be shown indicating you have no results
4. If results are found, the label should not be shown, only the result entries (direct conversations or nearby channel)
> fix: conversation list empty state when searching

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Scripts/UserContextMenu.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Adds a data structure for the payloads when reporting players and scenes.
The reported scene id has been replaced for coordinates: `x,y`
1. You cannot report a scene with the current ui
2. Click over other player, then open the passport and click the report button
> fix: added payloads for reporting scenes and players

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
Fixes the performance overhead of the AvatarAnimatorLegacy, it has zero allocations now.
Fixes #2714 
The performance improvement is 0.7 ms per frame so it's not that much noticeable. But it adds up.
Check that running, walking, jumping and falling animate like before.
> fix: avatar animator legacy overhead

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarReporterController/Implementation/AvatarReporterController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarReporterController/Tests/AvatarReporterControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/DebugBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IWorldState.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/WorldState.cs
`AvatarReporterController.ReportAvatarPosition` had a small overhead and allocations, those are gone.
Fixes #2701 
Scenes with `onEnterSceneObservable` and `onLeaveSceneObservable` should work properly. 
67 players (-100,126 ) 30 seconds WITHOUT UI (pressing U)
```
* PERFORMANCE SCORE (0-100) -> 10
* lowest frame time -> 61.7ms
* average frame time -> 77.4ms
* highest frame time -> 100.0ms
* 1 percentile frame time -> 64.3ms
* 50 percentile frame time -> 74.4ms
* 99 percentile frame time -> 100.0ms
* error percentage -> ±1.3%
* total hiccups (>0.05ms frames) -> 387 (99.74% of frames were hiccups)
* total hiccups time (seconds) -> 29.94901
* total frames -> 388
* total frames time (seconds) -> 30.0292 …
```
> fix: reduced ReportAvatarPosition overhead

- unity-renderer/Assets/DCLPlugins/AvatarModifierAreaFeedbackPlugin/AvatarModifierAreaFeedbackPlugin.asmdef
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarModifierArea/Utils.meta
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarModifierArea/Utils/AvatarModifierAreaID.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarModifierArea/Utils/AvatarModifierAreaID.cs.meta
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarModifierArea/Utils/AvatarModifierAreaUtils.asmdef
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarModifierArea/Utils/AvatarModifierAreaUtils.asmdef.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/AvatarModifierAreaFeedbackHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Scripts/AvatarModifierAreaFeedbackController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Scripts/AvatarModifierAreaFeedbackView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Scripts/Interfaces/IAvatarModifierAreaFeedbackView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Test/AvatarModifierAreaFeedbackControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Test/AvatarModifierAreaFeedbackTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Test/AvatarModifierAreaFeedbackViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
Overlapping modifier areas generates a wrong behavior. Areas turn on and off the modifier even though the user is still inside at least one of the areas. This implementation solves the overlapping issue.
More info here: https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1660333541371069
1. Go to https://play.decentraland.zone/?renderer-branch=fix/overlap-avatar-modifier-areas&NETWORK=mainnet&position=-74,-99. There are some overlapping areas deployed in that scene, same as in this video
https://user-images.githubusercontent.com/1999557/185384451-578b9f31-bb6c-40b5-8c73-165b46fa495c.mp4
2. Check that your character is modified correctly
> fix: support for overlapping avatar modifier areas

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- removes direct messages entries when the friendship updates
- always allocates the last message received no matter if the profile exists or not
- removed deprecated filters for showing direct messages
- added test coverage
1. Go to the conversation list and check everything is listed correctly
2. Remove any friend that has a direct message with you
3. The friend should be removed from the list
4. Check that the last message is correctly display in the entry, when you receive one
> fix: direct message listing fixes

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/FeatureFlags/Data/FeatureFlag.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
Brought back flag and functionality deleted on commit #2876. The flag is Unleash is called [explorer-use_gpu_only_meshes](https://features.decentraland.systems/#/features/strategies/explorer-ab_use_gpu_only_meshes)
> chore: implement use-gpu-only-meshes flag

- docs/ecs7-component-creation.md
We are creating a new site for docs in Decentraland. This site will includes all documentation for players, content creator and for contributors to the project.
The unity renderer repo is the biggest repo of Decentraland and needs to be documented in the contributor part. This is the first iteration of adding documentation from the repo. After that, we are going to add the rest of the documentation
This PR adds the correct frontmatter metadata on top otherwise it won't appear on the docs site.
This metadata allows the docs site to recognize this document as a part of the documentation site
It can't be tested per see. You can see the changes in the file. After this PR and [this](https://github.com/decentraland/technical-documentation/pull/55) PR are merged. We will be able to see them in …
> docs: add missing frontmatter to ecs7-component-creation.md

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemSelector.cs
Fixes [#2808](https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/2808)
The scroll bar was not being displayed the first time correctly because the canvas update with its corresponding ContentSizeFitter was not being done unless the gameobject was active.
This PR fixes that by forcing the content canvas update on enabling the item selector.
0. Open https://play.decentraland.zone/?renderer-branch=fix/scroll-bar-not-displayed-in-backpack
1. Log into the game as a guest or through a wallet.
2. Wait for the game to load.
3. Make the resolution/screen size smaller, so that not all backpack elements can fit on the screen (not required if you have enough items in any section of the Head and Top tabs).
4. Enter the backpack.
5, Choose the Hair …
> fix: show scroll bar on first time opening wearable selection

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/AnchorPointsGetterHandlers/GetAnchorPointsHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarAttach/Tests/AvatarAttachHandlerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/AvatarAttach/Tests/AvatarAttachHandlerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/AvatarAttach/Tests/AvatarAttachPlayerHandlerShould.cs
player profile is resolved after the component is updated.
adding this component at the beginning of a portable experience won't attach the entity to the player since userId is empty.
we are hooking to the profile update to wait until is resolved before trying make the attachment
test link: https://play.decentraland.zone/?GLOBAL_PX=urn%3Adecentraland%3Aentity%3Abafkreidfs3xlfb6kkemmjn23qpg64qhghbghwafoa2uoi57izof5kf2nti%3FbaseUrl%3Dhttps%3A%2F%2Fsdk-content-server.decentraland.org%2Fipfs%2F&position=52,52&DEBUG_SCENE_LOG&renderer-branch=fix/avatar-attach-px
if you see a cube over your avatar head, then it's working :)
> fix: avatar attach component in portable experience

- unity-renderer/Assets/Scripts/MainScripts/DCL/Configuration/Configuration.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/TextureHelpers/TextureHelpers.cs
This PR moves two magic numbers used to set texture max size for GLTF and other textures to a new static class in Configuration script file, it also creates two other constants of same type to be used in the desktop repo
...
These changes should be tested in desktop repo together with desktop client changes. In order to test it you would have to make sure your desktop client package manager is using correct branch or local folder of unity-renderer repo.
> chore: move texture max size constants to configuration

- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
- unity-renderer/ProjectSettings/PackageManagerSettings.asset
Adding Animation Sequencer package for DOTween
https://github.com/brunomikoski/Animation-Sequencer
Latest version is `0.3.9`, however, it's not compiling with Unity `2020.3`, and we have to use `0.3.8` for now.
I have created an [issue](https://github.com/brunomikoski/Animation-Sequencer/issues/53), and we can update after the plugin owner makes a change or we upgrade to 2021.
> chore: add Animations Sequencer for DOTween

- unity-renderer/Assets/DCLPlugins/BuilderInWorld/Tests/BIWEntityHandlerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
- unity-renderer/Assets/Tutorial/Tests/TutorialControllerShould.cs
Added persistent scenes flag check to avoid running scene boundaries checks for entities that come from a persistent (AKA global) scene, like the global scene for avatar shapes or the scene of every portable experience.
1. Check that the already-solved https://github.com/decentraland/unity-renderer/pull/2811 issue hasn't reappeared: 
In [production](https://play.decentraland.org/?position=90%2C-143) there are invisible colliders on the empty parcels at the left of the affected scene (90, -143).
In [that PR's build](https://play.decentraland.zone/?renderer-branch=fix/SceneBoundsCheckPersistentScenes&position=90%2C-143) those colliders are disabled as they are detected as part of the mesh of the entity that contains them and that is detected as outside the scene boundaries.
2. Check that …
> fix: scene bounds check persistent scenes

- unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationsTracker.cs
- unity-renderer/Assets/DCLPlugins/EquippedEmotes/EquippedEmotesPlugin.cs
- unity-renderer/Assets/DCLServices/EmotesCatalog/EmotesCatalogService.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarCurator.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/Loader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/WearableItemResolver.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BotsController/BotsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/EmotesCustomization/EmotesCustomizationComponentControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmotesWheelHUD/EmotesWheelController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Emotes.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_EmotesCustomization.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
There were issues in changing nft emotes structure so after discussion with Mendez we decided to use different approach: make only one version for the Renderer emote structure but convert structures for old users in runtime.
To test this change it is very important to test in both old users and new users. For old users we need to check if their old NFT emotes will be present. Old user is considered anyone who created his profile and added some NFT emotes and/or other wearables before this change was in the Renderer.
> nft emotes different approach to new structure

- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/DCL.Plugins.UUIDEventComponents.asmdef
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/DCL.Components.Events.asmdef
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/OnPointerEvent.cs
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/OnPointerEventColliders.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/Tests/AudioTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTextureShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_SceneBoundariesChecker.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_SceneBoundariesChecker_Extensions.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
- unity-renderer/Assets/Scripts/Tests/IntegrationTestSuite_Legacy.cs
When an entity with a shape is outside the scene boundaries, its renderers are disabled. If at that moment an OnPointerEvent component is attached to the entity, it will have its onpointer event colliders disabled and they'll never be enabled when the entity re-enters the scene boundaries and gets re-evaluated.
That happens because during onpointer vent colliders initialization, the colliders are initialized as enabled/disabled based on the entity renderers enabled value.
- Implemented 'IOutOfSceneBoundariesHandler' interface in OnPointerEvent to be called when the pertinent scene changes its 'inside scene boundaries' state.
- Added pointer event colliders update based on renderers state after scene boundaries state change event
- Implemented `UnloadAll()` method in old …
> fix: onpointerevent colliders reset on scene bounds check

- unity-renderer/ProjectSettings/InputManager.asset
This PR removing joystick axes from Unity Input Manager since this repo is not supposed to support joysticks and gamepads anyway but there is a high probability that some per-user bugs are caused by this setting being enabled in the Input Manager
Just test the input.
> input manager joystick axes removed

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/Channel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChannelSearchResultsPayload.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChannelSearchResultsPayload.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChatController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Tests/Helpers/ChatController_Mock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatEntryModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/SearchChannelsWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/CollapsableChatSearchListComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/CreateChannelWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChannelEntryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatChannelComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatEntryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/SearchChannelsWindowComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/SearchChannelsWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Changes the way pagination works when searching channels. It is required a `string paginationToken` instead of a `skip` parameter.
1. Open the channel browser
2. All channels should be loaded
3. Scroll down to load more
4. Use the searchbar and type a name
> feat: channels search pagination by token

- README.md
Lately, Decentraland code implemented "SystemInfo.supportsStoreAndResolveAction" and this field does not exist yet in the listed version in the README. This PR only changes the listed version to the current required one.
> docs: update README required Unity version

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
This PR fixes analytics of playing an emote for new emotes. If the emote is not found in the collection of wearables in that case it will be found in the new emotes catalog.
Closes #2963 
Check if analytics event actually coming to our analytics when you play a new custom NFT emote.
> fix: emotes play analytics fixed for new emotes

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- Fixed avatar with no eyes due to a floating point precision error.
- Fixed hologram not being visible while avatar was being loaded
Go to wondermine and inspect all possible avatars, they should have eyes as expected.
> hotfix 20220917

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmotesCustomizationSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmotesCustomizationComponentController.cs
Fixes https://github.com/decentraland/unity-renderer/issues/3051
ItemInfoShortcutInfo gameObject was disabled insiede EmotesCustomizationSection.prefab to hide non-functional button (until the time implementation for it will be ready).
1. Open Backpack->Emotes UI
2. Observe no `+` `ShowInfo ` button to be displayed below `E` `EQUIP / UNEQUIP` button
> fix: non-functional showInfo button be shown in backack emotes 

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesAndEventsSectionComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentViewTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ShowHideAnimator/ShowHideAnimator.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMapLoadingLogo.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMapLoadingLogo.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Resources/NavMap.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/Variables/BaseVariable.cs
- unity-renderer/Assets/UIComponents/Scripts/Components/SectionSelector/SectionToggle.cs
Fixes https://github.com/decentraland/unity-renderer/issues/2071
- Add a small controller to disable/enable white background when loading NavMap
- Refactored ExploreV2Controller/View to reduce duplication of the code
- Move responsibility of changing Model from ExploreV2View to ExploreV2Controller
Test 1
1. Open NavMap via shortcut and observe that it loads without the white splash
2. Switch between other tabs (Explore, Backpack, Settings...) and NavMap via UI or Shorcuts and observe no white splash when opening/closing NavMap
Test 2
1. Open NavMap
2. Close ExploreUI via Close button on the right hand side
3. Open Settings via shortcut (P)
4. Observe that Settings are opening on the white background (and you don't see 3d world behind it) …
> Fix: gray screen flash on nav map

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmoteSlotCard.prefab
When reducing graphics quality some of the separators of the emotes in the backpack were smaller than 0.5px, as a result they were not rendered.
I increased slightly the size making sure they are above the threshold at all times.
> Emotes separation bar dissappears on lower resolutions

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.cs
Fixes https://github.com/decentraland/unity-renderer/issues/1807
Changes default port for WebSocketCommunication from 5000 to 7666.
Related changes for the definitions repo are in this [PR](https://github.com/decentraland/definitions/pull/88)
1. Starting from Desktop client should be able to connect and work as usual
2. Starting from Unity Editor should be able to connect and work as usual
> feat: change default (debug) port from 5000 to 7666

- .circleci/config.yml
The code for the renderer protocol and the ecs7 components is now generated in the CI.
It will replace the existing pushed code.
Note: Add just 7 seconds to the CI
The CI will throw an error if there is a misuse of the protocol generation.
> chore: CI code generation of renderer protocol and ecs7 components

- unity-renderer/Assets/DCLServices/ApplicationFocus.meta
- unity-renderer/Assets/DCLServices/ApplicationFocus/ApplicationFocusService.asmdef
- unity-renderer/Assets/DCLServices/ApplicationFocus/ApplicationFocusService.asmdef.meta
- unity-renderer/Assets/DCLServices/ApplicationFocus/ApplicationFocusService.cs
- unity-renderer/Assets/DCLServices/ApplicationFocus/ApplicationFocusService.cs.meta
- unity-renderer/Assets/DCLServices/ApplicationFocus/AssemblyInfo.cs
- unity-renderer/Assets/DCLServices/ApplicationFocus/AssemblyInfo.cs.meta
- unity-renderer/Assets/DCLServices/ApplicationFocus/IApplicationFocusService.cs
- unity-renderer/Assets/DCLServices/ApplicationFocus/IApplicationFocusService.cs.meta
- unity-renderer/Assets/DCLServices/ApplicationFocus/Tests.meta
- unity-renderer/Assets/DCLServices/ApplicationFocus/Tests/ApplicationFocusServiceShould.cs
- unity-renderer/Assets/DCLServices/ApplicationFocus/Tests/ApplicationFocusServiceShould.cs.meta
- unity-renderer/Assets/DCLServices/ApplicationFocus/Tests/ApplicationFocusServiceTests.asmdef
- unity-renderer/Assets/DCLServices/ApplicationFocus/Tests/ApplicationFocusServiceTests.asmdef.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/AvatarEditorHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
Fixes #2996. If we assume that the player went to the marketplace to buy a wearable, we force an update of the owned wearables when DCL lost focus
1. Follow this guide to get Polygon money into your GOERLI account (https://www.notion.so/decentraland/Set-up-a-wallet-for-testing-e23afcc6c74d49009781667dee493822)
2. Open DCL and open the backpack in GOERLI. You should not have any collectibles. Go to `market.decentraland.zone `(IMPORTANT, use zone as market address)
3. Buy this hat https://market.decentraland.zone/contracts/0xc9b1cd286279dca22ff22abb9ebc24a5f15fa24c/tokens/1 (Looks like the only wearable that currently works)
4. Go back to DCL. Check that the hat appears
> fix: update owned wearables after losing focus

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
- unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_LockTheCursor.cs
- unity-renderer/Assets/Tutorial/Scripts/TutorialStep.cs
- unity-renderer/Assets/Tutorial/Scripts/TutorialTeacher.cs
- unity-renderer/ProjectSettings/QualitySettings.asset
Fixes #1794 
When the prefabs containing character animation or tutorial robot are hidden or the specific element containing the animations is hidden, the animations stops. 
QA
once we stop rendering an avatar or the tutorial robot, the preview should stop being animated.
PR in progress, more modifications to catch specific moments when we should stop animations might arise following tests and investigations.
> Stop animations when character and tutorial robot are not rendered

- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/PointerEventsController/PointerEventsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_ECS7.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/Extensions/DataStore_ECS7_Extensions.cs
removed deprecated code used for ECS7 input
https://play.decentraland.zone/?renderer-branch=chore/ecs7-remove-deprecated-input-code
go to genesis plaza, click on events or places pilars.
input should behave as expected.
> chore: ECS7 remove deprecated input code

- unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs
- unity-renderer/Assets/Tutorial/Scripts/TutorialController.cs
fixes #3087 
This PR should avoid the tutorial from being fired outside genesis plaza.
QA
In order to check, reproduce the steps described in the linked issue, the tutorial should not be shown anymore.
> fix: Welcome to Genesis plaza should not be shown outside of it

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelLeaveErrorModal.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChannelLeaveErrorModal.prefab.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowComponentView.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowController.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelLeaveErrorWindowPlugin.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelLeaveErrorWindowView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelLeaveErrorWindowView.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/LeaveChannelConfirmationWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLeaveErrorWindowComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLeaveErrorWindowComponentViewShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLeaveErrorWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelLeaveErrorWindowControllerShould.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
Adds a new modal that is displayed whenever there is an error to leave a channel.
1. Easiest way to test is to force `ChatController.LeaveChannel` method to trigger `OnChannelLeaveError` event
2. Open the conversation list
3. Leave any channel
4. A modal should be displayed with the option to close or retry
> feat: leave channel error modal

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DateSeparatorEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/DefaultChatEntryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Utils/CoordinateUtils.cs
Add links for usernames in chat messages. This fixes the issue that the contextual menu was being opened when clicking on a channel link. Also the scene coordinates links got fixes, since they were dissapearing after hovering with the mouse.
1. Go to any public chat
2. Receive a message with coordinates and channel links, for example: "100,100 hello #channel"
3. Click on the user name, it should display the user contextual menu
4. Click on the scene coordinate, it should display the jumpin modal
5. Click on the channel link, it should display the join channel modal
6. None of the cases should overlap between them
> fix: username links in chat

- .github/auto_assign_config.yml
Updating auto_assign_config.yml to include @Antivortex and @popuz as reviewers.
Above GitHub users will be used in the lottery system for auto review
> chore: add extra reviewers

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_HUDs.cs
When we have a chat open, avoids showing top notifications coming from that chat
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/notification-same-panel&kernel-branch=fix/channels-profiles
2. Open different chats (nearby, channel, private)
3. Receive messages in the open chat
4. Verify that the top notification doesn't show the new message in the opened chat
> Fix: avoid showing top notification when coming from open chat

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimationEventHandler.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionClap.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionHeart.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionHohoho.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionMoney.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/Resources/Prefabs/AvatarExpressionSnowflakes.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/StickersController/StickersController.cs
Fixes #2961 
- Emote stickers should now follow the user.
- Check that every emote with particles (mostly the base ones, clap, kiss, ho ho ho...) show the correct particle.
> chore: stickers in local space

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/DestroyParticlesOnFinish.cs
fixes #3168 
Destroy particles on finish now will:
- Remove itself as a component if no particles are attached, (the variable is private and can not be updated later)
- Sectioned the calls for fixed update based on a random index for each component, as there are 10 possible indexes, performance cost should cost about 10% of the previous one.
- No behavior changes on the particles should be observable, particles should keep acting exactly the same as in production.
> Destroy particles on finish refactor

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmotesCustomizationSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/EmotesCustomization/EmoteSlotSelectorComponentView.cs
This PR fixes null reference exception happening in GetAllSlots method of EmoteSlotSelectorComponentView class for a user who has custom wearables. The exception happens during emote customization UI initialization, field emotesSlots (a serialized field of EmoteSlotSelectorComponentView) is null on that frame. This field is accessed on the same frame when game object of EmotesCustomizationSection is instantiated and the field is part of nested prefab EmoteSlotSelector but accessed with a chain of public methods before nested prefab EmoteSlotSelector is fully initialized with its instantiated parent.
Solution is to unpack EmoteSlotSelector prefab and make it part of EmotesCustomizationSection. This is the only usage of this nested prefab.
Test everything regarding emotes and wearables:
If …
> fix: nested prefab null reference exception fix

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/PlayerName.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/Tests/PlayerNameShould.cs
Fixes #3144
Fixes the profanity filter disabled but not affecting the head floating names on avatars.
Log in with two instances, disable the profanity filter on one account, and set a swear word as a name on the other.
> Fix: profanity filter not disabled on name

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
* Go to https://play.decentraland.zone/?NETWORK=goerli&ENABLE_NOTIFICATION_CHAT=&renderer-branch=fix/join-channel-notific&kernel-branch=fix%2Fchannels-profiles&realm=artemis&position=99%2C99
* Join a channel
* Receive notifications from that channel
* Leave the channel
* Click on the notification and check if it joins back in the channel
> Fix: fixed clicking on notification redirecting to non joined channel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
New rules has been applied to messages to be considered spam:
- time between messages lowered to 1000 milliseconds
- at least 10 messages
- 3 minutes of mute
A message has been added in the scroll whenever you try to send a message while you are muted.
1. Open #nearby channel
2. Send messages very fast until you are considered spam. A system message should be received.
3. Open any channel window
4. Send messages very fast until you are considered spam. A system message should be received.
5. Open any private chat window
6. Send messages very fast until you are considered spam. A system message should be received.
> feat: message feedback whenever you are muted due spam filtering

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Channels/ChatChannelsControllerMock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChatController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/Tests/Helpers/ChatController_Mock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/Tests/JoinChannelComponentControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_Channels.cs
If you click on a link of a channel where you are already joined, it should redirect to this channel instead of trying to join it.
https://play.decentraland.zone/?renderer-branch=fix/open-joined-channels-from-link&kernel-branch=feat/feature-flag-for-channels
> fix: [SUB-BRANCH] Open already joined channels from link

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChannelsFeatureFlagService.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/IChannelsFeatureFlagService.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/JoinChannelModalPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/JoinChannelHUD/Tests/JoinChannelHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Environment/Factories/ServiceLocatorFactory/ServiceLocatorFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/ChannelLinkDetector.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/UIHelpers.asmdef
Channel links (like #channel-example) are disabled if the user is not able to create channels through feature flag.
1. Login with a user that is able to create channels
2. Write #any-channel in chat
3. The channel link should work
4. Login with a user that is not able to create channels
5. Write #any-channel in chat
6. The channel link should not work
> feat: disable channel links if the user is not allowed to create channels

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/PlayerName.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/Tests/PlayerNameShould.cs
- unity-renderer/ProjectSettings/PackageManagerSettings.asset
fixes #3170 
Currently the alpha for the player name works in steps, this PR avoids recalculating new alpha values every frame if the alpha has not changed or has not been modified to a different step.
The only difference is the alpha will have a discrete amount of possible values instead of being a continuous one.
With this current PR the amount of steps is stored in the constant `ALPHA_STEPS`.
In order to get the discrete available values, these are all the values from 0 to 1 that are multiples of `1f / ALPHA_STEPS`
- The player name alpha should work very similar to dev / production, alpha values are as such: 0, 0.0625, 0.125... multiples of 0.0625 from 0 to 1
> refactor: Player name optimization

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
To avoid overwhelming the user with many unseen messages from channels, clear them at the start of the session for each channel joined.
1. Start receiving channel messages while online. Unseen message counter should go up.
2. Go offline
3. Receive more message in different channels
4. Go online
5. Go to the conversation list
6. The unseen message counter should be reset to 0 to each joined channel
> clear unseen messages at the start of the session for each joined channel

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
fixes #3077 
After sending a friend request, the profile was being uploaded with a null description, without a null checking, the description disappeared.
##QA
When you send a friend request through the passport (PlayerInfo in the code), the description should not disappear, should remain there.
> fix: Passport description disappears after friend request

- unity-renderer/Assets/Rendering/Culling/Interfaces/CullingControllerSettings.cs
- Reduced culling controller budget from 4 ms to 0.5 ms 
- Higher FPS
- More stable FPS (less fluctuations)
- When walking around genesis plaza or the world, some objects might appear in your face slower than before ( if they are already loaded ) 
position: 0,0 
realm: offline
wait a few seconds after everything loads and then go down the waterfall and run the tool for 30 secs
THIS PR
```
* PERFORMANCE SCORE (0-100) -> 94
* lowest frame time -> 31.8ms
* average frame time -> 37.1ms
* highest frame time -> 100.0ms
* 1 percentile frame time -> 32.7ms
* 50 percentile frame time -> 35.9ms
* 99 percentile frame time -> 51.4ms
* error percentage -> ±0.9%
* total hiccups (>0.05ms frames) -> 9 (1.11% of frames were hiccups)
* total hiccups time (seconds) -> 0.710701
* total frames -> 808
* total …
```
> test: reduce culling controller budget

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
We have a bug only the first time you click on the chat button in the taskbar, it opens the nearby channel instead of the conversation list. This is worst now that we have the toast for promoting channels. This change will force always to open the conversation list when clicking the chat buton in the taskbar.
1. Click the chat button in the taskbar
2. Should open the conversation list
3. Navigate between different chats: privates, channels and nearby
4. Press ENTER, it should open the last active chat window
5. Click the chat button in the taskbar, it should open the conversation list
> fix: chat taskbar navigation

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.jslib
- update video texture only when video frame is updated and not on browser frame update or Unity frame update
more details on [notion page](https://www.notion.so/decentraland/Video-Streaming-10-2022-5bd80fbea58e41d3a07793ba08565fda) 
1. Go to: https://play.decentraland.zone/?renderer-branch=feat%2Fvideo-streaming-performance&NETWORK=mainnet&position=-74%2C-99&CATALYST=peer-testing.decentraland.org&realm=peer-testing.decentraland.org&DEBUG_SCENE_LOG=&island=Idw
2. Run `/showfps` command in the chat
3. Press on the screen to play video and 
4. Observe it until it get sharp
5. Observe no fps drop at all (stable ~60 fps)
Additionally you can compare with https://play.decentraland.zone/?rNETWORK=mainnet&position=-74%2C-99&CATALYST=peer-testing.decentraland.org&realm=peer-testing.decentraland.or …
> feat: video streaming performance improvement

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Fixed https://github.com/decentraland/unity-renderer/issues/3409
The cause was an exception being thrown and the system falling apart.
This PR does not fix that exception. 
- `/goto -146, 67`
- Wait until everything loads
- Go to the Stadium model at the center of the room and click on the Stadium to teleport at it.
- /showfps
- Run over the people at the sides non-stop.
- After a few laps, the scene messages stop being processed due to an exception being thrown somewhere.
> fix: exception at SceneController stopping messaging processing flow

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/DefaultSettingsFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Tests/ProxySettingsRepositoryShould.cs
Set default scene load value to 2
1) Try a cache-free version. The default value for scene load radius should be 2
2) Open your normal DCL account. Go to the settings section. Press Reset All. Scene load radius should default to 2
> fix: setting default scene load value to 2

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
We were receiving huge hiccups when we opened a chat that contained messages with non-supported characteres for the font we use.
It seems the process to replace and calculate the size of all these texts is too expensive and it was provoking the hiccups. It happened specially when we had a lot of "corrupted" messages in the same chat.
As solution, before putting a text into the chat, we are identifying all the non-supported characters contained and replacing manually by the `?` character.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/replace-non-supported-characters-in-chats
2. Open a chat with non-supported characters.
3. Notice all these characters are replaced by the '?' character and you don't have any hiccup.
4. Check the CJK charactes keep working as before. …
> fix: Replace non supported characters in chats

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DCL.Runtime.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSComponentManagerLegacy/ECSComponentManagerLegacy.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ECSComponentManagerLegacy/ECSComponentsManagerLegacy.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
Nerfed the CPU budget of the SceneBoundsChecker from 20ms to 0.5ms
Nerfed the throttle ignore of the Entitities to check from Created/Updated to just Created.
Added feature flag `NERF_SBC`
use this link: https://play.decentraland.zone/?renderer-branch=test/nerf-sbc&ENABLE_NERF_SBC
- We should do a smoke test and report any anomaly caused by objects out of their scene boundaries not disappearing fast enough.
> chore: nerf SceneBoundsChecker budget usage and throttle skip

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/PoolManager.asmdef
Fixes #3417 
Move the pool container away from 0,0,0.
This will mitigate the issue with objects spawning in other scenes.
The issue described in the ticket shouldnt appear anymore.
> chore: move pool container out of sight

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Resources/_AvatarModifierAreaFeedbackHUD.prefab
Fixes [#3556](https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/3356)
1. Go to Wondermine (/goto -29,55). Go near the machine to hide the avatar
2. Press U to hide the whole UI. Check that the warning message is gone
> fix: hide Avatar Modifier UI on all UI Hide

- unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/ISocialAnalytics.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Analytics/SocialAnalytics/SocialAnalytics.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelHUDControllerShould.cs
Removes the sending of the metric on channel messages. Now it is handled by kernel in this pr: https://github.com/decentraland/kernel/pull/684
1. Open a channel
2. Send messages
3. Everything should keep working as expected
> fix: removal of send chat message to channel metric

- unity-renderer/Packages/packages-lock.json
Solves first issue with the black screen from [this list](https://github.com/decentraland/unity-renderer/issues/3399)
Updates to the package with the fix. 
Read more details about the fix [here](https://github.com/decentraland/webgl-ime-input/pull/2)
Teleport via chat `/goto` command 
1. to 100,100
2. back to 0,0
3. You should not see black screen blocking main loading screen
try to experiment with different teleportations like 150,150 -> 50,50
For QA: test other input fields in the DCL and verify that they are not affected by this change 
(like for inputing info and writing captchas. For example,  VIP area of the monkey quest in MVMF)
> fix: input field black screen overlay on chat /goto action

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Handler/ECSTransformHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Tests/ECSTransformHandlerShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Utils/ECSTransformUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/Variables/IBaseVariable.cs
*fix moving player's entity was not working for global scenes
*fix moving player to the same location as before, it was only working once
> fix: ECS7 move player entity

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmotesWheelHUD/EmotesWheelController.cs
Fix the next problem: Entering the menu while the emotes wheel is open results in the wheel getting stuck on the screen after the player leaves the menu. The player is able to use the wheel to play the emote animation, however, it is impossible to close the wheel.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/the-emotes-wheel-gets-stuck-on-the-main-screen
2. Load into the game as a guest or via a wallet.
3. Press 'B' to open the emotes wheel.
4. Press 'I' to enter the menu.
5. Return to the game by closing the menu.
6. Press the X icon near the wheel to exit the emotes wheel.
7. Notice the Emotes Wheel is closed and you can open it again pressing B or clicking in the taskbar button.
> fix: The emotes wheel gets stuck on the main screen

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/PlacesAndEventsSectionComponentView.cs
After closing the main menu, if we left open any of the Explore sub-sections (highlights, places or events) and we opened it again after 1 minute (this is the minimum time we have set for refreshing the data), the data inside of the sub-sections was not being refreshed.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/explore-sub-sections-are-not-being-refreshed-when-menu-opens
2. Open the main menu and go to the Explore section.
3. Select any of the 3 sub-sections.
4. Close the main menu and wait for 1min.
5. Open the main menu again.
6. Notice the sub-sections selected is the same as you left open before and its data refreshed.
> Explore sub-sections are not being refreshed when the main menu opens

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChannelMembersComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChannelMembersHUDControllerShould.cs
Data was being requested 2 times when the channel memebers list was open.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/channel-members-are-being-requested-twice
2. Open any channel.
3. Open the list of members.
3. Notice (from code) the `GetChannelMembers` message is being sent to kernel only once.
> fix: Channel members are being requested twice

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChannelsFeatureFlagService.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/ChannelLinkDetector.cs
Fixes a null reference exception when the channel link detector initializes before the user profile.
There is no specific steps. Its just a race condition that depends of the randomness of the load pipeline.
> fix: nullref exception when requesting allowance for creating channels from channel link detector

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/FPSDisplay/MetricsModules/MemoryJSDebugMetricModule.cs
Removed hardcoded number for the `jsHeapSizeLimit`.
When using /showfps command in chat and `jsHeapSizeLimit `should show 4GB instead of 2GB
> chore: updated hardcoded heap size limit

- unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/Tests.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
fixes #3374 
This could also be considered a fix, but, as this was not a bug, but an intended Update that might not be needed anymore, I considered it a refactor.
The call for update of the whole profile when showing an emote was causing a hiccup in performance, as emotes showing does not change the profile, this call has been removed.
Showing emotes should act exactly the same as in dev, no further modifications should be observable.
> refactor: UserProfileemotes caused a hiccup

- unity-renderer/Assets/DCLPlugins/ECS7/Systems/BillboardSystem/Tests.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
fixes #3342 
This issue was fixed by adding a Debug.Log... and then removing it.
Found something similar in the past, sometimes Unity seems to create a "cache" on how certain methods work, like a "precompilation status", once any change is done to that code directly, it updates and starts behaving as expected again.
For this issue, I don't know if the solution will just work on my end or on everyone else's to, let's see what QA finds.
In order to create a meaningful change so it can be committed, I removed the brackets of the single lined if.
Very weird behavior about Unity compilation, it works on my end now, but it could perfectly not work at all on others.
- Go to coordinates (-53, 1) approx.
- In the woods of a set of scenes called **Salmonomicon** you will be able to see a text over …
> fix: TextShape billboard

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/WorldChatWindowViewMock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/CollapsableDirectChatListComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IWorldChatWindowView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PrivateChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
The online status of the players was not visible in the chat window where we show the private conversations.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/player-online-status-is-not-visible-in-the-chat-window
2. Talk to a friend that is online
3. Check the Chat panel an see the online status of that player
> fix: Player online status is not visible in the Chat window

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/Resources/DebugSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/Resources/DebugView.prefab
Corrected the DebugView prefab to use the content size fitter according to recomendatios
1. Open the DebugView by using the command /showfps
2. Open and close the sections. They should respond accordingly
> fix: corrected use of CSF in debugView

- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/OpenSea/OpenSea.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/OpenSea/Types.cs
The owner field of the NFTs info has been deprecated for some time (https://decentralandteam.slack.com/archives/C02CNQT2D3M/p1669332675907709?thread_ts=1669322928.379659&cid=C02CNQT2D3M). 
Recently, this field started sending a null value, which caused the NFTs to not be displayed in explorer. This PR fixes that issue by removing the `owner` field references and replaced them with `top_ownerships.`
1. Go to the NFT gallery in Genesis Plaza and check that NFTs are displayed correctly
2. Go to Tru Band 26,-118 and check that NFTs are displayed correctly
> hotfix: nfts not displayed due to owner deprecated field

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PluginSystem/PluginSystemFactory.cs
Because we released the ECS7. There will be scenes with ECS7 in the World. So we must have ECS7
> feat: ecs7 plugin always enabled

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/DefaultSettingsFactory.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Tests/ProxySettingsRepositoryShould.cs
Reverting changes to default settings load radius from 2 to 4
Enter the world and go to the settings menu. Scene load radius should show 4.
> chore: set default scene radius back to 4

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/Resources/ControlsHUD.prefab
- unity-renderer/Assets/Textures/UI/ArrowOutline.png
- unity-renderer/Assets/Textures/UI/ArrowOutline.png.meta
- unity-renderer/Assets/Textures/UI/TexturesUI.spriteatlas
The key preview assets and the close button container have been updated. The builder key removed and the social keys reorganised that were misplaced. 
**Previous HUD**
**New HUD**
1. Go to: https://play.decentraland.zone/?renderer-branch=style/controls-hud-update
2. Press the key [C] and compare with the previous version that now the keys are well placed and that the builder reference doesn't exist anymore.
3. Check that the functionality open close pressing [C] works fine. Press [Esc] and the close button to close the panel too.
> style: controls screen update

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Fixes an error reported by serializing an infinity value when reporting video progress.
1. Go to: https://play.decentraland.org/?renderer-branch=hotfix/infinity-video-length
2. Go to `108,-120` and check that video is working OK and no errors are reported
> fix: avoid infinity values on VideoProgressEvent message

- unity-renderer/Assets/Rendering/Utils/ShaderUtils.cs
Fix some materials not being tagged as alpha tested properly.
You can test the pineapple hat here:  https://play.decentraland.zone/?renderer-branch=fix/alpha-cutoff-upgrade-2021&WITH_COLLECTIONS=fd575e10-5871-49e8-b625-caaf0a0f0deb&NETWORK=goerli
This PR changes the way we detect alphatested materials. A thoroughtful test is required to ensure no regressions in how the world looks.
Test in a default WebGL environment (Asset Bundles enabled) and take a look at wearables and assets in general to spot differences with production.
> fix: materials in geometry render queue sometimes have cutoff

- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
Just changed the dependency with the old package name
> fix: gltfast importer wont work if the package name changes

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmotesWheelHUD/EmotesWheelController.cs
Fixes [#3737](https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/3737)
- Added a safe copy from the list pool to iterate over
- Try to play around with Emotes Wheel
- Keep it open long enough to receive your own profile update
- There should be no exceptions mentioned in the ticket
- The rest of behavior should remain the same
> fix: make UpdateEmoteSlots iterate on a collection copy

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/EmotesService/EmotesRendererServiceImpl.cs
TriggerSelfUserExpression call is performing some accesses to unity members in a bg thread. 
Go to any scene with a self dancing event (like the ongoing event in -123,-126 ). You should dance properly.
> fix: TriggerSelfUserExpression executing in a background thread

- unity-renderer/Assets/DCLPlugins/ABDetectorPlugin/ABDetectorTracker.cs
fixes #3191 
A null reference exception was being fired when triggering again from outside initial range.
The renderers for the initial calculation where already destroyed but we were trying to access their materials, as the method for recalculation came after destroying the previous ones, all the process was blocked by the null ref.
Steps to reproduce the error in the issue:
- Log in with either a guest or a wallet account.
- Use the command "/detectabs" to turn on detection of AssetBundles for the nearby loaded tiles.
- Go beyond the range of the loaded tiles until you encounter non-highlighted tiles and walk into one such tile.
- When standing on a non-highlighted tile use the "/detectabs" command again.
- Notice new nearby tiles not being highlighted.
- Use any combination of …
> Fix: AssetBundles detection commands stop working when triggered again outside the initial range

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Removes the `DisablePassport() / EnablePassport()` calls from the `ApplyChanges()` update in AvatarShape. This was being called multiple times on a scene, which broke the functionality of the Hide Passport avatar modifier area.
1. Open two sessions of https://play.decentraland.zone/?NETWORK=mainnet&position=-119%2C100&CATALYST=peer-testing.decentraland.org&DEBUG_SCENE_LOG=&renderer-branch=fix%2Fremove-passport-change-on-apply-changes
2. As long as you have the warning message, passports should not be openable. 
3. Go outside the scene until the warning dissapears. Check that passports are openable
4. Go normally to https://play.decentraland.zone/?renderer-branch=fix/remove-passport-change-on-apply-changes. Check that passports are openable as usual …
> hotfix: Passport being enabled again on ApplyChanges of AvatarShape

- unity-renderer/Assets/DCLPlugins/MapTexturePlugin/MapTexturePlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/DCLWebSocketService.cs
Fixes
```
Texture creation failed. 'ETC2_RGBA8' is not supported on this platform. Use 'SystemInfo.SupportsTextureFormat' C# API to check format support.
NullReferenceException
at (wrapper managed-to-native) UnityEngine.Texture.set_filterMode(UnityEngine.Texture,UnityEngine.FilterMode)
at MapTexturePlugin.DownloadTexture (System.String url, BaseVariable`1[T] textureVariable, System.Threading.CancellationToken ct) [0x000b7] in <e20afafb71674baaa3ffc73363f12a8c>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) …
```
> fix: try to cope with desktop native crashes on quit

- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Changes the message ReportAvatarFatalError sends from a string to a json
> fix: ReportAvatarFatalError needs to send a json

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Scripts/AvatarModifierAreaFeedbackView.cs
Signed-off-by: Esteban Ordano <esteban@decentraland.org>
...
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/typo-disabled
2. Go in a passport disabled area
3. Verify that the message displayed is `Your passport is disabled for other players`
> fix: Typo on "disable for other users"

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/FriendEntry.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/FriendsHUD.prefab
This PR fix the next issues:
Online friend
Offline friend
Go to https://play.decentraland.org/?renderer-branch=feat/friends-ui-polish and verify that all the issues above are fixed.
> feat: friends ui polish

- unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/ComponentCrdtWriteSystem.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ComponentCrdtWriteSystem/Tests/ComponentCrdtWriteSystemShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneController.cs
after hot-reloading a scene renderer wasn't sending messages back to the scene any more due to an exception
> fix: sdk7 hotreload

- unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7HotReload.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7Plugin.Tests.asmdef
related to fix: https://github.com/decentraland/unity-renderer/pull/3870
test should fail before merging that fix but pass after it is merged
* fix test to be able to catch more errors, since hot-reload wasn't working properly and test wasn't failing as it should
> fix: sdk7 hotreload test

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShape.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/Resources/NewAvatarShape.prefab
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/InteractionHoverCanvas/InteractionHoverCanvasController.cs
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/Interfaces/EventsInterfaces.cs
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/PointerEventsController/PointerEventsController.cs
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/PointerEventsController/PointerHoverController.cs
- unity-renderer/Assets/DCLPlugins/UUIDEventComponentsPlugin/UUIDComponent/PointerEventsController/PointerHoverController.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarOnPointerDown/AvatarOnPointerDown.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarOnPointerDown/AvatarOutlineOnHoverEvent.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarOnPointerDown/AvatarOutlineOnHoverEvent.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
Closes #3859
**Definition of problem:**
Raycasting for passport is limited by range, while raycasting for outlining is unlimited. But they both were handled by a single piece of code that was very coupled. 
**Approach**
Detach avatar outlining from other functionality.
**Solution**
`PointerEventsController` is junk and without refactoring, it was impossible to approach properly. I had to extract all the functionality related to hovering to a separate class:
- The logic there was unclear so I modified it to be more consistent
- I tried to preserve the previous behavior
- Add an independent control of hovering so now there can be different `IPointerEvent`s with completely independent logic on the same object, and it will work correctly.
- It allowed me to introduce …
> Fix: incorrect avatar raycasting

- unity-renderer/.editorconfig
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2ComponentRealmsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2ComponentRealmsController.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/IExploreV2MenuComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/IExploreV2MenuComponentView.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Tests/ExploreV2MenuComponentControllerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/ThumbnailsManager/ThumbnailsManager.cs
- unity-renderer/Assets/UIComponents/Scripts/Components/SectionSelector/SectionToggle.cs
- unity-renderer/unity-renderer.sln.DotSettings
Closes #3030 
Opening or switching **ExploreV2Menu** sections from UI toggle or via keyboard shortcut was triggering `OnSectionOpen` event of `ExploreV2MenuComponentView` several times in one frame. Real problem is the chain calls between View and Controller for opening section task. That should be treated separately as a task of bigger refactoring of this pair (with more clear separation of responsibilities).
- To eliminate event to be called several time per frame I added a simple lock variable `isOpeningSectionThisFrame `(line 39 in `ExploreV2MenuComponentView`) and a coroutine `ResetSectionOpenLock()` (line 164) which updates it in one frame after a call (they used inside a logic of `OnSectionSelected` function).
- Add checks of variables change to apply it only if values changes - …
> Chore: double call in explore v2 on select

- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMapLoadingLogo.cs
We have many access violation errors on destroy when disposing, these fix two that I found for now. I imagine the common singleton pattern that we are using can cause this quite often if the singleton is destroyed first before any registered delegate attempts to unregister itself from the object.
> Null check before delegate unregister

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarShape/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/Interface/IPlayerName.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/PlayerName.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/Resources/PlayerName.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/Tests/PlayerNameShould.cs
`Closes #3627`
Adds a new color scheme for avatar name tags depending if they are guests, web3 or claimed.
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/avatar-name-colors
2. Go to a crowded place
3. Spot users as guests, names should be greyed out
4. Spot users with connected wallets, names should be lighter
5. Spot users with claimed names, should be white
> feat: implemented a color scheme for avatar name tags

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarsLODController.cs
Closes #3876, that was extracted from #3385 (where you can find more info about the issue)
Method `ComposeLODControllersSortedByDistance` was using LINQ. I reverted it to a normal array.
1. Run in editor scene with 80+ avatars
2. Observe in Profiler no allocation from AvatarsLODController
> chore: remove LINQ from AvatarsLODController

- unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationsTracker.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarSystemUtils.cs
Closes #3933
It was reported that we could highlight hidden avatars but the actual issue was that the avatar was not visible.
This PR fixes 2 common exceptions that occur when loading avatars on certain conditions, thus failing and getting the whole avatar revealing system stuck. 
https://play.decentraland.zone/?renderer-branch=fix/invisible-avatars&ENABLE_AVATAR_OUTLINER
It should be from very hard to near impossible to find invisible avatars that can be highlighted, if it happens, please post the exception. 
> fix: exceptions caused avatars to never end loading or never show up

- .github/auto_assign_config.yml
Update the autoassign tool to have a new tech-leads reviewers
> chore: set a new reviewers group for tech leads

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModel.cs
The profile updating event is only triggered when the profile equality check fails. This fixes:
- many pagination buttons over the names section in the passport
- many GET requests for lands and names while the passport is opened
- passport being reloaded for no reason
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/names-lands-repetitive-requests
2. Go to a crowded place (ideally 10+ users around)
3. Open the http requests tab in the developer console
4. The friends and names request should be triggered only once. Example: `/lambdas/nfts/names/:id` or `/lambdas/nfts/lands`
5. Let the user to change a wearable, name, anything in the profile. A request should be triggered again.
6. Go to the names section, the pagination "dots" should be displayed correctly
7. Open your …
> hotfix: names & lands repetitive requests when the passport is opened

- unity-renderer/Assets/DCLPlugins/LoadingScreenPlugin/LoadingScreenPlugin.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DataStore_LoadingScreen.cs
Fix dataStoreLoadingScreen.visible when the AB-test is disabled
...
2. ...
> Fix decoupled loading screen enabled when the AB test is off

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/IPassportApiBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/WebInterfacePassportApiBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/Interfaces/ITheGraph.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/Interfaces/VariablesTypes.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/TheGraph.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/TheGraph/TheGraphQueries.cs
Fixes #3991
When we clicked on the BUY button of some NFTs inside the Profile, it sometimes takes us to the Marketplace front page instead of the specific item.
- In order to get the necessary information to build the marketplace's url for an NFT (basically we need the collectionId + the tokenId of the NFT), when the passport opens, we send a query to TheGraph (to both networks ETHEREUM and POLYGON) to obtain the list of owned NFTs belonging to the user that we're loading in the passport. As result we always have these 2 pre-loaded lists with the TheGraph information: `ownedNftCollectionsL1`  and `ownedNftCollectionsL2`.
- When we click on the BUY button of any NFT item loaded in the passport, we try to find that NFT in the pre-loaded lists mentioned above. If we find it, we get the the …
> fix: Clicking on BUY on NFTs in the Profile does not open the right link

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Handler/ECSTransformHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Tests/ECSTransformParentingSystemShould.cs
closes https://github.com/decentraland/sdk/issues/520
removing a parent entity while setting it child's `parent` property was raising an exception due to child transform was still child of the removed entity transform
> fix: sdk7 exception while removing parent entity

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Fixes clicking on chat notifications not opening the chat window with that user.
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/open-dm-from-noti
2. Take two friend users, both in different locations in the world, far away from each other
3. Do not open any friends window with user A
4. Write a private message from user B to user A
5. User A should receive a DM notification
6. Click the notification
7. The chat window should be opened as expected
> fix: chat not opening from notification when the friend was not previously loaded

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Main/Main.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/PlayerPrefsGeneralSettingsRepository.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/HideUIControlController.cs
- unity-renderer/unity-renderer.sln.DotSettings
Closes #3999 
Settings were saved only when closing the UI. So it wasn't saved in case if user pressed sign-in (Guest) or log-out (Wallet) button before closing settings UI.
**Solution:**
- Since I didn't found any exit-point for the WebGL application to put the saving logic there, I directly subscribed to the SingIn and LogOut events to solve just this particular cases - it is inside `ProfileHUDController.cs` constructor and `Dispose` methods.
- I also added `Settings.Save(`) to `Main.ApplicationWantsToQuit()`, method, but it will work only in Standalone client.
`HideUI`, `ShowAvatarNames` and `CameraControl` userSettings were not saved in any scenario.
**Solution:** added respective logic in `PlayerPrefsGeneralSettingsRepository` and adjusted `HideUIControlController`
1. Go to: …
> fix: settings should not be cleared when user logs out

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsApiBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/RPCFriendsApiBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/Helpers/FriendsController_Mock.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridge.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridgeProxy.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
Fix #4023 (Point 2 of this issue: `Friends who are offline are not being displayed`)
From the second time on we opened the friends window, the offline list was always loading empty.
The problem was that, after re-opening the HUD from a second time and clean its lists, when we received the new list of friends from the backend, when the flow reached the `UpdateFriendshipStatus()` function, we had this condition:
```
if (friends.ContainsKey(userId) && friends[userId].friendshipStatus == friendshipStatus)
return;
``` 
In this case, as the new friends received already were loaded in our internal dictionary `friends`, the flow was being always canceled and never added the data into the HUD.
The main problem here is that we were using the `UpdateFriendshipStatus()` for managing the request of …
> fix: Offline friends sometimes don't load

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerName/PlayerName.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileWebInterfaceBridge.cs
Fixed a few null reference exceptions caused by the userId being null when loading avatar shapes.
Also fixed the nameplate background being visible when the player name is null. 
https://play.decentraland.zone/?renderer-branch=fix/avatar-shape-name&realm=redeemer.dcl.eth
The avatar in the mirror should be visible and the nameplate of those avatars should be invisible.
> fix: avatar shape with null user id failing to load

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
This pull request removes the feature flag `explorer-use_gpu_only_meshes_variant` for the A/B test that was implemented to test any performance impact for uploading mesh data to gpu.
The test results have shown a slight performance gain, so this PR is setting this behaviour as default.
Group A display results with the feature disabled, and group B with the feature on.
1. Go to: https://play.decentraland.zone/?renderer-branch=chore/clean-up-use-gpu-only-meshes-ab-test
2. No change should be visible with 3d models.
> chore: clean up use_gpu_only_meshes feature flag

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/_LoadingScreen.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
Maintaince task for decoupled loading screen.
In desktop, the null blit texture appears rotated 180 degrees. This PR adds a check to rotate the image accordingly.
Also, it turns off by default the blit texture in the prefab, since it was generating a white flash in that platform.
All of these is testable in desktop. To test that nothing broke in renderer,
1. https://play.decentraland.zone/?renderer-branch=fix/decoupled-loading-screen-rotated-image-in-desktop&ENABLE_DECOUPLED_LOADING_SCREEN
2. Teleport around. No issues should be visible
> fix: Decoupled loading screen rotated image in desktop

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/GltfContainer/GltfContainerHandler.cs
Fixes some features not working because of the hierarchy change of gltfast 
Clone https://github.com/decentraland-scenes/sdk7-goerli-plaza.git
Run `avatar-swap` with `dcl start`
Add `&renderer-branch=fix/gltfast-sdk7&ENABLE_GLTFAST` to the URL
The character should animate correctly.
> fix: collider setup in sdk7 not working with gltfast

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Tests/PlayerInfoCardHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Tests/PlayerInfoCardHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Scripts/UserContextMenu.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Tests/UserContextMenuShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/UserContextMenu/Tests/UserContextMenuTest.asmdef
`Fixes #3914 `
Enables or disables the friends UI depending on a feature flag: `explorer-friends_enabled`.
1. Go to: https://play.decentraland.zone/?renderer-branch=feat/friends-feature-flag
2. None of the UI should be referring to the friends feature
3. Go to: https://play.decentraland.org/?renderer-branch=feat/friends-feature-flag
4. The friends UI should be enabled as usual
> feat: disabled friends ui by a feature flag

- .github/workflows/main.yml
- README.md
Signed-off-by: Juan Ignacio Molteni <juanignaciomolteni@gmail.com>
Updates the github action so it shows the correct branch name after kernel merger
> chore: update githubactions with new branch name

- unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationLoader.cs
Disabled the Animation component of loaded emotes to avoid the processing overhead
Performance increase scales with the amount of NFT emotes that were loaded
In the next example there's a great amount of them and the overhead can be greatly reduced. 
- Check that base emotes and NFT emotes work correctly.
- Check that you can see another avatar rather than yourself being animated correctly while their use an emote.
> fix: emotes performance degradation

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
Fix #4167 
Solves 2 things:
- A NullRef that we were not managing correctly in the `CatalogController.WearablesRequestFailed` method.
- A wrong behavior of the backpack which caused it to stuck when the request of the owned wearables failed.
1. Switch your metamask to GOERLI.
2. Go to: https://play.decentraland.zone/?explorer-branch=fix/null-wearable-is-added-to-inventory&BUILDER_SERVER_URL=https://builder-api.decentraland.zone/v1&NETWORK=goerli&DEBUG_MODE=true&WITH_COLLECTIONS=9c4d923f-3e19-4abc-a012-33397f1e10ea
3. Open the backpack.
4. Notice that, even if the owned wearables failed when they were requested, the rest of the backpack (avatar preview and all the rest of wearables) loads correctly.
5. Close the backpack.
6. Notice the user's flow doesn't break. …
> fix: The backpack breaks when the owned wearables request fails

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/Resources/UIInputText.prefab
The users cannot put the focus on any input text of any scene.
The problem was that the `UIInputText.prefab` had the `RaycastTarget` deactivated in its text component:
1. Go to: https://play.decentraland.org/?explorer-branch=hotfix/missing-raycast-target-on-scenes-ui-input-text
2. Go to GolfCraft scene.
3. Open one of the input text of the scene.
4. Check that you can click on the input box and write.
> hotfix: Fix interactivity of the scenes input texts

- unity-renderer/Assets/Scripts/CodeStyleExample.cs
chore: suppress warning on hiding deprecated "animation" field
As suggested by the C# compiler:
```
Assets\Scripts\CodeStyleExample.cs(56,27): warning CS0108: 'CodeStyleExample.animation' hides inherited member 'Component.animation'. Use the new keyword if hiding was intended.
```
> chore: suppress warning on hiding deprecated "animation" field

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateTPS.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Fixes #4107 
Go to 119,-12, there shouldnt be a `Look rotation viewing vector is zero` error anymore
> fix: remove cases where the character forward was set to 0,0,0.

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/SceneControllerServiceShould.cs
Issue to fix the flaky test: https://github.com/decentraland/unity-renderer/issues/4222
> fix: disable `CallGetCurrentStateWithoutStoredState` flaky test

- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/SceneControllerService/Tests/SceneControllerServiceShould.cs
Related to https://github.com/decentraland/unity-renderer/issues/4222
> fix: disable `CallGetCurrentStateWithStoredState` flaky test

- .github/auto_assign_config.yml
Added "No QA Needed" to exclussion list, since the previous one was modified.
> chore: add "No QA Needed" label to exclussion list in auto assign tool

- .github/CODEOWNERS
Signed-off-by: Mateo Miccino <mateomiccino@gmail.com>
Due to issues with the notifications, the code-owners will work in a different way for explorer-team 
> chore: remove @decentraland/explorer-team as CODEOWNER

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
Steps to reproduce:
* Log in as guest, without wallet
* Click on a user
* You should see a "Connect your wallet" modal blocking the passport view
* Press Escape
What should happen with this fix:
* Both the Passport and the "Connect Wallet" modals get hidden
Error happening in production:
* The Passport is closed, but the "Connect Wallet" modal is still open
> fix: close connect wallet modal when pressing ESC

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadata.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/MapRendererShould.cs
Avoids duplication of POIs by adding a correct comparison of `MinimapMetada.cs`. Issue described further in [here](https://app.zenhub.com/workspaces/workstream-core-experience-63aaac346e1c8d00104586e8/issues/gh/decentraland/unity-renderer/4244) and [here](https://app.zenhub.com/workspaces/workstream-core-experience-63aaac346e1c8d00104586e8/issues/gh/decentraland/unity-renderer/4294) 
Using this [video ](https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1675259138800659) as reference
1. Go to: -84,-135. Move your camera around and check the fps
2. Wait 10 minutes
3. Move your camera around and check the fps. Performance degradation shouldnt be as bad as in the video
4. Check that the POIs in the map are the same as in `prd`
5. Test that the POIs thumbnails are showing the correct …
> fix: Avoid duplication of POIs in Map

- .circleci/config.yml
- scripts/hash-unity-files.sh
[Offending code](https://github.com/decentraland/unity-renderer/blob/1632eb12d26eb5c7454690c2453b0430190ee217/scripts/src/inject-sentry-params.ts#L53)
Also, leaving the `.txt` with checksums as circleci artifacts for easier debugging of these kind of issues later
> fix: Sentry script busting the cache

- browser-interface/packages/config/index.ts
- browser-interface/packages/shared/web3.ts
Because `eth` contract calls are pretty slow (particularly over metamask), the function to get the list of catalysts from the DAO contract was taking ~10 seconds out of every boot. This hard-codes the values into the code for a faster boot, without removing the logic to actually fetch the catalysts' list from the DAO contract.
> feat: hardcode catalyst selection

- browser-interface/packages/shared/session/sagas.ts
Another set of requests were getting blocked by the lack of definition of which network to use -- this should save a couple more seconds to start the renderer
> feat: send ethereum network before renderer initializes

- browser-interface/packages/shared/loadingScreen/sagas.ts
- browser-interface/packages/shared/meta/types.ts
- browser-interface/packages/shared/store/rootSaga.ts
fix explorer not loading when feature flag `decoupled_loading_screen` is not enabled
> fix: loading when `decoupled_loading_screen` feature flag is disabled

- .github/workflows/set-rollout.yml
Temporal fix, because the release process is publishing incorrect artifacts. We're going to check those artifacts before releasing.
> chore: set rollout to .org to 0%

- browser-interface/packages/shared/world/positionThings.ts
- browser-interface/test/unit/positionThings.test.tsx
This prevents awkward interactions with greenblockers if scenes around have not been loaded. Scene owners are free to fix their spawn point to this position anyways!
Test plan:
- Enter a scene with a defined start position (for example, genesis plaza). Ensure that scene defined spawn point is used
- Enter a scene with no spawn position defined (for example, 46,74). Ensure that you spawn in the middle of the scene, and not strictly in the edge of a corner (a relative 0,0 of the scene)
- Enter a scene with a 0,0 spawn position defined (for example, aetheria at 110,100). Ensure that you spawn strictly in the corner
> feat: spawn in middle of scene by default

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/IMainChatNotificationsComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/MainChatNotificationsComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Tests/ChatNotificationControllerShould.cs
Fix #4427
Hides notification area when no notifications are present
...
1. Go to: https://play.decentraland.zone/?explorer-branch=fix/hide-notifications
2. Verify that notifications tab doesn't appear when overing if there are no notifications
3. Get notifications
4. Check the notification panel appears correctly
> Fix: hide notification area when no notifications are present

- browser-interface/packages/shared/scene-loader/sagas.ts
Steps to test:
Current bug:
- Clear local storage
- Log in as a guest
- Ensure the signup flow isn't broken by a teleporting logo
Potentially affected flows:
- Sign up as new user, with wallet
- Login as existing guest
- Login as existing wallet user (with and without localstorage session)
- Teleporting
- Starting not on genesis plaza
> fix: race condition on signup flow

- unity-renderer/Assets/Tutorial/Prefabs/Resources/TutorialView.prefab
When rendering the robot, we used a regular renderer with SSAO and other features enabled, which is not very visible to the user. 
This change set the skybox renderer to the tutorial camera, which has all the features disabled.
> fix: changed tutorial camera to use skybox renderer

- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxCamera.cs
- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxController.cs
When showing fullscreen UI there is not point in rendering anything under. We already disable main camera, but skybox was still rendering
Open and close main menu. There should not be any visible change, skybox should be visible.
> fix: disabling skybox camera when fullscreen ui is visible

- unity-renderer/Assets/Rendering/Common/UniversalRenderPipelineAsset.asset
- unity-renderer/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Configuration/Controls/RenderingScaleControlConfiguration.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/SettingsControlModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUD/Scripts/ControlsModule/SettingsControlView.cs
Closes #4342 
Common changes are:
- disable additional lights in general Quality settings 
Changes per Quality Preset
- disabled Ambient Occlusion
- drop Resolution to Normal from MatchScreen
- drop Ambient Occlusion to Low
- drop Shader Quality to Low
- drop Resolution Scale to 0.75
- drop Anti-Aliasing to 2
- drop Shader Quality to Medium
- drop Resolution Scale to 0.86
2. Go to Settings->Quality and choose these 4 presets - Low, Medium, High, Ultra
3. Observe quality changed accordingly to the description above for LOW-MEDIUM-HIGH☝️
4. Check that performance is better (use `/debug` window)
> Chore: adjust quality settings presets

- browser-interface/packages/shared/comms/selectors.ts
- browser-interface/packages/shared/profiles/sagas/fetchProfile/index.ts
- browser-interface/test/unit/profiles.saga.test.tsx
The `fetchProfile` function makes 5 calls to `yield select`. This makes the fetching of profiles more efficient by only issuing one `select` effect.
> refactor: single select to increase efficiency of profiles

- browser-interface/packages/shared/realm/resolver.ts
Replaces the realm name for its hostname or url
- To foster transparency and to provide meaningful information about where you are connected to
- To reduce issues caused by repeated realm names (unresolvable)
- To enable reload of the explorer keeping the previous connection. Repro steps:
1. Load play.decentraland.org
2. `/changerealm https://sdk-test-scenes.decentraland.zone/` (now the url says `realm=LocalPreview`)
3. Reload the explorer
4. It won't get reconnected, this PR fixes it
> feat: use hostnames as realmname

- browser-interface/packages/shared/realm/resolver.ts
Reverts decentraland/unity-renderer#4477 -- introduces problems when loading worlds
> revert: "feat: use hostnames as realmname"

- browser-interface/packages/shared/realm/resolver.ts
This reverts commit a6b445ecb70cc25f9e8192c0b1c1d5ab73d51bcf. Related to https://github.com/decentraland/unity-renderer/pull/4494
> revert: "feat: use hostnames as realmname (#4477)"

- .github/workflows/main.yml
Fixes an extra parenthesis on gh action bot commenting with links
> fix: typo on gh build commenter

- .github/workflows/set-rollout.yml
The rollout to .org was set to 0% due to a failure on the cdn-uploader. Now that it is working again, there is no need to have the rollout to 0%.
Reverts decentraland/unity-renderer#4407
> chore: set rollout to .org to 100%

- unity-renderer/Assets/DCLServices/MapRendererV2/Addressables/MapCameraObject.prefab
- unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererChunkComponentsFactory.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/ComponentsFactory/MapRendererConfiguration.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/IMapCameraController.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/IMapCameraControllerInternal.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/IMapInteractivityController.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/IMapInteractivityController.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/IMapInteractivityControllerInternal.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/IMapInteractivityControllerInternal.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/MapCameraController.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/MapCameraInteractivityController.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/MapCameraInteractivityController.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/MapRenderImage.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapCameraController/MapRenderImage.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/MapLayer.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/ParcelHighlight.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/ParcelHighlight/IParcelHighlightMarker.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/ParcelHighlight/IParcelHighlightMarker.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/ParcelHighlight/ParcelHighlightMarker.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/ParcelHighlight/ParcelHighlightMarker.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/ParcelHighlight/ParcelHighlightMarkerObject.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/MapLayers/ParcelHighlight/ParcelHighlightMarkerObject.cs.meta
- unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapCameraController/MapCameraControllerShould.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapCameraController/MapCameraInteractivityControllerShould.cs
- unity-renderer/Assets/DCLServices/MapRendererV2/Tests/MapCameraController/MapCameraInteractivityControllerShould.cs.meta
Closes #4264
- Added `MapCameraInteractivityController` that handles high-level input events on camera basis:
- `HighlightParcel` to highlight the hovered parcel
- `GetParcel` under the cursor to comply with the current API of `NavmapToastView`
- Added `MapRenderImage`: a lower level class to handle pointer events and transform them for the higher level API
> Add Map Interactivity Controller and Map Render Image

- browser-interface/packages/shared/world/positionThings.ts
Reverts #4410, and moves the spawn position by default to be (1,1) instead of 0,0 to avoid green blockers
Rationale:
* All sample scenes and templates from the CLI have a hard-coded 0,0 spawn point. So, the change introduced in #4410 is only effective on scenes created manually, copying code, or by builder.decentraland.org
* builder.decentraland.org has no way of setting spawn points, so the user is likely to appear in the middle of buildings or, maybe even worse, colliders.
* Thus, the rationale for #4410 is probably only effective on empty parcels, and introducing undesirable effects on all builder-created scenes.
> revert: spawn on the middle of the scene

- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxController.cs
Fixes #4542 by adding a null check on a skybox race condition
1. Try to reproduce the bug reported on the issue. Check that it doesnt occur anymore
> fix: race condition for skybox on guest flow

- unity-renderer/ProjectSettings/ProjectSettings.asset
To analyze the toggle, I made a test in which I enter DCL and leave through the North door. The following conclusion are observed: 
**With IGC disabled**
On GC fired: 134.26 ms
Constant GC: Around 6.55 ms
**With IGC enabled**
Worst GC spike: Worst 21.77 ms, 12.67 ms during a couple of frames
Constant GC: Around 8.03 ms
When IGC enabled, we can see that we got **dismissable** increase GC occurring on every frame. Most importantly, on a GC spike, we can see it clearly distributed.
If the IGC is disabled, we have one huge spike that most probably will cause a hiccup.
Therefore, it is recommended to move forward and integrate the IGC. 
No QA needed
> chore: enable incremental gc

- unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs
Using `@dcl/sdk@next` new ui components can be used such as [the uiInput/Input component](https://github.com/decentraland/documentation/blob/3dd43fce83c4b76a24e8fe4dee1e37bcc37ac2bb/content/creator/sdk7/2d-ui/ui_special_types.md).
The `onChange` event result of the text input wasn't being sent back correctly to the scene, as the input is captured during the `Update()` and the `uiInputSenderSystem` was being updated [during the `Update`](https://github.com/decentraland/unity-renderer/blob/3ba5144d5495fe9e9871c8c1d216e8b6bde7446b/unity-renderer/Assets/DCLPlugins/ECS7/Systems/ECSSystemsController.cs#L103) instead of `LateUpdate()`, so the `InternalECSComponent<InternalUIInputResults>`'s model `isDirty` value was being reset before actually [sending the result to the …
> fix: sdk7 uiInput onchange input result

- unity-renderer/Assets/Rendering/ProceduralSkybox/ToolProceduralSkybox/Scripts/SkyboxController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenController.cs
Copy of [4545](https://github.com/decentraland/unity-renderer/pull/4545), since a branch name change is needed for merge to main
Fixes #4542 by adding a null check on a skybox race condition
Fixes #4503  a race condition for signup flow on goerli
Fixes #4504
> hotfix: guest flow race conditions

- .github/workflows/set-rollout.yml
Due to the unstability of the CI artifacts, we are setting the rollouts to 0%
> chore: rollout to 0%

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/ReceivedFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendRequestHUD/SendFriendRequestHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChannelMembersHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PrivateChatModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowComponentViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUD.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
Fetches the user profile when is not in cache in many social features:
- friend requests
- channel members
- friend list
- friend request list
- direct message list
1. Go to: https://play.decentraland.zone/?explorer-branch=fix/ensure-user-profiles
2. Check that the described social features are working as expected
3. Check that the pagination is working correctly when is possible
4. Check that the chat is working properly: #nearby, #channels, private messages
> fix: ensure user profiles in social features

- .circleci/config.yml
If we change the LIBRARY_CACHE_VERSION from the CircleCI Environment Variables, all the builds will start over without the cache of the library. We can use this when the library cache is corrupt.
> chore: add library cache versioning

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs
Closes #4558 after enabling the new feature flag `AB-NEW-CDN`
When loading worlds the scene-id has a different format so we had to fix this case to get the correct entity id to load the asset bundles with the new CDN flow
- Go to: https://play.decentraland.org/?explorer-branch=fix/new-cdn-worlds&ENABLE_AB-NEW-CDN&realm=dclonboarding.dcl.eth
- use `/detectabs` chat command 
- Check that most/all assets should be green ( blue for the colliders ) 
> fix: ab not loading with new cdn flow for worlds

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
When we load the Asset Bundles we upload the Meshes to the GPU and mark them as non-readable since that free's up some memory, but some meshes might fail to be used as colliders on WebGL.
Base Example: https://play.decentraland.org/?explorer-branch=fix/new-cdn-worlds&ENABLE_AB-NEW-CDN&realm=dclonboarding.dcl.eth
This branch: https://play.decentraland.org/?explorer-branch=test/remove-gpu-meshes&ENABLE_AB-NEW-CDN&realm=dclonboarding.dcl.eth
On the base Example if you go to the end of the tutorial ( the part of the portals ) you can move through the portals and clip into the mesh.
On this PR the mesh collider works correctly.
> fix: AB colliders not working because they are not readable on WebGL

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Transform/Serialization/ECSTransformSerialization.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Deserializer/Tests/CRDTDeserializerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/CRDTProtocol/Serializer/Tests/CRDTSerializerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryReader/ByteUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/BinaryMessage/BinaryWriter/BinaryWriter.cs
change binary endianness from big-endian to little-endian
for crdt's header and transform component
this change should improve performance while parsing messages since it avoid the step of converting byte arrays to little-endian
js-sdk pr: https://github.com/decentraland/js-sdk-toolchain/pull/446
> refactor: sdk7 change crdt header and transform binary endianness (LE)

- browser-interface/packages/config/index.ts
- browser-interface/packages/shared/portableExperiences/sagas.ts
- browser-interface/test/index.ts
- browser-interface/test/sceneEvents/comms.spec.ts
- browser-interface/test/unit/RestrictedActions.test.tsx
- browser-interface/test/unit/friends.saga.test.ts
- browser-interface/test/unit/portableExperiences.test.tsx
- browser-interface/test/unit/world.saga.test.tsx
Fixes the tests of the browser-interface so that they only take ~1s
(Developers only -- no change in production)
1. Run `make watch` in `browser-interface`
2. Open http://localhost:8080/?test
3. Check the duration of running the tests
> fix: run tests in ~1s

- browser-interface/packages/config/index.ts
- browser-interface/packages/lib/logger/logger.ts
- browser-interface/packages/shared/world/SceneWorker.ts
- browser-interface/static/preview.html
This enables to pipe of the console calls to an iframe parent
Editor counterpart: https://github.com/decentraland/editor-sdk7/pull/12
https://github.com/decentraland/sdk/issues/631
> feat: (preview mode) enable pipe the console .log and .error to the parent in a iframe

- unity-renderer/Assets/Rendering/Culling/CullingController.cs
- unity-renderer/Assets/Rendering/Culling/Tests/CullingControllerShould.cs
CullingController is messing up with the Offscreen Update of SkinnedMeshRenderer even with the CullingController disabled. 
Ideally objects should be constructed in a proper manner so the pivot doesnt stray too far away from the model (even when animated). 
Since we are evaluating removing the whole system I added a feature flag to allow the changes in `Offscreen Update` or not so we can A/B test it's implications in performance.
This is hard to test, you have to find a skinned mesh renderer (like the humanoids walking around genesis plaza). With `ENABLE_SMR_OFFSCREEN_UPDATE_STATUS` and the Detail Culling in Settings disabled luckily you will be able to reproduce that looking at the models from weird angles make them dissapear. On contrary, with not using …
> fix: disable offscreen culling for SkinnedMeshRenderer by feature flag

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Scripts/LoadingScreenView.cs
Turns off the blit loading image before it starts to fade out.
Teleport around. Eveything should be the same
> fix: hiding blit image of loading screen on show

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFDownloaderWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/ContentProvider.cs
Fixed several null references caused by unexpected empty or invalid assets, promises should fail gracefully now.
- Go to [-76,-9](https://play.decentraland.org/?explorer-branch=fix%2Fnull-ref&position=-77%2C-9)
- The scene loads
> fix: several null refs and added better errors for content creators

- browser-interface/packages/shared/world/SceneWorker.ts
Increases scene timeout to 2 minutes. This is a requirement for MVFW 2023, since there are a couple of scenes not loadings. The current scene shows whatever is in the scene once the timeout is reached, and this is a problem, since many times it shows uncompleted assets or even an empty scene alltogether. The increased timeout will give more time to users with slower connection.
The increasing or decreasing of this number is flawed, and its currently just a mitigation. A new PoC is in the works which would allow proper handling of download times and its corresponding realtime feedback. Also, it will include a user feddback and decision system, in which the user will be able to take action when the scene is not loading; like keep waiting or go where he came from.
More info on the …
> chore: increase scene timeout to 120

- ci-import-avpro.sh
AVPro package was not being imported correctly in desktop. This PR fixes that
1. Launch the explorer version
2. Go to a parcel with videos (like 64,64)
3. See a couple of videos
4. Check the Player.log. Check that you have AVPros log (like AVPro initializing)
> chore: fixed avpro package in desktop

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerPassportHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportInfoHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Tests/PassportInfoHUDControllerShould.cs.meta
Fix #4654
Adds the guest panel notification only when trying to add friend in passport and not in passport open
...
1. Launch the explorer as a guest https://play.decentraland.org/?explorer-branch=fix/guest-panel-passport
2. Open a passport
3. Check the passport can be used
4. Press add friend
5. verify that the guest panel appears
_______
1. Launch the explorer as a regular user https://play.decentraland.org/?explorer-branch=fix/guest-panel-passport
2. verify that the passport works as always
> fix: show guest panel only when trying to add friend from passport

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Utils/CoordinateUtils.cs
Fix #4669
Fixes clickable coordinates in chat
...
2. Type some valid coordinates in chat
3. Verify they are highlighted and are clickable without any issues
> Fix: fixed clickable coordinates in chat

- browser-interface/packages/shared/comms/adapters/LivekitAdapter.ts
Adds event tracking in 2 particular situations:
* When there is a comms error trying to send data to LiveKit.
* When receiving a disconnect event from the server.
This would capture the events and/or exceptions and allow us to determine why disconnections happen. This might (or might not) be related to https://github.com/decentraland/unity-renderer/issues/4489.
> fix: add tracking for error events

- browser-interface/packages/shared/scene-loader/sagas.ts
- browser-interface/packages/shared/world/positionThings.ts
- browser-interface/test/unit/positionThings.test.tsx
Closes #4652
When jumping to a scene we used to select a random spawn point defined by the scene.
Now we are selecting the spawn point that is nearest to our jump coordinates.
This means that if we have a scene that is 4x4 parcels and has a spawn point at each corner, the teleport positions will be:
| B 	| B 	| C 	| C 	|
|---:	|:---:	|:---:	|---	|
| B 	| B 	| C 	| C 	|
| A 	| A 	| D 	| D 	|
| A 	| A 	| D 	| D 	|
Being:
A: Lower-left
B: Top-Left
C: Top-Right
D: Lower-Right
- Go to [MVFW Road scenes](https://play.decentraland.org/?explorer-branch=feat%2Fspawn-points&realm=baldr&position=-73%2C6)
- Open the map and click near the corners (that are inside the green box), if that parcel is a road, you will get teleported to the nearest spawn point (at the time I'm writing this, the scene has 4 …
> feat: spawn point based on teleport position and nearest spawn point

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/StandaloneInputModuleDCL.cs
Closes #4658 (Probably)
**Problem** - in the direct access to the `key` in the `Dictionary` which could be not present there at the time of the request. 
**Solution**  - usage of the method in the parent class `PointerInputModule.GetPointerData(..)` that check if key exist and if not, it creates one;
**Note** - the only user of this call was `NeedToUnhoverWhileCursorUnlocked` (in `PointerEventsController`)
2. Check that unhovering behavior for the cursor behaves as previously (for example when action buttons are pressed)
> fix: InputModule KeyNotFoundException

- unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs
Url param `DISABLE_force_to_request_wearables_through_kernel]` causing issues with wearables when entering world `menduz.dcl.eth` directly on startup.
Clear cache, log in with "DISABLE_force_to_request_wearables_through_kernel" and "realm=menduz.dcl.eth" params. Guest arrives at the initial character creation screen with "Problem loading your wearables" error and a blank avatar. Wallet: (After a lengthy loading) logs in with "loading scene timeout" error message and a blue hologram-looking avatar missing its wearables.
> fix: error loading wearables for guest users in worlds

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
`Fixes #4612 `
1. Go to: https://play.decentraland.zone/?explorer-branch=feat/nearby-default
2. Hit ENTER key
3. The ~nearby channel should open
4. Hit back and then open the conversation list
5. Close the conversation list
6. Hit ENTER key
7. The ~nearby channel should open
8. Go to the conversation list and open any #channel or DM
9. Close the chat window
10. Hit ENTER key, the last chat window should be opened (#channel or DM)
> feat: open ~nearby channel by default when hitting ENTER key

- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
Transparent objects should ignore SSAO. The main reason SSAO was bleeding into transparent objects is because the SSAO pass is performed after the opaque objects and before the transparent ones. This cannot be changed, and therefore the postprocessing layer was painting the AO calculated behind some transparent objects.
To fix this, I modified the shared dependency at https://github.com/decentraland/unity-shared-dependencies/pull/18.
This PR above must be merged before this one, which updates the package version.
Go to -109 -18. The "clock-man" face should no longer bleed AO.
Take a look at the rest of the world and look for regressions in SSAO.
> fix: transparent objects and SSAO

- README.md
- browser-interface/Makefile
Fixed the `Makefile` of `browser-interface` for it to work with Windows.
Added a tutorial to setup `browser-interface` using `Visual Studio Code` with `devcontainer` extension. 
Follow the` browser-tutorial` setup-guide
> feat: browser-interface for windows and tutorial

- browser-interface/packages/shared/profiles/sagas/initialRemoteProfileLoad.ts
This PR fixes the case where the local profile has a wrong `hasClaimedName` value set to `false`, showing the owned ENS name as any other guest name and propagating this data to other peers. This could be caused by a faulty connection or any error from The Graph query which was then persisted locally and a version number higher than the one found remotely.
The current PR consolidates the name and hasClaimedName values in the profile and tries to update the local and remote ones when a change is detected on startup and increments the version number appropriately to avoid prior versions shadowing the correct status.
> hotfix: check for claimed name locally and consolidate if owned

- unity-renderer/Assets/DCLPlugins/ECS7/Systems/SceneBoundsCheckerSystem/ECSSceneBoundsCheckerSystem.cs
lack of parcels array in global scenes was triggering a null exception on the scene boundaries checker while running playground
> fix: sdk7 playground

- browser-interface/packages/shared/profiles/sagas/handleCommsProfile.ts
With the motivation of loading near profiles quicker, this PR changes the call to fetch peer profile in the comms loop (whenever a profile is announced around the player) to make the call non-blocking, changing the `call` from redux-sagas framework to a `spawn` one.
This change makes the call to `fetchPeerProfile` from a blocking one having to wait for the answer/timeout to a non-blocking one which should still be consistent writing the responses to the common store.
2. Go to a scene with many other players present (e.g. the poker scene or Genesis plaza starting point)
3. See how avatars should appear quicker than in the current released version (at least the ghost of them should appear much faster)
https://github.com/decentraland/unity-renderer/blob/master/docs/code …
> hotfix: making comms loop for fetching profiles concurrently using spawn

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
Avoid sorting by timestamp the messages sent to `~nearby` channel. Instead, add them sequentaly.
Comms does not calculate any server timestamp, so depending on the user's local timestamp, messages could be in the wrong order.
2. Send/receive private messages. Load previous history. Messages should be correctly sorted in the list.
3. Send/receive messages in ~nearby. Messages should be correctly sorted in the list.
4. Send/receive messages in #channels. Load previous history. Messages should be correctly sorted in the list.
> hotfix: nearby chat sequence sorting

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs
Friendship button in the passport should not be available if the friends service is not initialized.
2. Open the friend list, if its loading means friends are not initialized yet
3. Inspect your passport and other user passports
4. Check that the friendship button is hidden
5. After friends service initializes, check that the friendship button is shown as expected
> hotfix: hide friendship if friends are not initialized

- browser-interface/packages/shared/profiles/sagas/fetchProfile/index.ts
To mitigate the current timeouts when fetching profiles from comms peers and trying to optimize the use of the catalysts, this PR introduces a race between the both while also checking the version of the profile returned for the catalyst branch.
2. Go to the channels tab and enter one
3. Click on the menu for a given user and show profile
4. The profile should be taking considerable less time to load (the state of things before this PR would be >4.5s for a set timeout and retry strategy nonworking as expected for the use case)
> hotfix: race comms and catalyst fetching for profile with version

- unity-renderer/Assets/DCLServices/Lambdas/LambdasService.cs
- unity-renderer/Assets/DCLServices/Lambdas/Tests/LambdasServiceShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/IWebRequestAsyncOperation.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/WebRequestAsyncOperation.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/WebRequestExtensions.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/SentryUtils/IWebRequestMonitor.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/SentryUtils/SentryUtils.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/SentryUtils/SentryWebRequestMonitor.cs
Fixes #4052 
Source of the issue:
`SentryWebRequestMonitor`
```
private static void SetSpanStatus(ITransaction transaction, UnityWebRequest webRequest)
{
if (webRequest.WebRequestTimedOut())
transaction.Status = SpanStatus.DeadlineExceeded;
else
{
transaction.Status = webRequest.responseCode switch
{
200 => SpanStatus.Ok,
404 => SpanStatus.NotFound,
400 => SpanStatus.InvalidArgument,
403 => SpanStatus.PermissionDenied,
409 => SpanStatus.Aborted,
500 => SpanStatus.InternalError,
503 => SpanStatus.Unavailable,
401 => SpanStatus.Unauthenticated,
429 => SpanStatus.ResourceExhausted,
504 => SpanStatus.DeadlineExceeded,
_ => SpanStatus.UnknownError
};
}
}
```
was calling `UnityWebRequest `'s API on the disposed instance.
The instance was disposed if a first attempt fails as …
> hotfix: change SentryWebRequestMonitor to track IWebRequestAsyncOperation

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingByTimestamp.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntrySortingSequentally.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
Fixes chat sorting for ~nearby messages.
Nearby messages are not being sorted. Private messages & channel messages are sorted by timestamp.
2. Send and receive more than 30 messages in ~nearby channel
3. Send and receive more than 30 messages in private conversation
4. Send and receive more than 30 messages in #test channel
> hotfix: nearby chat sorting

- browser-interface/packages/shared/portableExperiences/sagas.ts
- browser-interface/packages/shared/renderer/actions.ts
- browser-interface/packages/shared/renderer/reducer.ts
- browser-interface/packages/shared/renderer/sagas-helper.ts
- browser-interface/packages/shared/renderer/selectors.ts
- browser-interface/packages/shared/renderer/types.ts
- browser-interface/packages/unity-interface/dcl.ts
A race condition on scene initialization was not allowing avatars to be clicked when a PX was present
1. Enter using the PX https://play.decentraland.org/?explorer-branch=hotfix/global-scenes-disorder&GLOBAL_PX=urn%3Adecentraland%3Aentity%3Abafkreie2hjsspbw37gbgkgftuhm5ppjvy2wzuxbjsdeif26z7tuig4cxfq%3FbaseUrl%3Dhttps%3A%2F%2Fsdk-content-server.decentraland.org%2Fipfs%2F&realm=heimdallr
2. Check that you can click on other avatars
3. Teleport using the PX. Check if you can click on avatars there as well
4. Remove the PX from the url. Enter DCL and check that you can click in avatars.
5. Repeat the [1 - 2] steps but entering using https://play.decentraland.org/?explorer-branch=hotfix/global-scenes-disorder&GLOBAL_PX=urn:decentraland:entity:bafkreihpipyhrt75xyquwrynrtjadwb373xfosy7a5rhlh5vogj …
> hotfix: global scenes disorder

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD_V2.prefab
When we press [U] (or change the corresponding option in the seetings panel) to hide all the UI, the ProfileHUD had not been hidden.
1. Go to: https://play.decentraland.org/?explorer-branch=hotfix/hide-profile-hud-when-press-u
2. Press [U] (or check "Hide UI" from the Settings Panel)
3. Check that the ProfileHUD on the top right of the screen is being hidden.
4. Press [U] again (or uncheck "Hide UI" from the Settings Panel)
> hotfix: hide profile hud when all the ui is hidden

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFTextureDownloaderWrapper.cs
- unity-renderer/Packages/packages-lock.json
Fixes #4708 
Related commit https://github.com/decentraland/glTFast/commit/cd8485999522daafc7cb5b990fce8f6fdf3f74ab
- There shouldn't be color differences between WebGL and Desktop
- in `LambdasWearablesCatalogService.cs` add this line at 59:
```C#
userId = "0x87956abC4078a0Cc3b89b419928b857B8AF826Ed";
```
- Disable Asset bundles
- Open your backpack and equip the steampunk wearables.
- Their colors should be fine
> hotfix: texture resize with incorrect color format

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExperiencesViewer/Resources/ExperienceRow.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExperiencesViewer/Resources/ExperiencesViewer.prefab
- unity-renderer/Assets/UIComponents/Resources/Button_OnlyImage.prefab
"Experiences" window (the UI where we load all the current active portable experiences) was completely unusable, we couldn't do any click on it (for example if we wanted to hide the UI of the MVFW PX).
1. Launch the explorer.
2. Open the Experiences viewer window.
3. Check that you can interact with the UI (close, show/hide PX, etc.).
> hotfix: experiences UI is completely unusable

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventCard_Long.prefab
Fix #4436
Fixes teleport button for future events in the events tab
...
1. Launch the explorer https://play.decentraland.org/?explorer-branch=fix/teleport-future-events
2. Go in the events section in the explore
3. Verify that the teleport button for ongoing events and future events works correctly
> fix: fixed teleport button for future events in explore panel

- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/FPSLimitControlController.cs
- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/PlayerPrefsDesktopDisplaySettingsRepository.cs
- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/SettingsDesktop/Tests/PlayerPrefsDesktopDisplaySettingsRepositoryShould.cs
- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/SpecificControllers/ShadowResolutionControlController.cs
Closes #3567
- add saving on value changed
- add saving desktop settings `OnApplicationQuit`
- add fps cap to Save/Load prefs
- fix test
1. Launch the desktop explorer
2. Change fps cap setting 
3. Exit the client by clicking on exit button 
4. Re-launch and observe fpsCap setting to be saved
> fix: fps limit settings does not persist after restart

- .github/workflows/sync-main-to-dev.yml
Due to Protected Branches, we cannot sync automatically from `main` to `dev`. So we're going to auto-create the PR
> hotfix: remove auto-sync between from main to dev and just create pr

- unity-renderer/Assets/DCLPlugins/EmoteAnimations/EmoteAnimationsTracker.cs
- unity-renderer/Assets/DCLPlugins/EmoteAnimations/Tests/EmoteAnimationsTrackerShould.cs
Fix some inconsistencies if the same emote was requested twice. Also fixed and reenabled some tests.
Triggering the error was super tricky, go to places with many people and look for a `An item with the same key has already been added` error. It shouldnt be present in the console.
Also take a look at emotes en general.
> fix: duplicated key in emote animation tracker + reenabled tests

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
Fixes a null ref that was reported on `#4770`
```C#
NullReferenceException: Object reference not set to an instance of an object
at DCL.Components.DCLVideoTexture+<ApplyChanges>d__20.MoveNext () [0x00167] in <a2f450b9556440c09c623236aef11acc>:0 
at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <e93b3aea730141c2bccba78f97e76c3e>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Sentry.Unity.Integrations.UnityLogHandlerIntegration:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```
- Run around MVFW scenes with Desktop Client
- …
> fix: null ref on disposed texture player not being handled well

- browser-interface/packages/shared/dao/sagas.ts
Possible edge case: If your internet goes down, the client will try to reconnect to a different realm, and it could set all the realms to already connected, and the realm selected could be null. So on that case, we bring a fatal error.
> hotfix: add fatal error when no valid catalyst are found

- browser-interface/packages/shared/comms/adapters/LivekitAdapter.ts
- browser-interface/packages/shared/comms/handlers.ts
- browser-interface/packages/shared/loading/ReportFatalError.ts
The current PR partially addresses #4513 bringing down the client and removing disabling comms from retrying to connect to the realm when it was initially kicked due to a duplicated id error (i.e. two tabs open with the same wallet address).
1. Launch the explorer on one tab with a given wallet
2. Launch the explorer on another tab with the same wallet
3. At least one of the two should get an error explaining the issue, bringing down the client and disconnecting from comms
4. The tab with no issue or a new tab if the previous two erred should be available to connect successfully with no realm issues
> hotfix: bring down client on id duplicated

- .circleci/config.yml
Fix the CI failing due to editmode results.
It was failing because the CI was caching incorrectly.
> chore: add editmode-results.xml to the tests to fix the caching problems

- unity-renderer/ProjectSettings/Physics2DSettings.asset
Closes #4821 
As per Unity recommendation,
Both 3D and 2D physics simulations are currently being run in the game, even though the game only uses
3D physics. Those updates cause unnecessary overhead, which can add up when multiple updates are
scheduled during the same frame.
We recommend that the team disables the 2D physics auto simulation in the Project Settings. The
relevant setting is Project Settings -> Physics 2D-> Simulation Mode -> Script.
We are changing the Simulation Mode from Fixed Update to Script
> chore: disable physcs 2D auto simulation

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/MainChatNotificationsComponentView.cs
Fixes that sometimes we get an exception on the notification panel due the notification entry being null.
The problem was due objects in the pool getting messed up between friend requests and chat messages. There was only one `entryPool` field for both kind of pools. When an entry was getting released, the internal object pool's linked list was nesting two different type of objects in the same pool.
The fix consists on referring to the correct pool depending on the type of notification.
```
NullReferenceException: Object reference not set to an instance of an object
DCL.Chat.Notifications.MainChatNotificationsComponentView.AddNewChatNotification (DCL.Chat.Notifications.PublicChannelMessageNotificationModel model) (at Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/Ma …
```
> fix: null chat notification entries in rare occasions

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
Fix #4786
Avoids pooled messages to appear yellow when no mention is detected
...
2. Send 30+ messages with mentions from a second account
3. Verify that after the 30 messages by sending regular messages without mentions the background is white and not yellow
> fix: fixed color reset for notifications with mention

- unity-renderer/Assets/Rendering/Utils/GPUSkinning/GPUSkinningThrottlerService.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarWithHologram.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Definitions/LoaderDefinitions/ILoader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Loader/Loader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Tests/AvatarShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarLOD/AvatarLODController/AvatarLODController.cs
- unity-renderer/ProjectSettings/Physics2DSettings.asset
Avatar was registering its `gpuSkinning `each time when calling `Load() `method. This cause the problem, since gpuSkinning instance is readonly assigned on Avatar creation, but `Load `called often - for example by `CharacterPreviewController` when changing wearables from backpack.
- now, when GPUSkinning is re-register, we just modify its timeBetweenFrames
- removed duplication in Avatar and AvatarWithHologramm classes (via inheritance and variation of Template Method pattern)
[Devs Only]
2. Change wearables in Backpack
3. [DevsOnly]: Observe no LogWarning in console from `gpuSkinningThrottlerService`
4. Check that Avatar and Hologrammed avatar behaves correctly
> fix: gpuSkinningThrottlerService.Register() called twice

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatControllerContextMenuUtility.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatMessage/ChatMessage.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntryModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DateSeparatorEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/DefaultChatEntry.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/IChatHUDComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDViewShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/DefaultChatEntryShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/IPrivateChatComponentView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatHUDView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/Resources/SocialBarV1/ChatHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ChatChannelHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IChatChannelWindowView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/IPublicChatWindowView.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/PublicChatWindowController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/ChatChannelHUDControllerShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/PublicChatWindowControllerShould.cs
Fetches the profile, if not available, when adding a chat message.
Fixes that sometimes you see the address of the user instead of the name in the message, either sender or recipient. 
2. Send and receive messages in ~nearby
3. Send and receive messages in private conversations
4. Send and receive messages in #channels (recommended to use #test)
5. If at any point you see an address instead of the user name, it should change to a proper name after a small period of time
> fix: usernames in chat messages

- unity-renderer/Assets/DCLPlugins/MapTexturePlugin/MapTexturePlugin.cs
Use GraphicsFormatUtility to get a compatible texture for every platform.
No "Texture creation failed" should appear, check WebGL, Windows and Mac builds. Additionally, the infinite floor should look correct.
> fix: force a compatible texture format for the platform

- unity-renderer/Assets/Desktop/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUDDesktop.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/Resources/DebugView.prefab
This branch contains stylistic adjustments of the minimap and debug panel.
**Minimap**
- Reduced the gap between the scene name and coordinates.
- The style of these fonts was changed in size and style as they were incorrect with respect to the original design.
Desktop
- Darkened the decentraland logo container to improve readability.
- The container and font of the beta label are smaller now.
**Debug panel**
- Font style and size updated
> style: minimap & debug panel polish

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Textures/Tests/TexturesTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/BlockedAndMasterPromisesShould.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/AssetPromise_GLTFast_Loader.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFTextureDownloaderWrapper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTFast/Wrappers/GLTFastDownloadProvider.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
- unity-renderer/Assets/UnityGLTF/Scripts/GLTFComponent.cs
- unity-renderer/Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs
- Old Gltf importer will now fail to load completely if an image is missing
- Added better error messages
Closes #5048
- Go to -60,38
- Both importers fail, scene must be almost empty
> chore: added better error handling for gltf importing

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfo.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfo.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/MeshesInfo/MeshesInfoUtils.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Interfaces/ISceneBoundsChecker.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsChecker.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_RedBox.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SBC_Asserts.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Tests/SceneTests.cs
- The `SceneBoundsChecker` immortal task now waits for the next `FixedUpdate` to re-check all entities
- The preliminary check of the `SceneBoundsChecker` now also waits for the next `FixedUpdate`
- `MeshesInfo.RecalculateBounds` is now async and waits for `FixedUpdate`
- All `SceneBoundsChecker` routines and tests are now Tasks
Fixes #5113
Fixes #4866 
For these coordinates `-109,-7` `23,78` do:
- Set the Scene load radius to 2
- Wait for the scene to load correctly
- Move somewhere else until the target scene is unloaded
- Move back until the scene loads correctly
- Those scenes shouldn't have invisible objects compared to the initial loading. 
> fix: boundaries not being in sync with the SBC

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
On some code paths, we still have flow exceptions leaking through this system, causing canceled asset requests to be loaded anyways by using the fallback path.
Fixes https://github.com/decentraland/unity-renderer/issues/5171
> fix: added cancellation handling on rendereable asset fallback

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
Introduced feature flag `ab-mesh-gpu` in order to experiment with a reduction of hiccups caused by `Physics.BakeMesh` in WebGL
The flag is ON by default.
If we disable this flag, all the meshes from the asset bundles won't get baked neither get uploaded to the GPU, reducing the hiccups caused by them and increasing the memory usage up to 90mb in Genesis Plaza
Related ticket: https://github.com/decentraland/unity-renderer/issues/4820
> feat: Physics.Bake in AB loading flow with a Feature Flag

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs
Fixes exception caused by new URN format.
New Asset bundles should load for worlds, check them with `/detectabs`
- Enter `dclonboarding.dcl.eth` realm in `.zone` ([link](https://play.decentraland.zone/?explorer-branch=fix/ab-urn-format&realm=dclonboarding.dcl.eth))
- Enter `dclonboarding.dcl.eth` realm in `.org` by adding `ENABLE_AB-NEW-CDN` flag ([link](https://play.decentraland.org/?explorer-branch=fix/ab-urn-format&realm=dclonboarding.dcl.eth&ENABLE_AB-NEW-CDN))
> fix: exception caused by fetching the scene ID from the new urn format

- unity-renderer/Assets/DCLServices/WearablesCatalogService/LambdasWearablesCatalogService.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/DataStore/DebugConfig.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Debugging/DebugParameters/DebugConfigComponent.cs
Sometimes we need to load another user's wearables for debugging reasons.
This override will make that chore a bit easier
> chore: added handy override to change wearables catalog based on another user id

- browser-interface/package-lock.json
- browser-interface/package.json
- browser-interface/packages/lib/decentraland/profiles/sceneRuntime/AvatarForUserData.ts
- browser-interface/packages/lib/decentraland/profiles/sceneRuntime/sceneRuntimeCompatibleAvatar.ts
- browser-interface/packages/lib/decentraland/profiles/transformations/profileToRendererFormat.ts
- browser-interface/packages/lib/decentraland/profiles/transformations/profileToServerFormat.ts
- browser-interface/packages/shared/profiles/sagas/handleDeployProfile.ts
- browser-interface/packages/unity-interface/BrowserInterface.ts
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/BackpackEditorHUDModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/CharacterPreview/CharacterPreviewController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModelDTO.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModelDTO.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModel.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModelDTO.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileModelDTO.cs.meta
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WebInterface/WebInterface.asmdef
Fixes #5221 
New property for profiles as discussed in ADR: https://github.com/decentraland/adr/issues/239
> feat: add `forceRenderer` property

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/VoiceChatHUD/Resources/SocialBarV1/VoiceChatBar.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/VoiceChatHUD/Resources/SocialBarV1/VoiceChatHUD.prefab
This PR fixes the dropdown menu and the missing mask rounded corners at the bottom of the chat window.
Plus, it includes the design update of the tooltip warning.
> style: voice chat dropdown menu and toast

- unity-renderer/Assets/DCLServices/Lambdas/LandsService/LandsResponse.cs
- unity-renderer/Assets/DCLServices/Lambdas/NamesService/NamesResponse.cs
- unity-renderer/Assets/DCLServices/Lambdas/PaginatedResponse.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PassportNavigation/PassportNavigationComponentController.cs
We changed the default Json deserializer for the one from Newtonsoft.
We had to fix a few DTO objects that used unity attributes
https://play.decentraland.org/?explorer-branch=fix/json-req
Names and Lands should appear correctly in the player's passport
> fix: failing requests because of json conversion incompatibility

- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/AvatarSystemUtils.cs
- unity-renderer/Packages/packages-lock.json
Apparently the overload for `string.Compare(string, StringComparison)` does not work correctly in `WebGL`
All avatars should have their custom skin an hair colors: https://play.decentraland.org/?explorer-branch=fix/white-skin-webgl
> fix: usage of string comparison not working correctly in webgl

- unity-renderer/Assets/Scripts/MainScripts/DCL/AvatarSystem/Avatar.cs
Added an old code that made sure that the avatar animator had its correct target, this workaround should be removed once we get rid of the old ABs
- test in https://play.decentraland.org/?explorer-branch=fix/avatar-preview
- Open backpack and see that the character animates correctly
- Open passport and see that the character animates correctly
> fix: avatar animations in backpack & passport

- unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/Catalyst/Catalyst.cs
Fixed issue with URLs not correctly normalized.
https://play.decentraland.org/?explorer-branch=hotfix/2023-06-22&realm=dclonboarding.dcl.eth
Go to `dclonboarding.dcl.eth` and check that your emotes load correctly.
> hotfix: catalyst urls not correctly normalized in worlds

- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.asmdef
- unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/RendereableAssetLoadHelper/RendereableAssetLoadHelper.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ContentProvider/ContentProvider.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/GlobalScene.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/ParcelScene.cs
Fetching the asset bundles for each scene blocked the flow of the scene loading causing the green blockers to appear very late, causing lots of issues with the avatar clipping through colliders
Fix #5406
Try running through the world.
Issue is present in https://play.decentraland.zone/
Issue should be fixed in https://play.decentraland.zone/?explorer-branch=fix/ab-blockers
> fix: green blockers not appearing when AB-NEW-CDN ff is on

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Animator/DCLAnimator.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
Fixed an issue caused by properties not being properly reset after being re-used by pools. 
- Go to Wondermine and wait for the first meteor to fall, it should animate correctly
- Mine the first meteor and wait for the second to fall, it should animate correctly
- Press F5 and start over at least 1 or 2 times since this bug was not deterministic enough to reproduce
> fix: issues with component pooling

- unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTextureShould.cs
Marked `VideoTextureIsDisposedAndReloadedCorrectly` as Flaky as it annoyed me enough already
> chore: mark flaky test as flaky

- unity-renderer/Assets/DCLServices/PlacesAPIService/PlacesAPIClient.cs
This hotfix changes the URL used for places search. It was erroneously pointing at .zone instead than .org
> hotfix: fixed places url form zone to org for search endpoint

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Addressables/ChannelSearchHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Addressables/ChatChannelHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Addressables/ChatNotificationHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Addressables/ConversationListHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Addressables/FriendsHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Addressables/NearbyChatChannelHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Addressables/TopNotificationHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/VoiceChatHUD/Resources/SocialBarV1/VoiceChatHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/Resources/DebugView.prefab
This PR fixes the horizontal social panels positions to match their alignment with the mini map and the tab bar that were recently updated.
1- Open [this](https://play.decentraland.org/?explorer-branch=style/FixSocialPanelsHorizontalPosition) link
2- Open all the social panels and check they are properly aligned horizontally with the mini map and tab bar. 
`Have into account the private channel panel is tackled in a different PR so here is not updated.`
> style: fix social panels horizontal position

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/AirdropNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/CameraModeLockedNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/CommsNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/GenericNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/GenericWithoutButtonNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/Notification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/NotificationHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/ScriptingErrorNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/UIHiddenNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/WarningNotification.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Prefabs/WarningNotificationNoIcon.prefab
This PR fixes inconsistencies with the design system guidelines for toast notifications plus missing textures and wrong canvas scale into the NotificationsHUD prefab.
Fixes visual inconsistency along all the notifications (background colour, textures, fonts size and style, icons)
Fixes notifications scale and textures
> style: notifications

- unity-renderer/Assets/DCLPlugins/ECS7/ECS7Plugin.cs
Moved scenes addition to sdk7 loaded scenes datastore to AFTER having its stuff initialized, the UiCanvasInformation system was not being able to update the component for late-loaded scenes since they didn't have their ComponentWriter initialized.
1. Access sdk7 goerli plaza world at 76, -10: https://sdk-test-scenes.decentraland.zone/?position=76%2C-10&realm=LocalPreview&explorer-branch=fix/sdk7-scenes-addition-to-datastore
2. After the world loads, without doing anything you should see a BLUE panel on top of the RED background panel, like so:
> fix: sdk7 scenes addition to loaded scenes datastore

- unity-renderer/Packages/manifest.json
- unity-renderer/Packages/packages-lock.json
Updated shared-dependencies package used to point to the [implementation branch](https://github.com/decentraland/unity-shared-dependencies/pull/19).
This was done to tackle the [rendering problem found](https://github.com/decentraland/unity-renderer/pull/5663#issuecomment-1699889258) since unity `2022.3.6f1`.
-----------------------
We need this PR tested as thoroughly as an RC.
Including:
* Full RC testing
* [Rendering issue](https://github.com/decentraland/unity-renderer/pull/5663#issuecomment-1699889258) not happening anymore in the onboarding world
* Testing new user onboarding
* Testing some popular scenes behaviour to see they keep working as in production
> chore: remove forced alphatest from srp batching helper

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/EventsSubSection/EventsSubSection.prefab
This PR fixes the horizontal space for the events cards grid, which was minor than required to match the large card edge on the right.
1- Open this link
2- Open the discover pressing tab or x and go to the events subsection.
3- Check that the small cards gap is okay erasing the blank gap on the right side.
> style: reduce events cards grid horizontal space

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/EquippedWearable.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/NFTIcon.prefab
This PR was created to fix the hover animation of the items visible in both sections of the profile card. 
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/ProfileCardHoverAnimation)
2- Open someones profile card and check that the rainbow outline asset is not covering the item information.
> style: fix item hover animation in player profile card

- browser-interface/packages/lib/web3/fetchCatalystNodesFromContract.ts
- browser-interface/packages/shared/dao/sagas.ts
This means:
- If FF is disabled (is currently disabled): you won't be ever assigned to main realm by realm picking algorithm
- `/changerealm main` will work irregardless of the FF status
- jumping on the main realm from the UI will work irregardless of the FF status
> chore: main realm is always available, but won't be realm picked unless FF is enabled

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/AvatarSlot/NftTypeIcons.asset
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/BackpackInfoCard.prefab
This PR fixes the missing the missing texture for "hides" and replaces the hand icon that was outdated.
1- Open this [link](https://play.decentraland.org/?explorer-branch=fix/InfoCardMissingHidesWearableIcn)
2- Open the backpack pressing [I]
3- Open the info card of an item that hides the hand wear category. Check the hides icon is visible and that the hand wear is the box glove instead of a hand.
> fix: info card missing icons

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/NavmapFilters.prefab
This PR adds the icons for the layers friends and people on the filter menu. This way users have a visual hint to understand how this two layers look in the map.
1- Open this link
2- Open the nav map
3- Open the filters and check both icons are visible and the functionality is still working properly
> style: add visual hint to layers

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesSubSection/PlacesSubSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/WorldsSubSection/WorldsSubSection.prefab
This PR was created to update the banners' copies inside `Genesis City` and `Worlds` sub-sections of the Discover tab.
Genesis city banner now says
`Decentraland's Genesis City map is made up of thousands of parcels owned and populated with dynamic content by its diverse community. Browse through some of the virtual world's most popular locations and jump directly to places of interest.
`
Worlds banner now says
`With just a Decentraland NAME, you can claim your own World, a personal 3D space separate from Genesis City, where you can unleash your creativity, host events, and more! Browse the directory and explore how others have used their Worlds.`
DAO disclaimer now says
`For the text underneath it could say: Only Worlds belonging to LAND owners or renters appear here as per this DAO …
> style: update discover tab copies

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/NavigationPanel.prefab
This PR fixes the missing texture when hover the zoom button in the nav map.
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/ZoomHoverTexture)
2- Open the nav map pressing [M] or tab
3- Hover the zoom in button in the nav map and check that the texture has been fixed. It should look like the following screenshot, not squared.
> style: add missing texture when hover map zoom button

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ContentModerationHUD/Prefabs/ContentModerationButtonForWorldsHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUD.prefab
This PR was created to fix the issues #5853 and #5855 
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/GoToGenesisTexture)
2- Go to the discover section pressing [x] or [tab]
3- Jump into any world
4- Check that the texture on the `go to genesis city` is visible (DCL icon)
5- The open the main menu and check the Content Moderation button is not visible overlapping the menu UI
> fix: go to genesis texture and canvas order of the content moderation buttons

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Prefabs/NavmapFilters.prefab
This branch is created to fix the missing info button next to the POI filter in the nav map. 
1- Open this [link](https://play.decentraland.org/?explorer-branch=fix/ToggleOnPoiInfo)
2- Open the Genesis City Map
3- Open the filters and check that the info button next to the POI filter is visible and the tooltip is shown when clicking it
> fix: POI info button

- unity-renderer/Assets/DCLFeatures/CameraReel/ScreenshotViewer/Prefabs/InfoSidePanel.prefab
This PR fixes the missing mask texture on the photo taken by avatar snapshot.
1- Open this [link](https://play.decentraland.org/?explorer-branch=styke/FixAvatarMaskInfoSidePanel)
2- Open the camera reel and then any of the pictures you have taken
3- Check on the side info panel that the edges of the avatar snapshot are not visible anymore. The pic now looks rounded.
> style: fix avatar pic mask on "photo taken by" 

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/Realms/RealmSelector_Modal.prefab
This PR was created to fix the real selector container that looks squared instead of rounded because its missing textures.
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/RealmsPanelFixContainer)
2- Press tab to open the main menu.
3- Open the realm selector clicking the button located on the left side of the nav bar.
> style: fix realm selector container

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Resources/_AvatarModifierAreaFeedbackHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Prefabs/ChannelMembersHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SocialBarPrefabs/SocialBarV1/Prefabs/NearbyMembersHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/Animations/Idle.anim
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/Resources/TeleportPromptHUD.prefab
This PR fixes the missing container on the avatar modifier disclaimer and Teleport Prompt. Besides, the teleport prompt has suffered a structural update in order to align the way scenes' information is displayed in the rest of the platform.
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/AvatarModifier-TeleportPrompt-ColapseChatMembers-Fix-Textures)
2- Open any chat conversation and write the coordinates 47,-45 (GolfCraft minigolf scene). Send the message and click on the blue highlighted coords of the message sent. 
3- Then walk to the "Oh my pixel" interactive wall located inside the scene, parcel 48,-45 to be precise. Get close enough to finally see the avatar modifier warning next to the mini map.
> style: fix textures for avatar modifier/teleport prompt and colapse chat members bar

- browser-interface/packages/unity-interface/dcl.ts
Fix hot reload for smart wearables.
It doesnt change any code that can be reached at play.decentraland.org.
It changes only a piece of code that is being called only with the Preivew mode
- create a smart wearable
- install this version of the sdk https://github.com/decentraland/js-sdk-toolchain/pull/822#issuecomment-1789569493
- run npm start and when the explorer opens, add the following param to the url `&explorer-branch=fix/sw-hot-reload`
> fix hot reload for smart wearables

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmoteCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmotesCustomizationSectionV2.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BackpackEditorHUDV2/Prefabs/WearableGridItemView.prefab
This PR was created to fix the horizontal position of the smart wearable icon, new label, and sound icon for backpack items. With this fix their position behaviour is dynamic, meaning that they readapt depending on the width of the item card.
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/IconsLabelsPositionOnItems)
2- Open the backpack in the avatar section. Play resizing the browser window and validate the position of the new label and the smart wearable icon are positioned correctly on the items which have it.
3- Then go to the emotes section and check that the position of the sound icon is okay.
> style: fix items' icons and labels horizontal position

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/Animations/In.anim
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/Animations/Out.anim
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/Resources/TeleportPromptHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDController.cs
This PR was created to fix the copy and architecture of the event module in the Teleport prompt.
It should look like this now:
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/LiveEventContainerTeleportPrompt)
2- Go to the events column in the genesis plaza and click on the jump in button of a live event card.
3- Check that instead of `current event` now the label says `live` and the amount of players is next to it. Note that instead of a solid container in the background now there is a gradient. All this was done in order to align its aesthetic with the discover cards (was outdated). Plus, the whole modal is bigger now.
> style: update live event container on teleport prompt

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Tween/ECSTweenHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/Tween/Tests/ECSTweenHandlerShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Systems/TweenSystem/ECSTweenSystem.cs
* Moved Tweener killing from `ECSTweenSystem` into `ECSTweenHandler.OnComponentRemoved()`
* Added test
The problem was basically that in the time between the `ECSTweenHandler.OnComponentRemoved()` and the `ECSTweenSystem.Update()` (which handled the tween killing recognizing the component removal) the hot reload could happen at that point in the middle and an old entity that got recycled could still have its Tweener affecting its transform.
Issue: https://github.com/decentraland/sdk/issues/987
----------------------------------------
* **HOT RELOAD**: We call Hot Reload the process that re-loads the current scene in development when something is changed in the scene code and the scene is reloaded automatically (this only happens in preview mode, AKA when creators are implementing their …
> fix: sdk7 tween component preview mode hot reload

- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarModifierArea/Handler/AvatarModifierAreaComponentHandler.cs
- unity-renderer/Assets/DCLPlugins/ECS7/ECSComponents/AvatarModifierArea/Tests/AvatarModiferAreaShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Systems/AvatarModifierAreaSystem/ECSAvatarModifierAreaSystem.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Systems/AvatarModifierAreaSystem/Tests/ECSAvatarModifierAreaSystemShould.cs
- unity-renderer/Assets/DCLPlugins/ECS7/Tests/ECS7Plugin.Tests.asmdef
Dynamic modification of Avatar Modifier Area component excluded ids property wasn't being handled correctly.
Fixes https://github.com/decentraland/sdk/issues/999#issuecomment-1876163659
------------------
1. Open [this playground link](https://playground.decentraland.org/?code=Y29uc3QgZXhjbHVkZWRVc2VyID0gJ1VTRVItV0FMTEVULUFERFJFU1MtR09FUy1IRVJFJwpjb25zdCBhdmF0YXJNb2RpZmllckFyZWFFbnRpdHkgPSBlbmdpbmUuYWRkRW50aXR5KCkKY29uc3QgYXJlYVNpemUgPSBWZWN0b3IzLmNyZWF0ZSg0LCA0LCA0KQoKVHJhbnNmb3JtLmNyZWF0ZShhdmF0YXJNb2RpZmllckFyZWFFbnRpdHksIHsgCiAgcG9zaXRpb246IFZlY3RvcjMuY3JlYXRlKDgsIDEsIDgpLAogIHNjYWxlOiBhcmVhU2l6ZQp9KQpBdmF0YXJNb2RpZmllckFyZWEuY3JlYXRlKGF2YXRhck1vZGlmaWVyQXJlYUVudGl0eSwgewogIGFyZWE6IGFyZWFTaXplLAogIG1vZGlmaWVyczogW0F2YXRhck1vZGlmaWVyVHlwZS5BTVRfSElERV9BVkFUQVJTXSwKICBleGNsdWRlSWRzOiBbZX …
> fix: sdk7 avatar modifier area dynamic excluded ids

- README.md
Fixed outdated instructions for running a local build with local kernel.
> fix: local build instruction docs

- unity-renderer/Assets/DCLServices/EmotesService/Domain/IEmotesService.cs
- unity-renderer/Assets/DCLServices/EmotesService/EmotesService.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
- unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/RPC/Services/EmotesService/EmotesRendererServiceImpl.cs
Updated `TriggerSceneExpression()` method to inject the scene content url, so that the feature also works in Worlds.
Fixes https://github.com/decentraland/sdk/issues/1042
--------------------------------------
Confirm that after clicking the blue button, the avatar plays a dancing emote animation.
https://play.decentraland.zone/?realm=builder-api.decentraland.zone%2Fv1%2Fprojects%2Fee7b5bbe-f9be-4ae6-9b7a-b5fd2b5786c4&NETWORK=sepolia&DEBUG_SCENE_LOG=&position=0%2C0&explorer-branch=fix/sdk7-worlds-scene-emotes-content-url
https://github.com/decentraland/unity-renderer/assets/1031741/8de47bd2-7fdf-4c63-906c-33e7cc3f710f
> fix: sdk7 worlds scene emotes url

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/PlacesAndEventsSection.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/Sections/PlacesAndEventsSection/WorldsSubSection/WorldsSubSection.prefab
- unity-renderer/Assets/Textures/UI/Worlds/GenesisCityBanner.png
- unity-renderer/Assets/Textures/UI/Worlds/WorldsBanner.png
Genesis City and Worlds sections banners now have a brand new style!
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/discover-banners)
2- Open the menu in the discover section and check that the Genesis City and Worlds banners have been replaced with the new art.
> style: update discover banners

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/ExploreV2Menu.prefab
PR created to remove the `new` label from the camera reel tab, which is not a new feature since a long time. Collaterally solves the issue #5803. 
1- Open this link.
2- Open the main menu and check that the new label doesn't appear anymore as in the following screenshot.
> style: remove new label from camera reel tab

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WalletHUD/Prefabs/WalletSectionHUD.prefab
This PR was created to add the missing `it` at the beginning of the Ethereum MANA description.
1. Open this [link](https://play.decentraland.org/?explorer-branch=style/wallet-copy)
2. Open the main menu and go to the wallet section. Check the description of Ethereum MANA starts with an **It**
> style: fix ethereum mana copy

- unity-renderer/Assets/DCLFeatures/CameraReel/Gallery/Prefabs/Header.prefab
- unity-renderer/Assets/DCLFeatures/CameraReel/Gallery/Scripts/CameraReelGalleryStorageView.cs
- unity-renderer/Assets/DCLFeatures/CameraReel/Gallery/Scripts/ThumbnailContextMenuController.cs
- unity-renderer/Assets/DCLFeatures/CameraReel/ScreenshotViewer/Scripts/ScreenshotViewerController.cs
- unity-renderer/Assets/DCLServices/ScreencaptureCamera/UI/Prefabs/ScreencaptureCameraHUD.prefab
This PR was created to replace the word `pictures` by `photos` in every component of the camera UI in order to keep wording consistency. 
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/replace-pictures-for-photos)
2- Go to the camera reel section in the menu and check the copy says `Storage n/500 **photos** taken` instead of `photo` in singular.
3- Then try to delete one of the pics and check in the prompt the word `pictures` had been replaced by `photos`.
4- Now go back to the world and enter the camera mode. Take as many photos as you can until reach the storage limit. Check the warning toast now says `photos` instead of `pictures`.
5- Then go back to the camera reel and check the storage warning saying pictures now says `photos` in the nav bar.
> style: replace the word pictures by photos in the camera and camera reel UI

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Resources/MainMenu/Realms/RealmViewer.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/LoadingScreen/Resources/_LoadingScreen.prefab
- unity-renderer/Assets/Textures/UI/Common/DCLLogo.png
- unity-renderer/Assets/Textures/UI/Common/TexturesUI.spriteatlas
The DCL logo has a brand new look. This PR was created to update the logo texture.
This impacts on the loading screen and menu tab bar. The logos may look pretty similar, but have into account that now the wordmark is bigger and more rounded than the previous one.
1- Open this [link](https://play.decentraland.org/?explorer-branch=style/update-logo)
2- Check during the loading screen the new logo is visible
3- Open the menu and validate the logo has been also updated in the realm selector button in the tab bar.
> style: update Decentraland logo

- browser-interface/packages/shared/apis/host/CommunicationsController.ts
- browser-interface/packages/shared/comms/sceneSubscriptions.ts
- browser-interface/packages/shared/scene-loader/genesis-city-loader-impl/emptyParcelController.ts
- browser-interface/packages/shared/types.ts
- browser-interface/packages/shared/wearablesPortableExperience/sagas.ts
- browser-interface/packages/unity-interface/dcl.ts
- browser-interface/packages/unity-interface/portableExperiencesUtils.ts
- browser-interface/test/unit/RestrictedActions.test.tsx
- browser-interface/test/unit/portableExperiences.test.tsx
Use always the `entity.id` as scene identifier by comms. Right now the identifier changes if you're in the genesis city, world or custom realm.
Jump to the beer scene using two tabs (that's why the guest=true is on):
https://play.decentraland.org/?explorer-branch=fix/unify-scene-id-by-comms&realm=sdk-team-cdn.decentraland.org%2Fipfs%2Fgoerli-plaza-test-psquad-demo-latest&skipSetup=true&guest=true&position=73%2C-7
If you pick up a glass, you have to be able to see it from the other tab.
> fix: unify to entity.id the scene_id by comms, remove unused code

- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmoteCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/EmotesCustomization/EmoteSlotCard.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmotesWheelHUD/Resources/EmotesWheelHUD.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Resources/PlayerPassport.prefab
- unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
- unity-renderer/Assets/Textures/UI/Common/EmotesIcon.png
- unity-renderer/Assets/Textures/UI/Common/EmotesOff.png
- unity-renderer/Assets/Textures/UI/Common/EmotesOn.png
- unity-renderer/Assets/Textures/UI/Passport/PassportIcons/EmotesIcn.png
As the emotes icon, represented by a hand, was not very intuitive there is a new representation of a humanoid dancing as an icon.
This new icon impacted the backpack emotes section, the emotes persistent button, and the emotes slots from the wheel as marked in the images bellow.
2. Check the HUD emotes icon on and off states are okay. 
3. Open the emotes wheel pressing `B` or by clicking the emotes button. Check the icon is updated on the slots' flaps.
4. While the wheel is opened, press `E` or `I` and check the emotes section icon has been updated. Same with emote items flap.
> style: emotes icon
